create table if not exists public.merchant_member_transactions (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.merchant_memberships(id) on delete cascade,
  merchant_user_id uuid not null,
  user_id uuid not null,
  action text not null,
  delta integer not null default 0,
  before_value integer not null default 0,
  after_value integer not null default 0,
  source text not null default 'manual',
  note text,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint merchant_member_transactions_action_check check (action in ('stamp', 'points', 'update')),
  constraint merchant_member_transactions_source_check check (source in ('manual', 'code_checkin', 'qr_checkin'))
);

alter table public.merchant_member_transactions enable row level security;

create index if not exists merchant_member_transactions_membership_idx
  on public.merchant_member_transactions (membership_id, created_at desc);

create index if not exists merchant_member_transactions_merchant_idx
  on public.merchant_member_transactions (merchant_user_id, created_at desc);

create index if not exists merchant_member_transactions_user_idx
  on public.merchant_member_transactions (user_id, created_at desc);

grant select, insert on public.merchant_member_transactions to authenticated;
grant usage, select on sequence public.merchant_member_transactions_id_seq to authenticated;

drop policy if exists "users and merchants can read member transactions" on public.merchant_member_transactions;
create policy "users and merchants can read member transactions"
on public.merchant_member_transactions
for select
to authenticated
using ((select auth.uid()) = user_id or (select auth.uid()) = merchant_user_id);

drop policy if exists "merchants can create member transactions" on public.merchant_member_transactions;
create policy "merchants can create member transactions"
on public.merchant_member_transactions
for insert
to authenticated
with check ((select auth.uid()) = merchant_user_id);
