(()=>{
const URL='https://ptxdxepmggmjcndgukjk.supabase.co',KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-',MEDIA='https://upload.escoopcity.com';
const app=document.getElementById('autoManageApp'),q=new URLSearchParams(location.search),S={merchantId:q.get('merchant')||'',listings:[],leads:[],screen:'home',edit:null,photos:[],lead:null,leadFilter:'all'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const session=()=>{try{return JSON.parse(localStorage.getItem('wanba_session')||'null')}catch{return null}};
const autoSalesApi=window.LeshenghuoAutoSalesApi?.create({supabaseUrl:URL,supabaseKey:KEY});
const api=(path,opt={})=>autoSalesApi.request(path,opt);
const money=v=>`$${Number(v||0).toLocaleString('en-US',{maximumFractionDigits:0})}`;
const close=()=>{if(parent!==window){parent.postMessage({type:'leshenghuo-close-auto'},'*');return}history.length>1?history.back():location.assign('/');};
const top=t=>`<header class="top"><button onclick="AutoAdmin.back()">‹</button><b>${esc(t)}</b><span class="right"><button onclick="AutoAdmin.close()">×</button></span></header>`;
const listingPhoto=x=>Array.isArray(x.photos)&&x.photos[0]?`<img src="${esc(x.photos[0])}" alt="">`:'<div class="photo">🚘</div>';
const stateText=x=>({available:'在售',reserved:'已预留',sold:'已售出',hidden:'已隐藏',new:'新线索',contacted:'已联系',scheduled:'已安排',reschedule_requested:'申请改期',cancelled:'已取消',quoted:'已报价',closed:'已完成',archived:'已归档'}[x]||x);
async function load(){if(!S.merchantId){app.innerHTML=`${top('二手车管理')}<div class="empty">缺少商家信息。</div>`;return}try{const r=await api('/rest/v1/rpc/merchant_auto_manager_list',{method:'POST',body:JSON.stringify({p_merchant_user_id:S.merchantId})}),d=await r.json();if(!r.ok)throw new Error(d.message||'load_failed');S.listings=Array.isArray(d.listings)?d.listings:[];S.leads=Array.isArray(d.leads)?d.leads:[];S.sales=Array.isArray(d.sales)?d.sales:[];render()}catch(e){const expired=/jwt|token|401/i.test(String(e.message||''));app.innerHTML=`${top('二手车管理')}<div class="empty">${expired?'登录状态已过期，请返回乐生活首页重新登录后再试。':'暂时无法读取后台，请稍后刷新重试。'}</div>`;}}
function render(){if(S.screen==='edit')return editView();if(S.screen==='lead')return leadView();const available=S.listings.filter(x=>x.status==='available').length,newLeads=S.leads.filter(x=>x.status==='new').length;app.innerHTML=`${top('二手车管理')}<div class="wrap"><div class="summary"><div><b>${S.listings.length}</b><span>车辆库存</span></div><div><b>${available}</b><span>正在出售</span></div><div><b>${newLeads}</b><span>新线索</span></div></div><div class="actions"><button class="btn primary" onclick="AutoAdmin.add()">＋ 添加车辆</button><button class="btn" onclick="AutoAdmin.refresh()">刷新后台</button></div><div class="tabs"><button class="${S.screen==='home'?'on':''}" onclick="AutoAdmin.home()">车辆库存</button><button onclick="AutoAdmin.leads()">客户线索 ${newLeads?`(${newLeads})`:''}</button></div><section><div class="section-title"><h2>在售车辆</h2><span>第一张照片为封面</span></div>${S.listings.length?S.listings.map(x=>`<div class="card listing"><button style="all:unset;display:flex;gap:12px;align-items:center;width:100%;cursor:pointer" onclick="AutoAdmin.edit('${esc(x.id)}')">${listingPhoto(x)}<div class="listing-info"><b>${esc(x.title)}</b><span>${esc([x.year,x.make,x.model,x.mileage?`${Number(x.mileage).toLocaleString()} mi`:''].filter(Boolean).join(' · '))}</span><strong>${money(x.price)}</strong></div><i class="status ${esc(x.status)}">${esc(stateText(x.status))}</i></button></div>`).join(''):'<div class="empty">还没有车辆。添加后会出现在商家的二手车店铺内。</div>'}</section></div>`;}
function leadList(){app.innerHTML=`${top('客户线索')}<div class="wrap"><div class="tabs"><button onclick="AutoAdmin.home()">车辆库存</button><button class="on">客户线索</button></div>${S.leads.length?S.leads.map(x=>`<button class="card lead" style="text-align:left;width:100%;font:inherit" onclick="AutoAdmin.openLead('${esc(x.id)}')"><div class="lead-head"><div><b>${esc(x.lead_type==='sell_quote'?'卖车估价':x.lead_type==='test_drive'?'预约试驾':'车辆咨询')} · ${esc(x.customer_name)}</b><span>${esc(x.customer_phone)} · ${new Date(x.created_at).toLocaleDateString('zh-CN')}</span></div><i class="status ${esc(x.status)}">${esc(stateText(x.status))}</i></div><p>${esc(x.lead_type==='sell_quote'?[x.vehicle_data?.year,x.vehicle_data?.make,x.vehicle_data?.model,x.vehicle_data?.mileage?`${x.vehicle_data.mileage} mi`:'' ].filter(Boolean).join(' · ')||'客户尚未补充车辆信息':x.message||'暂无留言')}</p></button>`).join(''):'<div class="empty">暂无客户线索。</div>'}</div>`;}
function editView(){const x=S.edit||{},photos=S.photos;app.innerHTML=`${top(x.id?'编辑车辆':'添加车辆')}<div class="wrap form"><label class="field">车辆标题<input id="autoTitle" maxlength="100" value="${esc(x.title||'')}" placeholder="例如 2022 Toyota RAV4 XLE"></label><div class="cols"><label class="field">品牌<input id="autoMake" value="${esc(x.make||'')}" placeholder="Toyota"></label><label class="field">车型<input id="autoModel" value="${esc(x.model||'')}" placeholder="RAV4"></label></div><div class="cols"><label class="field">年份<input id="autoYear" type="number" min="1900" max="2100" value="${esc(x.year||'')}"></label><label class="field">售价（美元）<input id="autoPrice" inputmode="decimal" value="${esc(x.price??'')}"></label></div><div class="cols"><label class="field">里程（英里）<input id="autoMileage" type="number" min="0" value="${esc(x.mileage||'')}"></label><label class="field">车型<select id="autoType">${['轿车','SUV','VAN','皮卡','跑车','其他'].map(v=>`<option ${x.vehicle_type===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="cols"><label class="field">能源<select id="autoFuel">${['汽油','柴油','混动','纯电'].map(v=>`<option ${x.fuel_type===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">变速箱<select id="autoTransmission">${['自动挡','手动挡','其他'].map(v=>`<option ${x.transmission===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="cols"><label class="field">驱动方式<input id="autoDrive" value="${esc(x.drivetrain||'')}" placeholder="AWD / FWD / RWD"></label><label class="field">外观颜色<input id="autoColor" value="${esc(x.exterior_color||'')}"></label></div><label class="field">VIN（仅商家后台完整可见）<input id="autoVin" maxlength="80" value="${esc(x.vin||'')}"></label><label class="field">车辆配置<input id="autoFeatures" value="${esc(Array.isArray(x.features)?x.features.join('，'):'')}" placeholder="用逗号分隔，例如 倒车影像，Apple CarPlay"></label><label class="field">车况与说明<textarea id="autoDescription" maxlength="3000" placeholder="车况、保养记录、事故说明等">${esc(x.description||x.condition_note||'')}</textarea></label><label class="field">上架状态<select id="autoStatus">${[['available','在售'],['reserved','已预留'],['sold','已售出'],['hidden','隐藏']].map(([v,n])=>`<option value="${v}" ${x.status===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field"><input id="autoCertified" type="checkbox" ${x.is_certified?'checked':''}> 标记为商家认证车况</label><label class="field">车辆图片<input id="autoPhotos" type="file" accept="image/*" multiple onchange="AutoAdmin.upload(this.files)"></label><div class="photo-list">${photos.map((u,i)=>`<div><img src="${esc(u)}"><button onclick="AutoAdmin.removePhoto(${i})">×</button></div>`).join('')}</div><div class="notice">图片会压缩后上传，第一张图片就是顾客浏览时看到的车辆封面。</div><button class="btn primary" style="width:100%;margin-top:15px" onclick="AutoAdmin.save()">保存车辆</button></div>`;}
function leadView(){const x=S.lead;if(!x)return leadList();const vehicle=x.vehicle_data||{},contact=[x.customer_phone,x.customer_email].filter(Boolean).join(' · ');app.innerHTML=`${top(x.lead_type==='sell_quote'?'卖车估价线索':'客户咨询')}<div class="wrap"><div class="card"><div class="lead-head"><div><b>${esc(x.customer_name)}</b><span>${esc(contact)}</span></div><i class="status ${esc(x.status)}">${esc(stateText(x.status))}</i></div><p>${esc(x.message||'暂无留言')}</p></div>${x.lead_type==='sell_quote'?`<section><div class="section-title"><h2>客户车辆</h2></div><div class="card"><b>${esc([vehicle.year,vehicle.make,vehicle.model].filter(Boolean).join(' ')||'资料待补充')}</b><p>${esc(vehicle.mileage?`${vehicle.mileage} 英里`:'')}</p></div></section>`:''}<label class="field">处理状态<select id="leadStatus">${[['new','新线索'],['contacted','已联系'],['scheduled','已安排'],['quoted','已报价'],['closed','已完成'],['archived','已归档']].map(([v,n])=>`<option value="${v}" ${x.status===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field">商家内部备注<textarea id="leadNote" maxlength="1500" placeholder="仅商家团队可见">${esc(x.merchant_note||'')}</textarea></label><button class="btn primary" style="width:100%;margin-top:15px" onclick="AutoAdmin.saveLead()">保存线索处理结果</button></div>`;}
function leadView(){const x=S.lead;if(!x)return leadList();const v=x.vehicle_data||{},photos=Array.isArray(x.photos)?x.photos:[],contact=[x.customer_phone,x.customer_email].filter(Boolean).join(' · '),photoBlock=photos.length?`<div class="photo-list">${photos.map(url=>`<img src="${esc(url)}" alt="客户车辆照片">`).join('')}</div>`:'<p style="color:#777;font-size:12px">客户未上传车辆照片。</p>';const fields=[['年份',v.year],['品牌 / 车型',[v.make,v.model].filter(Boolean).join(' ')],['里程',v.mileage?`${Number(v.mileage).toLocaleString()} 英里`:'' ],['车型',v.vehicle_type],['能源',v.fuel_type],['变速箱',v.transmission],['期望售价',v.expected_price?money(v.expected_price):''],['VIN 后六位',v.vin_last6]].filter(([,value])=>value);app.innerHTML=`${top(x.lead_type==='sell_quote'?'卖车估价线索':'客户咨询')}<div class="wrap"><div class="card"><div class="lead-head"><div><b>${esc(x.customer_name)}</b><span>${esc(contact)}</span></div><i class="status ${esc(x.status)}">${esc(stateText(x.status))}</i></div><p>${esc(x.message||'暂无留言')}</p></div>${x.lead_type==='sell_quote'?`<section><div class="section-title"><h2>客户车辆</h2></div><div class="card"><b>${esc([v.year,v.make,v.model].filter(Boolean).join(' ')||'资料待补充')}</b><div class="chip-list">${fields.map(([key,value])=>`<span>${esc(key)}：${esc(value)}</span>`).join('')}</div>${photoBlock}</div></section>`:''}<section class="card"><b>商家报价</b><div class="cols"><label class="field">报价金额（美元）<input id="leadQuoteAmount" type="number" min="0" inputmode="decimal" value="${esc(x.quoted_amount??'')}" placeholder="暂不报价"></label><label class="field">报价有效至<input id="leadQuoteExpires" type="datetime-local" value="${x.quote_expires_at?new Date(x.quote_expires_at-Date.prototype.getTimezoneOffset).toISOString().slice(0,16):''}"></label></div></section><label class="field">处理状态<select id="leadStatus">${[['new','新线索'],['contacted','已联系'],['scheduled','已安排'],['quoted','已报价'],['closed','已完成'],['archived','已归档']].map(([key,name])=>`<option value="${key}" ${x.status===key?'selected':''}>${name}</option>`).join('')}</select></label><label class="field">商家备注<textarea id="leadNote" maxlength="1500" placeholder="会显示给客户，用于说明报价或下一步安排">${esc(x.merchant_note||'')}</textarea></label><button class="btn primary" style="width:100%;margin-top:15px" onclick="AutoAdmin.saveLead()">保存报价与处理结果</button></div>`;}
async function saveLead(){const amount=document.getElementById('leadQuoteAmount')?.value.trim(),expires=document.getElementById('leadQuoteExpires')?.value;const r=await api('/rest/v1/rpc/merchant_auto_update_lead_quote',{method:'POST',body:JSON.stringify({p_lead_id:S.lead.id,p_status:document.getElementById('leadStatus').value,p_merchant_note:document.getElementById('leadNote').value.trim(),p_quoted_amount:amount===''?null:Number(amount),p_quote_expires_at:expires?new Date(expires).toISOString():null})});if(!r.ok){alert('保存失败，请确认已运行 v5.387 数据库更新后重试。');return}S.screen='leads';await load();leadList();}
function leadView(){const x=S.lead;if(!x)return leadList();const v=x.vehicle_data||{},photos=Array.isArray(x.photos)?x.photos:[],contact=[x.customer_phone,x.customer_email].filter(Boolean).join(' · '),dt=x.quote_expires_at?new Date(x.quote_expires_at).toISOString().slice(0,16):'',photoHtml=photos.length?`<div class="photo-list">${photos.map(url=>`<img src="${esc(url)}" alt="客户车辆照片">`).join('')}</div>`:'<p style="font-size:12px;color:#777">客户未上传车辆照片。</p>',carRows=[['年份',v.year],['品牌 / 车型',[v.make,v.model].filter(Boolean).join(' ')],['里程',v.mileage?`${Number(v.mileage).toLocaleString()} 英里`:'' ],['车型',v.vehicle_type],['能源',v.fuel_type],['变速箱',v.transmission],['期望售价',v.expected_price?money(v.expected_price):''],['VIN 后六位',v.vin_last6]].filter(row=>row[1]);app.innerHTML=`${top(x.lead_type==='sell_quote'?'卖车估价线索':'客户咨询')}<div class="wrap"><div class="card"><div class="lead-head"><div><b>${esc(x.customer_name)}</b><span>${esc(contact)}</span></div><i class="status">${esc(stateText(x.status))}</i></div><p>${esc(x.message||'暂无留言')}</p></div>${x.lead_type==='sell_quote'?`<section><div class="section-title"><h2>客户车辆</h2></div><div class="card"><b>${esc([v.year,v.make,v.model].filter(Boolean).join(' ')||'资料待补充')}</b><div class="chip-list">${carRows.map(row=>`<span>${esc(row[0])}：${esc(row[1])}</span>`).join('')}</div>${photoHtml}</div></section>`:''}<section class="card"><b>商家报价</b><div class="cols"><label class="field">报价金额（美元）<input id="leadQuoteAmount" type="number" min="0" inputmode="decimal" value="${esc(x.quoted_amount??'')}" placeholder="暂不报价"></label><label class="field">报价有效至<input id="leadQuoteExpires" type="datetime-local" value="${dt}"></label></div></section><label class="field">处理状态<select id="leadStatus">${[['new','新线索'],['contacted','已联系'],['scheduled','已安排'],['quoted','已报价'],['closed','已完成'],['archived','已归档']].map(row=>`<option value="${row[0]}" ${x.status===row[0]?'selected':''}>${row[1]}</option>`).join('')}</select></label><label class="field">商家备注<textarea id="leadNote" maxlength="1500" placeholder="会显示给客户，用于说明报价或下一步安排">${esc(x.merchant_note||'')}</textarea></label><button class="btn primary" style="width:100%;margin-top:15px" onclick="AutoAdmin.saveLead()">保存报价与处理结果</button></div>`;}
async function compress(file){const bitmap=await createImageBitmap(file),ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));}
async function upload(files){try{for(const file of [...files].slice(0,12-S.photos.length)){const blob=await compress(file),r=await fetch(`${MEDIA}/upload`,{method:'POST',headers:{Authorization:`Bearer ${session()?.access_token||''}`,'Content-Type':'image/jpeg','x-media-kind':'products'},body:blob}),d=await r.json();if(!r.ok||!d.url)throw new Error('upload_failed');S.photos.push(d.url)}editView()}catch(e){alert('图片上传失败，请确认登录后重试。')}}
async function save(){const get=id=>document.getElementById(id)?.value.trim()||'';const payload={id:S.edit?.id,title:get('autoTitle'),make:get('autoMake'),model:get('autoModel'),year:get('autoYear'),price:get('autoPrice'),mileage:get('autoMileage'),vehicle_type:get('autoType'),fuel_type:get('autoFuel'),transmission:get('autoTransmission'),drivetrain:get('autoDrive'),exterior_color:get('autoColor'),vin:get('autoVin'),features:get('autoFeatures').split(/[，,]/).map(x=>x.trim()).filter(Boolean),photos:S.photos,description:get('autoDescription'),status:get('autoStatus'),is_certified:!!document.getElementById('autoCertified')?.checked};if(!payload.title){alert('请填写车辆标题。');return}const r=await api('/rest/v1/rpc/merchant_auto_save_listing',{method:'POST',body:JSON.stringify({p_merchant_user_id:S.merchantId,p_listing:payload})});if(!r.ok){alert('保存失败，请检查车辆资料后重试。');return}S.screen='home';await load();}
async function saveLead(){const r=await api('/rest/v1/rpc/merchant_auto_update_lead',{method:'POST',body:JSON.stringify({p_lead_id:S.lead.id,p_status:document.getElementById('leadStatus').value,p_merchant_note:document.getElementById('leadNote').value.trim()})});if(!r.ok){alert('保存失败，请稍后重试。');return}S.screen='leads';await load();leadList();}
async function saveLead(){const amount=document.getElementById('leadQuoteAmount')?.value.trim(),expires=document.getElementById('leadQuoteExpires')?.value;const r=await api('/rest/v1/rpc/merchant_auto_update_lead_quote',{method:'POST',body:JSON.stringify({p_lead_id:S.lead.id,p_status:document.getElementById('leadStatus').value,p_merchant_note:document.getElementById('leadNote').value.trim(),p_quoted_amount:amount===''?null:Number(amount),p_quote_expires_at:expires?new Date(expires).toISOString():null})});if(!r.ok){alert('保存失败，请确认已运行 v5.387 数据库更新后重试。');return}S.screen='leads';await load();leadList();}
const renderAutoLeadBase=leadView;
function leadLocalDateTime(value){if(!value)return '';const date=new Date(value),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
leadView=function(){renderAutoLeadBase();const lead=S.lead||{},target=document.querySelector('#autoManageApp .wrap'),statusSelect=document.getElementById('leadStatus');if(statusSelect&&lead.lead_type==='test_drive'){[['reschedule_requested','客户申请改期'],['cancelled','客户已取消']].forEach(([value,label])=>{if(![...statusSelect.options].some(option=>option.value===value))statusSelect.add(new Option(label,value))});statusSelect.value=lead.status}if(!target)return;const vin=String(lead.vehicle_data?.vin||'').trim();if(vin)target.insertAdjacentHTML('beforeend',`<section class="card"><b>完整 VIN</b><p style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em">${esc(vin)}</p><small style="color:#777">仅限商家团队核验车辆历史报告使用，不会在公开车辆页展示。</small></section>`);if(lead.lead_type==='test_drive')target.insertAdjacentHTML('beforeend',`${lead.customer_action?`<section class="card"><b>${lead.customer_action==='cancel'?'客户申请取消试驾':'客户申请改期'}</b><p>${esc(lead.customer_action_note||'客户未填写说明。')}</p><small style="color:#777">重新确认试驾时间并保存“已安排”后，该请求会自动清除。</small></section>`:''}<section class="card"><b>试驾安排</b><label class="field">确认试驾时间<input id="leadConfirmedAt" type="datetime-local" value="${esc(leadLocalDateTime(lead.confirmed_at))}"></label><label class="field">试驾地点<input id="leadAppointmentLocation" maxlength="300" value="${esc(lead.appointment_location||'')}" placeholder="例如：门店地址或约定地点"></label><small style="color:#777">将状态设为“已安排”时，必须填写确认试驾时间。客户可在自己的试驾记录中查看。</small><button class="btn primary" style="width:100%;margin-top:12px" onclick="AutoAdmin.saveLead()">保存试驾安排</button></section>`);if(lead.lead_type==='sell_quote'&&lead.quote_response)target.insertAdjacentHTML('beforeend',`<section class="card"><b>客户报价决定</b><p style="color:${lead.quote_response==='accepted'?'#2f704c':'#a44747'}"><b>${lead.quote_response==='accepted'?'客户已接受报价':'客户暂不接受报价'}</b></p>${lead.quote_responded_at?`<small style="color:#777">${esc(new Date(lead.quote_responded_at).toLocaleString('zh-CN'))}</small>`:''}</section>`);};
const renderAutoLeadWithQuoteResponse=leadView;
leadView=function(){renderAutoLeadWithQuoteResponse();const lead=S.lead||{},statusSelect=document.getElementById('leadStatus');if(statusSelect&&lead.lead_type==='sell_quote'){[['quote_accepted','客户已接受报价'],['quote_declined','客户暂不接受报价']].forEach(([value,label])=>{if(![...statusSelect.options].some(option=>option.value===value))statusSelect.add(new Option(label,value))});statusSelect.value=lead.status;}};
async function saveLead(){const amountInput=document.getElementById('leadQuoteAmount'),expiresInput=document.getElementById('leadQuoteExpires'),confirmedInput=document.getElementById('leadConfirmedAt'),locationInput=document.getElementById('leadAppointmentLocation'),amount=amountInput?.value.trim(),expires=expiresInput?.value,confirmed=confirmedInput?.value,location=locationInput?.value.trim();const r=await api('/rest/v1/rpc/merchant_auto_update_lead_schedule',{method:'POST',body:JSON.stringify({p_lead_id:S.lead.id,p_status:document.getElementById('leadStatus').value,p_merchant_note:document.getElementById('leadNote').value.trim(),p_quoted_amount:amountInput?(amount===''?null:Number(amount)):S.lead.quoted_amount,p_quote_expires_at:expiresInput?(expires?new Date(expires).toISOString():null):S.lead.quote_expires_at,p_confirmed_at:confirmedInput?(confirmed?new Date(confirmed).toISOString():null):S.lead.confirmed_at,p_appointment_location:locationInput?(location||null):S.lead.appointment_location})});if(!r.ok){alert('保存失败。试驾设为“已安排”时，请填写确认试驾时间，并确认已运行 v5.389 数据库更新。');return}S.screen='leads';await load();leadList();}
const renderAutoAdminBase=render;
const autoLocale=()=>({en:'en-US','zh-TW':'zh-TW','zh-CN':'zh-CN'}[window.LeshenghuoI18n?.getLanguage?.()]||'zh-CN');
function driveScheduleView(){const drives=S.leads.filter(lead=>lead.lead_type==='test_drive'&&['scheduled','reschedule_requested'].includes(lead.status)).sort((a,b)=>new Date(a.confirmed_at||a.preferred_at||a.created_at)-new Date(b.confirmed_at||b.preferred_at||b.created_at));const today=new Date().toLocaleDateString('en-CA'),todayCount=drives.filter(lead=>lead.confirmed_at&&new Date(lead.confirmed_at).toLocaleDateString('en-CA')===today).length,rescheduleCount=drives.filter(lead=>lead.status==='reschedule_requested').length,statusText={scheduled:'已安排',reschedule_requested:'客户申请改期'};app.innerHTML=`${top('试驾日历')}<div class="wrap"><div class="summary"><div><b>${todayCount}</b><span>今日试驾</span></div><div><b>${rescheduleCount}</b><span>改期请求</span></div><div><b>${drives.length}</b><span>待处理试驾</span></div></div><div class="actions"><button class="btn" onclick="AutoAdmin.home()">返回车辆库存</button><button class="btn" onclick="AutoAdmin.leads()">查看客户线索</button></div>${drives.length?drives.map(lead=>{const time=lead.confirmed_at?new Date(lead.confirmed_at).toLocaleString(autoLocale(),{dateStyle:'medium',timeStyle:'short'}):lead.preferred_at?new Date(lead.preferred_at).toLocaleString(autoLocale(),{dateStyle:'medium',timeStyle:'short'}):'等待确认时间',listing=S.listings.find(item=>String(item.id)===String(lead.listing_id));return `<button class="card lead" style="text-align:left;width:100%;font:inherit" onclick="AutoAdmin.openLead('${esc(lead.id)}')"><div class="lead-head"><div><b>${esc(lead.customer_name)} · ${esc(listing?.title||'预约试驾')}</b><span>${esc(time)}${lead.appointment_location?` · ${esc(lead.appointment_location)}`:''}</span></div><i class="status ${esc(lead.status)}">${esc(statusText[lead.status]||lead.status)}</i></div>${lead.customer_action_note?`<p>${esc(lead.customer_action_note)}</p>`:''}</button>`}).join(''):'<div class="empty">暂无需要处理的试驾。</div>'}</div>`;}
render=function(){if(S.screen==='drive_schedule')return driveScheduleView();renderAutoAdminBase();if(S.screen==='home'){const actions=document.querySelector('#autoManageApp .actions');if(actions&&!document.getElementById('autoDriveScheduleButton'))actions.insertAdjacentHTML('beforeend','<button id="autoDriveScheduleButton" class="btn" onclick="AutoAdmin.driveSchedule()">试驾日历</button>')}};
function leadFilterLabel(filter){return ({all:'全部',new:'新线索',test_drive:'试驾',sell_quote:'卖车估价',quoted:'已报价'})[filter]||'全部'}
function leadMatchesFilter(lead){if(S.leadFilter==='all')return true;if(S.leadFilter==='test_drive'||S.leadFilter==='sell_quote')return lead.lead_type===S.leadFilter;return lead.status===S.leadFilter}
function leadList(){const rows=S.leads.filter(leadMatchesFilter),newCount=S.leads.filter(x=>x.status==='new').length,driveCount=S.leads.filter(x=>x.lead_type==='test_drive'&&['new','scheduled','reschedule_requested'].includes(x.status)).length,quoteCount=S.leads.filter(x=>x.lead_type==='sell_quote'&&['new','contacted','quoted'].includes(x.status)).length,filters=[['all','全部'],['new',`新线索${newCount?` (${newCount})`:''}`],['test_drive',`试驾${driveCount?` (${driveCount})`:''}`],['sell_quote',`卖车估价${quoteCount?` (${quoteCount})`:''}`],['quoted','已报价']];app.innerHTML=`${top('客户线索')}<div class="wrap"><div class="summary"><div><b>${newCount}</b><span>待处理</span></div><div><b>${driveCount}</b><span>试驾相关</span></div><div><b>${quoteCount}</b><span>报价相关</span></div></div><div class="tabs"><button onclick="AutoAdmin.home()">车辆库存</button><button class="on">客户线索</button></div><div class="tabs" style="overflow-x:auto;white-space:nowrap">${filters.map(([value,label])=>`<button class="${S.leadFilter===value?'on':''}" onclick="AutoAdmin.filterLeads('${value}')">${label}</button>`).join('')}</div>${rows.length?rows.map(x=>{const type=x.lead_type==='sell_quote'?'卖车估价':x.lead_type==='test_drive'?'预约试驾':'车辆咨询',vehicle=x.lead_type==='sell_quote'?[x.vehicle_data?.year,x.vehicle_data?.make,x.vehicle_data?.model].filter(Boolean).join(' · '):x.message||'暂无留言',phone=String(x.customer_phone||'').replace(/[^0-9+]/g,'');return `<article class="card lead"><button style="all:unset;display:block;width:100%;cursor:pointer" onclick="AutoAdmin.openLead('${esc(x.id)}')"><div class="lead-head"><div><b>${esc(type)} · ${esc(x.customer_name)}</b><span>${esc(x.customer_phone||'未留电话')} · ${new Date(x.created_at).toLocaleDateString('zh-CN')}</span></div><i class="status ${esc(x.status)}">${esc(stateText(x.status))}</i></div><p>${esc(vehicle||'客户尚未补充车辆信息')}</p></button>${phone?`<div class="lead-actions" style="margin-top:10px"><a class="btn" href="tel:${esc(phone)}">拨打电话</a><a class="btn" href="sms:${esc(phone)}">发送短信</a></div>`:''}</article>`}).join(''):`<div class="empty">${leadFilterLabel(S.leadFilter)}中暂无客户线索。</div>`}</div>`;}
window.AutoAdmin={close,back(){if(S.screen==='home')return close();if(S.screen==='lead'){S.screen='leads';return leadList()}if(S.screen==='sale'){S.screen='edit';return editView()}S.screen='home';render()},home(){S.screen='home';render()},leads(){S.screen='leads';leadList()},filterLeads(filter){S.leadFilter=filter;S.screen='leads';leadList()},driveSchedule(){S.screen='drive_schedule';render()},refresh:load,add(){S.edit={status:'available',vehicle_type:'轿车',fuel_type:'汽油',transmission:'自动挡'};S.photos=[];S.screen='edit';editView()},edit(id){S.edit=S.listings.find(x=>String(x.id)===String(id))||{};S.photos=[...(S.edit.photos||[])];S.screen='edit';editView()},upload,removePhoto(i){S.photos.splice(i,1);editView()},save,openLead(id){S.lead=S.leads.find(x=>String(x.id)===String(id));S.screen='lead';leadView()},saveLead};
const renderAutoEditWithVinDecoder=editView;
editView=function(){renderAutoEditWithVinDecoder();const vin=document.getElementById('autoVin');if(!vin||document.getElementById('vinDecodeControl'))return;vin.insertAdjacentHTML('afterend','<div id="vinDecodeControl" class="vin-decode"><button type="button" class="btn" onclick="AutoAdmin.decodeVin()">自动解析 VIN</button><small>使用 NHTSA 官方基础车辆资料；事故、产权和保养记录不包含在内。</small></div>');};
function nhtsaValue(data,key){return String(data?.[key]||'').trim();}
function nhtsaVehicleType(bodyClass){const value=String(bodyClass||'').toLowerCase();if(/pickup|truck/.test(value))return '皮卡';if(/van|minivan/.test(value))return 'VAN';if(/sport utility|suv|crossover|multipurpose|multi-purpose/.test(value))return 'SUV';if(/convertible|coupe|sedan|hatchback|wagon/.test(value))return '轿车';return '';}
function nhtsaFuel(fuel){const value=String(fuel||'').toLowerCase();if(/electric/.test(value)&&/gas|hybrid|plug/.test(value))return '混动';if(/electric/.test(value))return '纯电';if(/diesel/.test(value))return '柴油';if(/gasoline|gas\b|flexible/.test(value))return '汽油';return '';}
function nhtsaTransmission(value){const text=String(value||'').toLowerCase();if(/automatic|cvt/.test(text))return '自动挡';if(/manual/.test(text))return '手动挡';return '';}
function setAutoField(id,value,{onlyEmpty=false}={}){const field=document.getElementById(id);if(!field||!value||(onlyEmpty&&field.value.trim()))return;field.value=value;}
async function decodeVin(){const vin=String(document.getElementById('autoVin')?.value||'').trim().toUpperCase();if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin)){alert('请先填写完整且有效的 17 位 VIN。VIN 不包含 I、O、Q。');return;}const control=document.getElementById('vinDecodeControl'),button=control?.querySelector('button');if(button){button.disabled=true;button.textContent='正在解析…';}try{const response=await fetch(`/api/vin/${encodeURIComponent(vin)}`,{headers:{Accept:'application/json'}});const payload=await response.json();const data=payload?.data||null;if(!response.ok||!data)throw new Error(payload?.error||'decode_failed');const make=nhtsaValue(data,'Make'),model=nhtsaValue(data,'Model'),year=nhtsaValue(data,'ModelYear'),type=nhtsaVehicleType(nhtsaValue(data,'BodyClass')),fuel=nhtsaFuel(nhtsaValue(data,'FuelTypePrimary')),transmission=nhtsaTransmission(nhtsaValue(data,'TransmissionStyle'));setAutoField('autoMake',make);setAutoField('autoModel',model);setAutoField('autoYear',year);setAutoField('autoType',type);setAutoField('autoFuel',fuel);setAutoField('autoTransmission',transmission);setAutoField('autoDrive',nhtsaValue(data,'DriveType'),{onlyEmpty:true});setAutoField('autoTitle',[year,make,model].filter(Boolean).join(' '),{onlyEmpty:true});const fields=['autoMake','autoModel','autoYear','autoType','autoFuel','autoTransmission'];const count=fields.filter(id=>document.getElementById(id)?.value.trim()).length;if(control)control.querySelector('small').textContent=`已填入 ${count} 项基础资料，请核对后保存。`;}catch(error){if(control)control.querySelector('small').textContent='暂时无法解析该 VIN。请检查 VIN 或稍后重试。';}finally{if(button){button.disabled=false;button.textContent='重新解析 VIN';}}}
window.AutoAdmin={...window.AutoAdmin,decodeVin};
const renderAutoAdminWithSales=render;
function saleReceiptHtml(sale,listing){return `<section class="card" style="border-top:4px solid var(--sage);line-height:1.65"><span class="status sold">成交完成</span><h2 style="margin:10px 0 8px">${esc(listing?.title||'车辆成交收据')}</h2><p>收据编号：<b>${esc(sale.receipt_number)}</b></p><p>购车人：${esc(sale.customer_name||'')}</p><p>成交金额：<b>${money(sale.sale_amount)}</b></p><p>成交时间：${esc(new Date(sale.completed_at).toLocaleString('zh-CN'))}</p></section>`;}
function saleView(){const listing=S.saleListing;if(!listing){S.screen='home';return render();}const leads=S.leads.filter(lead=>String(lead.listing_id)===String(listing.id)&&lead.user_id);app.innerHTML=`${top('登记车辆成交')}<div class="wrap form"><section class="card"><b>${esc(listing.title)}</b><p style="margin:7px 0 0;color:#777;font-size:13px">登记后车辆会自动从公开库存隐藏，并生成成交收据。</p></section><label class="field">关联客户线索（可选）<select id="saleLead"><option value="">不关联已有线索</option>${leads.map(lead=>`<option value="${esc(lead.id)}">${esc(lead.customer_name)} · ${esc(lead.lead_type==='test_drive'?'试驾':'咨询')}</option>`).join('')}</select></label><label class="field">购车人姓名<input id="saleCustomerName" maxlength="80" placeholder="姓名（必填）"></label><label class="field">联系电话<input id="saleCustomerPhone" maxlength="40" inputmode="tel" placeholder="电话（可选）"></label><label class="field">成交金额（美元）<input id="saleAmount" inputmode="decimal" type="number" min="0" step="0.01" value="${esc(listing.price||'')}" placeholder="成交金额（必填）"></label><label class="field">成交备注（可选）<textarea id="saleNote" maxlength="1500" placeholder="例如：线下完成交车、包含保修等"></textarea></label><button class="btn primary" onclick="AutoAdmin.completeSale()">确认成交并生成收据</button></div>`;}
function salesView(){const sales=Array.isArray(S.sales)?S.sales:[];app.innerHTML=`${top('成交记录')}<div class="wrap"><div class="actions"><button class="btn" onclick="AutoAdmin.home()">返回车辆库存</button><button class="btn" onclick="AutoAdmin.refresh()">刷新记录</button></div>${sales.length?sales.map(sale=>saleReceiptHtml(sale,S.listings.find(item=>String(item.id)===String(sale.listing_id)))).join(''):'<div class="empty">还没有成交记录。</div>'}</div>`;}
async function completeSale(){const listing=S.saleListing,name=document.getElementById('saleCustomerName')?.value.trim(),phone=document.getElementById('saleCustomerPhone')?.value.trim(),amount=Number(document.getElementById('saleAmount')?.value),leadId=document.getElementById('saleLead')?.value||null,note=document.getElementById('saleNote')?.value.trim()||null;if(!listing||!name||!Number.isFinite(amount)||amount<0){alert('请填写购车人姓名和有效的成交金额。');return;}if(!confirm(`确认以 ${money(amount)} 成交「${listing.title}」吗？成交后将自动从公开库存隐藏。`))return;const response=await api('/rest/v1/rpc/merchant_auto_complete_sale',{method:'POST',body:JSON.stringify({p_listing_id:listing.id,p_lead_id:leadId,p_customer_name:name,p_customer_phone:phone||null,p_sale_amount:amount,p_sale_note:note})});const sale=await response.json();if(!response.ok){alert('成交登记失败。请确认车辆仍在售或已保留状态后重试。');return;}S.sales=[sale,...(S.sales||[])];S.screen='sales';await load();salesView();}
const editAutoWithSale=editView;
editView=function(){editAutoWithSale();const saveButton=document.querySelector('#autoManageApp .form .btn.primary');if(!saveButton||!S.edit?.id||!['available','reserved'].includes(S.edit.status)||document.getElementById('autoCompleteSaleButton'))return;saveButton.insertAdjacentHTML('beforebegin',`<button id="autoCompleteSaleButton" class="btn danger" style="width:100%;margin-top:14px" onclick="AutoAdmin.sale('${esc(S.edit.id)}')">登记成交</button>`);};
render=function(){if(S.screen==='sale')return saleView();if(S.screen==='sales')return salesView();renderAutoAdminWithSales();if(S.screen==='home'){const actions=document.querySelector('#autoManageApp .actions');if(actions&&!document.getElementById('autoSalesHistoryButton'))actions.insertAdjacentHTML('beforeend',`<button id="autoSalesHistoryButton" class="btn" onclick="AutoAdmin.sales()">成交记录${S.sales?.length?` (${S.sales.length})`:''}</button>`);}};
window.AutoAdmin={...window.AutoAdmin,sale(id){S.saleListing=S.listings.find(item=>String(item.id)===String(id))||S.edit;S.screen='sale';render();},completeSale,sales(){S.screen='sales';render();}};
const editAutoWithVehicleDetails=editView;
editView=function(){
  editAutoWithVehicleDetails();
  if(document.getElementById('autoVehicleReportUrl'))return;
  const description=document.getElementById('autoDescription');
  if(!description)return;
  const x=S.edit||{};
  const options=(values,current,empty='未提供')=>`<option value="">${empty}</option>${values.map(value=>`<option value="${esc(value)}" ${x[current]===value?'selected':''}>${esc(value)}</option>`).join('')}`;
  description.closest('.field')?.insertAdjacentHTML('beforebegin',`<section class="card" style="margin-top:16px"><b>公开车辆资料</b><p style="margin:7px 0 0;color:#777;font-size:12px;line-height:1.5">以下资料会显示在客户车辆详情页。完整 VIN 仍只限商家后台可见。</p><label class="field">车况报告链接 / PDF<input id="autoVehicleReportUrl" type="url" maxlength="1000" value="${esc(x.vehicle_report_url||'')}" placeholder="https://..."></label><div class="cols"><label class="field">事故记录<select id="autoAccidentHistory">${options(['无事故记录','有事故记录','记录待核验'],'accident_history')}</select></label><label class="field">保养记录<select id="autoServiceHistory">${options(['保养记录齐全','有部分保养记录','记录待核验'],'service_history')}</select></label></div><div class="cols"><label class="field">过户次数<input id="autoOwnerCount" type="number" min="0" max="99" inputmode="numeric" value="${esc(x.owner_count??'')}" placeholder="例如 1"></label><label class="field">产权状态<select id="autoTitleStatus">${options(['Clean Title','Salvage Title','Rebuilt Title','记录待核验'],'title_status')}</select></label></div><label class="field">保修状态<select id="autoWarrantyStatus">${options(['原厂保修有效','延长保修有效','无保修','保修待核验'],'warranty_status')}</select></label></section>`);
};
async function save(){
  const get=id=>document.getElementById(id)?.value.trim()||'';
  const payload={id:S.edit?.id,title:get('autoTitle'),make:get('autoMake'),model:get('autoModel'),year:get('autoYear'),price:get('autoPrice'),mileage:get('autoMileage'),vehicle_type:get('autoType'),fuel_type:get('autoFuel'),transmission:get('autoTransmission'),drivetrain:get('autoDrive'),exterior_color:get('autoColor'),vin:get('autoVin'),features:get('autoFeatures').split(/[，,]/).map(x=>x.trim()).filter(Boolean),photos:S.photos,description:get('autoDescription'),status:get('autoStatus'),is_certified:!!document.getElementById('autoCertified')?.checked,vehicle_report_url:get('autoVehicleReportUrl'),accident_history:get('autoAccidentHistory'),service_history:get('autoServiceHistory'),owner_count:get('autoOwnerCount'),warranty_status:get('autoWarrantyStatus'),title_status:get('autoTitleStatus')};
  if(!payload.title){alert('请填写车辆标题。');return;}
  if(payload.owner_count && (!/^\d{1,2}$/.test(payload.owner_count)||Number(payload.owner_count)>99)){alert('过户次数请填写 0 到 99 之间的整数。');return;}
  const r=await api('/rest/v1/rpc/merchant_auto_save_listing',{method:'POST',body:JSON.stringify({p_merchant_user_id:S.merchantId,p_listing:payload})});
  if(!r.ok){alert('保存失败，请确认已运行 v5.403 数据库更新后重试。');return;}
  S.screen='home';await load();
}
window.AutoAdmin={...window.AutoAdmin,save};
// Standalone management keeps the same durable bottom navigation as the main app.
function openMainTab(tab){
  const target=new URL('/',location.origin);
  target.searchParams.set('tab',tab);
  target.searchParams.set('app_v','5.412');
  if(new URLSearchParams(location.search).get('app_v')) target.searchParams.set('embedded_app','1');
  location.assign(target.toString());
}
function ensureMainNavigation(){
  document.documentElement.style.overflowX='hidden';
  document.body.style.overflowX='hidden';
  app.style.paddingBottom='calc(82px + env(safe-area-inset-bottom))';
  if(document.getElementById('autoManageMainNav')) return;
  document.body.insertAdjacentHTML('beforeend',`<nav id="autoManageMainNav" aria-label="主导航" style="position:fixed;z-index:30;left:0;right:0;bottom:0;height:calc(58px + env(safe-area-inset-bottom));padding:7px max(10px,env(safe-area-inset-right)) calc(7px + env(safe-area-inset-bottom)) max(10px,env(safe-area-inset-left));display:grid;grid-template-columns:repeat(5,1fr);gap:3px;background:rgba(255,255,255,.98);border-top:1px solid #e4e0d4;box-shadow:0 -4px 14px rgba(38,42,37,.06)"><button style="border:0;background:transparent;color:#c93c6d;font:800 11px inherit" onclick="AutoAdmin.mainTab('home')">首页</button><button style="border:0;background:transparent;color:#777a71;font:800 11px inherit" onclick="AutoAdmin.mainTab('week')">本周</button><button style="border:0;background:transparent;color:#777a71;font:800 11px inherit" onclick="AutoAdmin.mainTab('deals')">省钱</button><button style="border:0;background:transparent;color:#777a71;font:800 11px inherit" onclick="AutoAdmin.mainTab('message')">消息</button><button style="border:0;background:transparent;color:#777a71;font:800 11px inherit" onclick="AutoAdmin.mainTab('profile')">我</button></nav>`);
}
const loadBeforeLeadOperations=load;
load=async function(){
  await loadBeforeLeadOperations();
  if(!S.merchantId)return;
  try{
    const response=await api('/rest/v1/rpc/merchant_auto_manager_list',{method:'POST',body:JSON.stringify({p_merchant_user_id:S.merchantId})});
    const data=await response.json();
    if(!response.ok)throw new Error(data.message||'lead_operations_load_failed');
    S.team=Array.isArray(data.team)?data.team:[];
    S.activities=Array.isArray(data.activities)?data.activities:[];
    render();
  }catch(error){
    S.team=[];
    S.activities=[];
  }
};
function leadLocalValue(value){
  if(!value)return '';
  const date=new Date(value),offset=date.getTimezoneOffset();
  return new Date(date.getTime()-offset*60000).toISOString().slice(0,16);
}
function leadFollowUpLabel(value){
  return value?new Date(value).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未设置';
}
function leadActivityLabel(type){return ({note:'跟进备注',assignment:'分配负责人',follow_up:'设置回访',status:'更新状态'})[type]||'线索更新';}
const leadViewBeforeLeadOperations=leadView;
leadView=function(){
  leadViewBeforeLeadOperations();
  const lead=S.lead,target=document.querySelector('#autoManageApp .wrap');
  if(!lead||!target||document.getElementById('autoLeadOperations'))return;
  const rows=(S.activities||[]).filter(row=>String(row.lead_id)===String(lead.id)).slice(0,12);
  target.insertAdjacentHTML('beforeend',`<section id="autoLeadOperations" class="card lead-operations"><div class="section-title"><h2>销售跟进</h2><span>仅商家团队可见</span></div><label class="field">负责人<select id="leadAssignedTo"><option value="">未分配</option>${(S.team||[]).map(member=>`<option value="${esc(member.user_id)}" ${String(member.user_id)===String(lead.assigned_to)?'selected':''}>${esc(member.name)}${member.role?` · ${esc(member.role)}`:''}</option>`).join('')}</select></label><label class="field">下次回访<input id="leadFollowUpAt" type="datetime-local" value="${leadLocalValue(lead.follow_up_at)}"></label><label class="field">本次跟进记录<textarea id="leadActivityNote" maxlength="1000" placeholder="例如：已电话沟通，客户周末到店试驾"></textarea></label><button class="btn primary" style="width:100%;margin-top:15px" onclick="AutoAdmin.saveLeadFollowUp()">保存销售跟进</button>${rows.length?`<div class="activity-list"><b>最近跟进</b>${rows.map(row=>`<div class="activity-item"><strong>${esc(leadActivityLabel(row.activity_type))}</strong><span>${esc(row.actor_name||'商家团队')} · ${esc(new Date(row.created_at).toLocaleString('zh-CN'))}</span>${row.note?`<p>${esc(row.note)}</p>`:''}${row.next_follow_up_at?`<small>下次回访：${esc(leadFollowUpLabel(row.next_follow_up_at))}</small>`:''}</div>`).join('')}</div>`:'<p class="activity-empty">还没有销售跟进记录。</p>'}</section>`);
};
async function saveLeadFollowUp(){
  const lead=S.lead;
  if(!lead)return;
  const assigned=document.getElementById('leadAssignedTo')?.value||null;
  const followUp=document.getElementById('leadFollowUpAt')?.value||null;
  const note=document.getElementById('leadActivityNote')?.value.trim()||null;
  const status=document.getElementById('leadStatus')?.value||lead.status;
  const response=await api('/rest/v1/rpc/merchant_auto_update_lead_follow_up',{method:'POST',body:JSON.stringify({p_lead_id:lead.id,p_status:status,p_assigned_to:assigned,p_set_assignee:true,p_follow_up_at:followUp?new Date(followUp).toISOString():null,p_set_follow_up:true,p_note:note})});
  if(!response.ok){alert('保存跟进失败，请确认已运行 v5.409 数据库更新后重试。');return;}
  await load();
  S.lead=S.leads.find(item=>String(item.id)===String(lead.id))||null;
  S.screen=S.lead?'lead':'leads';
  render();
}
window.AutoAdmin={...window.AutoAdmin,saveLeadFollowUp};
function privateNumber(id){const value=document.getElementById(id)?.value.trim()||'';return value===''?'':value;}
const editViewBeforeProfit=editView;
editView=function(){
  editViewBeforeProfit();
  if(document.getElementById('autoPurchaseSource'))return;
  const description=document.getElementById('autoDescription');
  if(!description)return;
  const listing=S.edit||{};
  description.closest('.field')?.insertAdjacentHTML('beforebegin',`<section class="card auto-private-data"><b>商家经营数据</b><p>仅商家后台可见，不会公开给顾客。</p><label class="field">车辆来源<select id="autoPurchaseSource">${['','置换收购','个人收购','拍卖采购','批发采购','寄售','其他'].map(value=>`<option value="${esc(value)}" ${listing.purchase_source===value?'selected':''}>${esc(value||'未填写')}</option>`).join('')}</select></label><div class="cols"><label class="field">进货价（美元）<input id="autoAcquisitionPrice" type="number" min="0" step="0.01" inputmode="decimal" value="${esc(listing.acquisition_price??'')}"></label><label class="field">整备成本（美元）<input id="autoReconditioningCost" type="number" min="0" step="0.01" inputmode="decimal" value="${esc(listing.reconditioning_cost??'')}"></label></div><label class="field">内部成本备注<textarea id="autoCostNote" maxlength="1000" placeholder="例如：轮胎、保养、清洁、维修等">${esc(listing.cost_note||'')}</textarea></label></section>`);
};
async function save(){
  const get=id=>document.getElementById(id)?.value.trim()||'';
  const payload={id:S.edit?.id,title:get('autoTitle'),make:get('autoMake'),model:get('autoModel'),year:get('autoYear'),price:get('autoPrice'),mileage:get('autoMileage'),vehicle_type:get('autoType'),fuel_type:get('autoFuel'),transmission:get('autoTransmission'),drivetrain:get('autoDrive'),exterior_color:get('autoColor'),vin:get('autoVin'),features:get('autoFeatures').split(/[，,]/).map(item=>item.trim()).filter(Boolean),photos:S.photos,description:get('autoDescription'),status:get('autoStatus'),is_certified:!!document.getElementById('autoCertified')?.checked,vehicle_report_url:get('autoVehicleReportUrl'),accident_history:get('autoAccidentHistory'),service_history:get('autoServiceHistory'),owner_count:get('autoOwnerCount'),warranty_status:get('autoWarrantyStatus'),title_status:get('autoTitleStatus'),purchase_source:get('autoPurchaseSource'),acquisition_price:privateNumber('autoAcquisitionPrice'),reconditioning_cost:privateNumber('autoReconditioningCost'),cost_note:get('autoCostNote')};
  if(!payload.title){alert('请填写车辆标题。');return;}
  if(payload.owner_count&&(!/^\d{1,2}$/.test(payload.owner_count)||Number(payload.owner_count)>99)){alert('过户次数请填写 0 到 99 之间的整数。');return;}
  for(const field of ['acquisition_price','reconditioning_cost'])if(payload[field]!==''&&(!Number.isFinite(Number(payload[field]))||Number(payload[field])<0)){alert('经营成本请输入大于或等于 0 的金额。');return;}
  const response=await api('/rest/v1/rpc/merchant_auto_save_listing',{method:'POST',body:JSON.stringify({p_merchant_user_id:S.merchantId,p_listing:payload})});
  if(!response.ok){alert('保存失败，请确认已运行 v5.410 数据库更新后重试。');return;}
  S.screen='home';await load();
}
function listingDays(listing){const from=new Date(listing.created_at||listing.updated_at||Date.now()).getTime();return Math.max(0,Math.floor((Date.now()-from)/86400000));}
function autoProfit(listing,saleAmount){const revenue=Number(saleAmount??listing?.price??0),cost=Number(listing?.acquisition_price||0)+Number(listing?.reconditioning_cost||0);return revenue-cost;}
function autoOperationsView(){
  const listings=S.listings||[],sales=S.sales||[],available=listings.filter(item=>['available','reserved'].includes(item.status)),sold=sales.map(sale=>({...sale,listing:listings.find(item=>String(item.id)===String(sale.listing_id))})),estimated=available.reduce((sum,item)=>sum+autoProfit(item),0),realized=sold.reduce((sum,sale)=>sum+autoProfit(sale.listing,sale.sale_amount),0),avgDays=available.length?Math.round(available.reduce((sum,item)=>sum+listingDays(item),0)/available.length):0,stages=[['新线索','new'],['已联系','contacted'],['已安排','scheduled'],['已报价','quoted'],['成交 / 完成','closed']];
  app.innerHTML=`${top('经营统计')}<div class="wrap"><div class="summary auto-ops-summary"><div><b>${money(estimated)}</b><span>在售预计毛利</span></div><div><b>${money(realized)}</b><span>已成交毛利</span></div><div><b>${avgDays}</b><span>平均库存天数</span></div></div><div class="actions"><button class="btn" onclick="AutoAdmin.home()">返回车辆库存</button><button class="btn" onclick="AutoAdmin.refresh()">刷新数据</button></div><section><div class="section-title"><h2>销售漏斗</h2><span>客户线索状态</span></div><div class="card funnel-list">${stages.map(([label,status])=>`<div><span>${label}</span><b>${(S.leads||[]).filter(lead=>lead.status===status).length}</b></div>`).join('')}</div></section><section><div class="section-title"><h2>库存概览</h2><span>仅商家可见</span></div>${available.length?available.sort((a,b)=>listingDays(b)-listingDays(a)).map(item=>`<article class="card auto-profit-row"><div><b>${esc(item.title)}</b><span>${esc(item.purchase_source||'未填写车辆来源')} · 库存 ${listingDays(item)} 天</span><small>进货 ${money(item.acquisition_price)} + 整备 ${money(item.reconditioning_cost)}</small></div><strong>${money(autoProfit(item))}</strong></article>`).join(''):'<div class="empty">暂无在售库存。</div>'}</section></div>`;
}
const renderBeforeProfit=render;
render=function(){if(S.screen==='operations')return autoOperationsView();renderBeforeProfit();if(S.screen==='home'){const actions=document.querySelector('#autoManageApp .actions');if(actions&&!document.getElementById('autoOperationsButton'))actions.insertAdjacentHTML('beforeend','<button id="autoOperationsButton" class="btn" onclick="AutoAdmin.operations()">经营统计</button>');}};
window.AutoAdmin={...window.AutoAdmin,save,operations(){S.screen='operations';render();}};
/* v5.412: inventory status changes are deliberate, logged, and visible to affected customers. */
const editViewBeforeStatusWorkflow=editView;
editView=function(){
  editViewBeforeStatusWorkflow();
  if(!S.edit?.id||document.getElementById('autoStatusWorkflow'))return;
  const status=document.getElementById('autoStatus');
  if(!status)return;
  status.closest('.field')?.insertAdjacentHTML('afterend',`<section id="autoStatusWorkflow" class="card auto-status-workflow"><b>库存状态与客户说明</b><p>预留、已售或下架时，可填写说明；收藏或预约过该车的客户会在“我的提醒”看到状态变化。</p><label class="field">状态说明（可选）<textarea id="autoStatusNote" maxlength="1000" placeholder="例如：已为客户保留至 7 月 25 日，或车辆已完成交付">${esc(S.edit.status_note||'')}</textarea></label><button class="btn" type="button" onclick="AutoAdmin.changeStatus()">仅更新库存状态</button></section>`);
};
async function changeStatus(){
  const listing=S.edit,status=document.getElementById('autoStatus')?.value,note=document.getElementById('autoStatusNote')?.value.trim()||null;
  if(!listing?.id||!status)return;
  if(status==='sold'&&!confirm('标记为已售后，此车辆不会再出现在公开库存中。是否继续？'))return;
  const response=await api('/rest/v1/rpc/merchant_auto_change_listing_status',{method:'POST',body:JSON.stringify({p_listing_id:listing.id,p_status:status,p_note:note})});
  if(!response.ok){let message='';try{message=(await response.json())?.message||''}catch(error){}alert(message==='sold_listing_locked'?'已售车辆不能恢复为在售，请新增一条库存记录。':'状态更新失败，请确认已运行 v5.412 数据库更新后重试。');return;}
  S.screen='home';
  await load();
}
window.AutoAdmin={...window.AutoAdmin,changeStatus};
window.AutoAdmin={...window.AutoAdmin,mainTab:openMainTab};
ensureMainNavigation();
load();
})();
