-- 乐生活 v5.600：账户设置与常用收货地址

create table if not exists public.user_account_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.user_account_settings enable row level security;

drop policy if exists "Users manage own account settings" on public.user_account_settings;
create policy "Users manage own account settings"
  on public.user_account_settings
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update on public.user_account_settings to authenticated;

create table if not exists public.user_delivery_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '常用地址',
  recipient_name text not null,
  phone text not null,
  address_line1 text not null,
  address_line2 text,
  city text,
  state_region text,
  postal_code text,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists user_delivery_addresses_user_updated_idx
  on public.user_delivery_addresses (user_id, updated_at desc);

alter table public.user_delivery_addresses enable row level security;

drop policy if exists "Users manage own delivery addresses" on public.user_delivery_addresses;
create policy "Users manage own delivery addresses"
  on public.user_delivery_addresses
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update, delete on public.user_delivery_addresses to authenticated;
grant usage, select on sequence public.user_delivery_addresses_id_seq to authenticated;
