-- 乐生活 5.210：商家餐桌扫码点餐
-- 顾客必须登录后才能提交订单；价格和商品快照均由数据库从商家菜单重新核对。

create table if not exists public.merchant_order_tables (
  id bigint generated by default as identity primary key,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  table_code text not null,
  table_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint merchant_order_tables_code_unique unique (merchant_user_id, table_code),
  constraint merchant_order_tables_code_format check (table_code ~ '^[a-z0-9-]{3,48}$')
);

create table if not exists public.merchant_orders (
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique default ('LSO-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8))),
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  table_id bigint not null references public.merchant_order_tables(id) on delete restrict,
  table_name text not null,
  user_id uuid not null references auth.users(id) on delete restrict,
  user_name text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'preparing', 'served', 'completed', 'cancelled')),
  note text not null default '',
  subtotal numeric(10,2) not null default 0,
  item_count integer not null default 0,
  addition_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  confirmed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz
);

create table if not exists public.merchant_order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.merchant_orders(id) on delete cascade,
  batch_no integer not null default 1,
  product_id text not null,
  product_name text not null,
  product_image text,
  product_categories jsonb not null default '[]'::jsonb,
  unit_price numeric(10,2) not null default 0,
  price_label text not null default '',
  quantity integer not null check (quantity between 1 and 99),
  created_at timestamptz not null default now()
);

create index if not exists merchant_order_tables_merchant_active_idx on public.merchant_order_tables (merchant_user_id, is_active, table_name);
create index if not exists merchant_orders_merchant_status_updated_idx on public.merchant_orders (merchant_user_id, status, updated_at desc);
create index if not exists merchant_orders_user_updated_idx on public.merchant_orders (user_id, updated_at desc);
create index if not exists merchant_order_items_order_batch_idx on public.merchant_order_items (order_id, batch_no, created_at);

alter table public.merchant_order_tables enable row level security;
alter table public.merchant_orders enable row level security;
alter table public.merchant_order_items enable row level security;

create or replace function public.merchant_order_can_manage(p_merchant_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select (select auth.uid()) = p_merchant_user_id
    or exists (
      select 1
      from public.merchant_team_members tm
      where tm.merchant_user_id = p_merchant_user_id
        and tm.member_user_id = (select auth.uid())
        and tm.status = 'active'
        and tm.role in ('operator', 'clerk')
    );
$$;

revoke all on function public.merchant_order_can_manage(uuid) from public;
grant execute on function public.merchant_order_can_manage(uuid) to authenticated;

drop policy if exists "Active tables visible to signed in customers" on public.merchant_order_tables;
create policy "Active tables visible to signed in customers"
on public.merchant_order_tables for select to authenticated
using (is_active or (select public.merchant_order_can_manage(merchant_user_id)));

drop policy if exists "Merchant team manages dining tables" on public.merchant_order_tables;
create policy "Merchant team manages dining tables"
on public.merchant_order_tables for all to authenticated
using ((select public.merchant_order_can_manage(merchant_user_id)))
with check ((select public.merchant_order_can_manage(merchant_user_id)));

drop policy if exists "Customers and merchant team read dining orders" on public.merchant_orders;
create policy "Customers and merchant team read dining orders"
on public.merchant_orders for select to authenticated
using (user_id = (select auth.uid()) or (select public.merchant_order_can_manage(merchant_user_id)));

drop policy if exists "Customers and merchant team read dining order items" on public.merchant_order_items;
create policy "Customers and merchant team read dining order items"
on public.merchant_order_items for select to authenticated
using (
  exists (
    select 1 from public.merchant_orders o
    where o.id = merchant_order_items.order_id
      and (o.user_id = (select auth.uid()) or (select public.merchant_order_can_manage(o.merchant_user_id)))
  )
);

create or replace function public.merchant_order_create(
  p_merchant_user_id uuid,
  p_table_code text,
  p_items jsonb,
  p_note text default '',
  p_existing_order_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_table public.merchant_order_tables%rowtype;
  v_order public.merchant_orders%rowtype;
  v_products jsonb;
  v_item jsonb;
  v_product jsonb;
  v_product_id text;
  v_quantity integer;
  v_unit_price numeric(10,2);
  v_price_label text;
  v_subtotal numeric(10,2) := 0;
  v_count integer := 0;
  v_batch integer := 1;
  v_user_name text;
begin
  if v_user_id is null then
    raise exception 'merchant_order_login_required';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'merchant_order_empty';
  end if;

  select * into v_table
  from public.merchant_order_tables
  where merchant_user_id = p_merchant_user_id
    and table_code = lower(trim(p_table_code))
    and is_active = true;
  if not found then
    raise exception 'merchant_order_table_not_found';
  end if;

  select products into v_products
  from public.merchants
  where user_id = p_merchant_user_id and verified = true;
  if not found then
    raise exception 'merchant_order_merchant_not_found';
  end if;

  if p_existing_order_id is not null then
    select * into v_order from public.merchant_orders
    where id = p_existing_order_id and user_id = v_user_id and merchant_user_id = p_merchant_user_id and table_id = v_table.id
    for update;
    if not found or v_order.status in ('completed', 'cancelled') then
      raise exception 'merchant_order_not_addable';
    end if;
    select coalesce(max(batch_no), 0) + 1 into v_batch from public.merchant_order_items where order_id = v_order.id;
  else
    select coalesce(name, '乐生活用户') into v_user_name
    from public.profiles where user_id = v_user_id limit 1;
    insert into public.merchant_orders (merchant_user_id, table_id, table_name, user_id, user_name, note)
    values (p_merchant_user_id, v_table.id, v_table.table_name, v_user_id, v_user_name, left(coalesce(trim(p_note), ''), 240))
    returning * into v_order;
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := coalesce(v_item->>'product_id', v_item->>'id', '');
    v_quantity := greatest(1, least(99, coalesce(nullif(v_item->>'quantity', '')::integer, 1)));
    select value into v_product
    from jsonb_array_elements(coalesce(v_products, '[]'::jsonb))
    where value->>'id' = v_product_id
      and coalesce((value->>'active')::boolean, true) = true
      and coalesce((value->>'orderable')::boolean, true) = true
    limit 1;
    if v_product is null then
      raise exception 'merchant_order_product_unavailable:%', v_product_id;
    end if;
    v_price_label := coalesce(v_product->>'price', '');
    v_unit_price := coalesce(nullif(substring(v_price_label from '([0-9]+([.][0-9]{1,2})?)'), '')::numeric, 0);
    insert into public.merchant_order_items (order_id, batch_no, product_id, product_name, product_image, product_categories, unit_price, price_label, quantity)
    values (
      v_order.id, v_batch, v_product_id, coalesce(v_product->>'name', '未命名商品'), nullif(v_product->>'image', ''),
      coalesce(v_product->'categories', jsonb_build_array(coalesce(v_product->>'category', '其他'))),
      v_unit_price, v_price_label, v_quantity
    );
    v_subtotal := v_subtotal + v_unit_price * v_quantity;
    v_count := v_count + v_quantity;
  end loop;

  update public.merchant_orders
  set subtotal = subtotal + v_subtotal,
      item_count = item_count + v_count,
      addition_count = addition_count + case when p_existing_order_id is null then 0 else 1 end,
      note = case when p_existing_order_id is null then left(coalesce(trim(p_note), ''), 240) else note end,
      updated_at = now()
  where id = v_order.id;

  return v_order.id;
end;
$$;

create or replace function public.merchant_order_set_status(p_order_id uuid, p_status text)
returns public.merchant_orders
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_order public.merchant_orders%rowtype;
begin
  if p_status not in ('pending', 'confirmed', 'preparing', 'served', 'completed', 'cancelled') then
    raise exception 'merchant_order_invalid_status';
  end if;
  select * into v_order from public.merchant_orders where id = p_order_id for update;
  if not found or not public.merchant_order_can_manage(v_order.merchant_user_id) then
    raise exception 'merchant_order_not_allowed';
  end if;
  update public.merchant_orders
  set status = p_status,
      updated_at = now(),
      confirmed_at = case when p_status = 'confirmed' then now() else confirmed_at end,
      completed_at = case when p_status = 'completed' then now() else completed_at end,
      cancelled_at = case when p_status = 'cancelled' then now() else cancelled_at end
  where id = p_order_id
  returning * into v_order;
  return v_order;
end;
$$;

revoke all on function public.merchant_order_create(uuid, text, jsonb, text, uuid) from public;
revoke all on function public.merchant_order_set_status(uuid, text) from public;
grant execute on function public.merchant_order_create(uuid, text, jsonb, text, uuid) to authenticated;
grant execute on function public.merchant_order_set_status(uuid, text) to authenticated;

grant select, insert, update, delete on public.merchant_order_tables to authenticated;
grant select on public.merchant_orders, public.merchant_order_items to authenticated;
grant usage, select on sequence public.merchant_order_tables_id_seq, public.merchant_order_items_id_seq to authenticated;
