-- 乐生活 v5.424：统一活动日历
-- 已有“玩乐”活动笔记不受影响；本表供未来票务、报名和商家独立活动写入。

create table if not exists public.activity_calendar_items (
  id bigint generated by default as identity primary key,
  source_type text not null check (source_type in ('ticket', 'registration', 'merchant_event')),
  source_id text not null,
  source_url text,
  merchant_user_id uuid references auth.users(id) on delete set null,
  title text not null check (char_length(title) between 1 and 120),
  summary text,
  cover_image text,
  start_date date not null,
  end_date date not null,
  all_day boolean not null default true,
  location text,
  capacity integer check (capacity is null or capacity >= 0),
  registered integer not null default 0 check (registered >= 0),
  registration_enabled boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'published', 'cancelled', 'ended')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_calendar_dates_valid check (end_date >= start_date),
  constraint activity_calendar_source_unique unique (source_type, source_id)
);

create index if not exists activity_calendar_items_published_dates_idx
  on public.activity_calendar_items (status, start_date, end_date);

create index if not exists activity_calendar_items_merchant_idx
  on public.activity_calendar_items (merchant_user_id, created_at desc);

alter table public.activity_calendar_items enable row level security;

drop policy if exists "Public can read published calendar activities" on public.activity_calendar_items;
create policy "Public can read published calendar activities"
on public.activity_calendar_items
for select
to anon, authenticated
using (status = 'published' or merchant_user_id = (select auth.uid()));

drop policy if exists "Merchants can create own calendar activities" on public.activity_calendar_items;
create policy "Merchants can create own calendar activities"
on public.activity_calendar_items
for insert
to authenticated
with check (merchant_user_id = (select auth.uid()));

drop policy if exists "Merchants can update own calendar activities" on public.activity_calendar_items;
create policy "Merchants can update own calendar activities"
on public.activity_calendar_items
for update
to authenticated
using (merchant_user_id = (select auth.uid()))
with check (merchant_user_id = (select auth.uid()));

drop policy if exists "Merchants can delete own calendar activities" on public.activity_calendar_items;
create policy "Merchants can delete own calendar activities"
on public.activity_calendar_items
for delete
to authenticated
using (merchant_user_id = (select auth.uid()));

grant select on public.activity_calendar_items to anon, authenticated;
grant insert, update, delete on public.activity_calendar_items to authenticated;
grant usage, select on sequence public.activity_calendar_items_id_seq to authenticated;
