-- 乐生活 v5.139：社区内容举报与管理员处理

create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reported_user_id uuid references auth.users(id) on delete set null,
  post_id bigint references public.posts(id) on delete set null,
  reason text not null check (reason in ('spam','misinformation','harassment','privacy','illegal','other')),
  detail text,
  status text not null default 'pending' check (status in ('pending','reviewing','resolved','dismissed')),
  handled_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists content_reports_status_created_at_idx
  on public.content_reports (status, created_at desc);
create index if not exists content_reports_reporter_created_at_idx
  on public.content_reports (reporter_user_id, created_at desc);
create index if not exists content_reports_post_id_idx
  on public.content_reports (post_id);

grant select, insert, update on public.content_reports to authenticated;
grant usage, select on sequence public.content_reports_id_seq to authenticated;

alter table public.content_reports enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'content_reports' and policyname = 'content_reports reporters insert own') then
    create policy "content_reports reporters insert own"
    on public.content_reports for insert to authenticated
    with check ((select auth.uid()) is not null and reporter_user_id = (select auth.uid()));
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'content_reports' and policyname = 'content_reports reporters or admins read') then
    create policy "content_reports reporters or admins read"
    on public.content_reports for select to authenticated
    using (
      reporter_user_id = (select auth.uid())
      or exists (
        select 1 from public.deal_admins da
        where da.user_id = (select auth.uid())
      )
    );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'content_reports' and policyname = 'content_reports admins update') then
    create policy "content_reports admins update"
    on public.content_reports for update to authenticated
    using (
      exists (
        select 1 from public.deal_admins da
        where da.user_id = (select auth.uid())
      )
    )
    with check (
      exists (
        select 1 from public.deal_admins da
        where da.user_id = (select auth.uid())
      )
    );
  end if;
end $$;
