-- 乐生活 v5.599：跨设备购物车
-- 购物车只保存用户尚未结算的商品快照；真实价格、库存和优惠会在提交订单时再次由商家侧核对。

create table if not exists public.user_cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  source_type text not null check (source_type in ('retail', 'restaurant')),
  product_key text not null,
  quantity integer not null check (quantity between 1 and 99),
  item_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, merchant_user_id, source_type, product_key)
);

create index if not exists user_cart_items_user_updated_idx
  on public.user_cart_items (user_id, updated_at desc);

alter table public.user_cart_items enable row level security;
grant select, insert, update, delete on public.user_cart_items to authenticated;

drop policy if exists "cart items are readable by owner" on public.user_cart_items;
create policy "cart items are readable by owner"
  on public.user_cart_items for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "cart items are insertable by owner" on public.user_cart_items;
create policy "cart items are insertable by owner"
  on public.user_cart_items for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "cart items are editable by owner" on public.user_cart_items;
create policy "cart items are editable by owner"
  on public.user_cart_items for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "cart items are removable by owner" on public.user_cart_items;
create policy "cart items are removable by owner"
  on public.user_cart_items for delete to authenticated
  using (auth.uid() = user_id);
