-- 乐生活 v5.584：交易安全基础
-- 覆盖个人小店与认证商家零售商品：发布限制、举报冻结、订单留痕、争议与商家协议。

create table if not exists public.marketplace_listing_controls (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  source_type text not null check (source_type in ('personal_shop_product','merchant_product')),
  source_id text not null check (char_length(trim(source_id)) between 1 and 120),
  status text not null default 'active' check (status in ('active','frozen','removed')),
  reason_code text,
  moderator_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_user_id, source_type, source_id)
);

create table if not exists public.marketplace_listing_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  source_type text not null check (source_type in ('personal_shop_product','merchant_product')),
  source_id text not null check (char_length(trim(source_id)) between 1 and 120),
  listing_title text not null default '' check (char_length(listing_title) <= 160),
  reason text not null check (reason in ('prohibited','counterfeit','fraud','unsafe','stolen','privacy','other')),
  detail text not null default '' check (char_length(detail) <= 800),
  status text not null default 'pending' check (status in ('pending','reviewing','resolved','dismissed')),
  handled_by uuid references auth.users(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  unique (reporter_user_id, source_type, source_id)
);

create table if not exists public.marketplace_order_events (
  id bigint generated by default as identity primary key,
  order_type text not null check (order_type in ('merchant_retail')),
  order_id uuid not null,
  order_code text not null default '',
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('created','status_changed','dispute_opened','dispute_updated','dispute_closed','note')),
  previous_status text,
  next_status text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.marketplace_order_disputes (
  id uuid primary key default gen_random_uuid(),
  order_type text not null check (order_type in ('merchant_retail')),
  order_id uuid not null,
  opened_by uuid not null references auth.users(id) on delete cascade,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('not_received','not_as_described','damaged','merchant_cancelled','other')),
  detail text not null default '' check (char_length(detail) <= 1200),
  status text not null default 'open' check (status in ('open','under_review','resolved','closed')),
  resolution text,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_type, order_id)
);

create table if not exists public.merchant_platform_agreements (
  id uuid primary key default gen_random_uuid(),
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  agreement_key text not null default 'marketplace_terms',
  agreement_version text not null,
  accepted_at timestamptz not null default now(),
  accepted_ip text,
  unique (merchant_user_id, agreement_key, agreement_version)
);

create index if not exists marketplace_listing_controls_lookup_idx on public.marketplace_listing_controls(owner_user_id, source_type, source_id, status);
create index if not exists marketplace_listing_reports_queue_idx on public.marketplace_listing_reports(status, created_at desc);
create index if not exists marketplace_listing_reports_target_idx on public.marketplace_listing_reports(owner_user_id, source_type, source_id, created_at desc);
create index if not exists marketplace_order_events_order_idx on public.marketplace_order_events(order_type, order_id, created_at asc);
create index if not exists marketplace_order_disputes_order_idx on public.marketplace_order_disputes(order_type, order_id, created_at desc);

alter table public.merchant_retail_orders add column if not exists dispute_status text not null default 'none' check (dispute_status in ('none','open','under_review','resolved','closed'));
alter table public.merchant_retail_orders add column if not exists marketplace_terms_version text;
alter table public.merchant_retail_orders add column if not exists marketplace_terms_accepted_at timestamptz;

alter table public.marketplace_listing_controls enable row level security;
alter table public.marketplace_listing_reports enable row level security;
alter table public.marketplace_order_events enable row level security;
alter table public.marketplace_order_disputes enable row level security;
alter table public.merchant_platform_agreements enable row level security;

revoke all on public.marketplace_listing_controls, public.marketplace_listing_reports, public.marketplace_order_events, public.marketplace_order_disputes, public.merchant_platform_agreements from anon, authenticated;
revoke all on sequence public.marketplace_order_events_id_seq from anon, authenticated;

create or replace function public.marketplace_listing_violation(p_text text)
returns text
language plpgsql immutable set search_path = public as $$
declare v text := lower(coalesce(p_text,''));
begin
  if v ~ '(枪支|手枪|步枪|弹药|子弹|消音器|firearm|handgun|rifle|ammunition|suppressor)' then return 'weapons'; end if;
  if v ~ '(毒品|大麻|可卡因|海洛因|处方药|迷幻|cocaine|heroin|fentanyl|prescription drug|marijuana)' then return 'controlled_substances'; end if;
  if v ~ '(电子烟油|烟弹|vape juice|nicotine liquid|烟草制品)' then return 'regulated_tobacco'; end if;
  if v ~ '(假货|高仿|复刻|盗版|仿冒|counterfeit|replica|knockoff|pirated)' then return 'counterfeit'; end if;
  if v ~ '(赃物|偷来|盗窃|stolen goods|stolen)' then return 'stolen_goods'; end if;
  if v ~ '(成人服务|裸照|色情|色情服务|escort|pornographic|adult service)' then return 'adult_content'; end if;
  return null;
end;
$$;

create or replace function public.marketplace_guard_personal_listing()
returns trigger language plpgsql set search_path = public as $$
declare v_reason text;
begin
  v_reason := public.marketplace_listing_violation(concat_ws(' ', new.title, new.description, new.category));
  if v_reason is not null then raise exception 'listing_restricted:%', v_reason using errcode = '22023'; end if;
  return new;
end;
$$;

drop trigger if exists marketplace_guard_personal_listing on public.personal_shop_products;
create trigger marketplace_guard_personal_listing before insert or update of title, description, category
on public.personal_shop_products for each row execute function public.marketplace_guard_personal_listing();

create or replace function public.marketplace_guard_merchant_products()
returns trigger language plpgsql set search_path = public as $$
declare v_item jsonb; v_reason text;
begin
  for v_item in select value from jsonb_array_elements(coalesce(new.products, '[]'::jsonb)) loop
    v_reason := public.marketplace_listing_violation(concat_ws(' ', v_item->>'name', v_item->>'title', v_item->>'description', v_item->>'category', v_item->>'categories'));
    if v_reason is not null then raise exception 'listing_restricted:%', v_reason using errcode = '22023'; end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists marketplace_guard_merchant_products on public.merchants;
create trigger marketplace_guard_merchant_products before insert or update of products
on public.merchants for each row execute function public.marketplace_guard_merchant_products();

create or replace function public.marketplace_public_listing_controls(p_owner_user_id uuid, p_source_type text)
returns table(source_id text, status text)
language sql stable security definer set search_path = public as $$
  select source_id, status
  from public.marketplace_listing_controls
  where owner_user_id = p_owner_user_id
    and source_type = p_source_type
    and status in ('frozen','removed');
$$;

create or replace function public.marketplace_report_listing(
  p_owner_user_id uuid,
  p_source_type text,
  p_source_id text,
  p_listing_title text,
  p_reason text,
  p_detail text default ''
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_report public.marketplace_listing_reports%rowtype;
begin
  if auth.uid() is null then raise exception 'login_required'; end if;
  if p_owner_user_id is null or p_owner_user_id = auth.uid() then raise exception 'invalid_report_target'; end if;
  if p_source_type not in ('personal_shop_product','merchant_product') then raise exception 'invalid_report_target'; end if;
  if char_length(trim(coalesce(p_source_id,''))) = 0 then raise exception 'invalid_report_target'; end if;
  if p_reason not in ('prohibited','counterfeit','fraud','unsafe','stolen','privacy','other') then raise exception 'invalid_report_reason'; end if;
  insert into public.marketplace_listing_reports(reporter_user_id,owner_user_id,source_type,source_id,listing_title,reason,detail)
  values(auth.uid(),p_owner_user_id,p_source_type,trim(p_source_id),left(trim(coalesce(p_listing_title,'')),160),p_reason,left(trim(coalesce(p_detail,'')),800))
  on conflict(reporter_user_id,source_type,source_id) do update set reason=excluded.reason,detail=excluded.detail,status='pending',handled_by=null,handled_at=null,created_at=now()
  returning * into v_report;
  return to_jsonb(v_report);
end;
$$;

create or replace function public.marketplace_moderate_listing(
  p_owner_user_id uuid,
  p_source_type text,
  p_source_id text,
  p_status text,
  p_reason_code text default null,
  p_note text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_control public.marketplace_listing_controls%rowtype;
begin
  if not exists(select 1 from public.deal_admins where user_id=auth.uid()) then raise exception 'admin_required'; end if;
  if p_source_type not in ('personal_shop_product','merchant_product') or p_status not in ('active','frozen','removed') then raise exception 'invalid_listing_moderation'; end if;
  insert into public.marketplace_listing_controls(owner_user_id,source_type,source_id,status,reason_code,moderator_note,reviewed_by,reviewed_at)
  values(p_owner_user_id,p_source_type,trim(p_source_id),p_status,nullif(trim(coalesce(p_reason_code,'')),''),nullif(trim(coalesce(p_note,'')),''),auth.uid(),now())
  on conflict(owner_user_id,source_type,source_id) do update set status=excluded.status,reason_code=excluded.reason_code,moderator_note=excluded.moderator_note,reviewed_by=excluded.reviewed_by,reviewed_at=excluded.reviewed_at,updated_at=now()
  returning * into v_control;
  update public.marketplace_listing_reports set status=case when p_status='active' then 'dismissed' else 'resolved' end,handled_by=auth.uid(),handled_at=now()
  where owner_user_id=p_owner_user_id and source_type=p_source_type and source_id=trim(p_source_id) and status in ('pending','reviewing');
  return to_jsonb(v_control);
end;
$$;

create or replace function public.marketplace_order_event_from_retail()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    insert into public.marketplace_order_events(order_type,order_id,order_code,actor_user_id,event_type,next_status,payload)
    values('merchant_retail',new.id,new.order_code,coalesce(v_actor,new.customer_user_id),'created',new.status,jsonb_build_object('subtotal',new.subtotal,'item_count',new.item_count));
  elsif old.status is distinct from new.status then
    insert into public.marketplace_order_events(order_type,order_id,order_code,actor_user_id,event_type,previous_status,next_status,payload)
    values('merchant_retail',new.id,new.order_code,coalesce(v_actor,new.merchant_user_id),'status_changed',old.status,new.status,jsonb_build_object('pickup_at',new.pickup_at,'merchant_note',new.merchant_note));
  end if;
  return new;
end;
$$;

drop trigger if exists marketplace_retail_order_event on public.merchant_retail_orders;
create trigger marketplace_retail_order_event after insert or update on public.merchant_retail_orders
for each row execute function public.marketplace_order_event_from_retail();

create or replace function public.marketplace_accept_merchant_agreement(p_version text default '2026-07-23')
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_row public.merchant_platform_agreements%rowtype;
begin
  if auth.uid() is null or not exists(select 1 from public.merchants where user_id=auth.uid() and verified=true) then raise exception 'merchant_required'; end if;
  insert into public.merchant_platform_agreements(merchant_user_id,agreement_version,accepted_ip)
  values(auth.uid(),left(trim(coalesce(p_version,'2026-07-23')),40),nullif(current_setting('request.headers',true)::jsonb->>'x-forwarded-for',''))
  on conflict(merchant_user_id,agreement_key,agreement_version) do update set accepted_at=now()
  returning * into v_row;
  return to_jsonb(v_row);
end;
$$;

create or replace function public.marketplace_open_retail_dispute(p_order_id uuid,p_reason text,p_detail text default '')
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_order public.merchant_retail_orders%rowtype; v_dispute public.marketplace_order_disputes%rowtype;
begin
  if auth.uid() is null then raise exception 'login_required'; end if;
  if p_reason not in ('not_received','not_as_described','damaged','merchant_cancelled','other') then raise exception 'invalid_dispute_reason'; end if;
  select * into v_order from public.merchant_retail_orders where id=p_order_id for update;
  if not found or auth.uid() not in (v_order.customer_user_id,v_order.merchant_user_id) then raise exception 'order_not_found'; end if;
  if v_order.status='cancelled' then raise exception 'order_closed'; end if;
  insert into public.marketplace_order_disputes(order_type,order_id,opened_by,merchant_user_id,reason,detail)
  values('merchant_retail',v_order.id,auth.uid(),v_order.merchant_user_id,p_reason,left(trim(coalesce(p_detail,'')),1200))
  on conflict(order_type,order_id) do update set reason=excluded.reason,detail=excluded.detail,status='open',opened_by=excluded.opened_by,updated_at=now(),resolution=null,resolved_at=null,resolved_by=null
  returning * into v_dispute;
  update public.merchant_retail_orders set dispute_status='open' where id=v_order.id;
  insert into public.marketplace_order_events(order_type,order_id,order_code,actor_user_id,event_type,previous_status,next_status,payload)
  values('merchant_retail',v_order.id,v_order.order_code,auth.uid(),'dispute_opened',v_order.dispute_status,'open',jsonb_build_object('reason',p_reason));
  return to_jsonb(v_dispute);
end;
$$;

create or replace function public.marketplace_retail_order_history(p_order_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_order public.merchant_retail_orders%rowtype;
begin
  if auth.uid() is null then raise exception 'login_required'; end if;
  select * into v_order from public.merchant_retail_orders where id=p_order_id;
  if not found or (auth.uid() not in (v_order.customer_user_id,v_order.merchant_user_id) and not exists(select 1 from public.deal_admins where user_id=auth.uid())) then raise exception 'order_not_found'; end if;
  return jsonb_build_object('order',to_jsonb(v_order),'events',coalesce((select jsonb_agg(to_jsonb(e) order by e.created_at asc) from public.marketplace_order_events e where e.order_type='merchant_retail' and e.order_id=v_order.id),'[]'::jsonb),'dispute',(select to_jsonb(d) from public.marketplace_order_disputes d where d.order_type='merchant_retail' and d.order_id=v_order.id));
end;
$$;

revoke all on function public.marketplace_public_listing_controls(uuid,text) from public;
revoke all on function public.marketplace_report_listing(uuid,text,text,text,text,text) from public,anon;
revoke all on function public.marketplace_moderate_listing(uuid,text,text,text,text,text) from public,anon;
revoke all on function public.marketplace_accept_merchant_agreement(text) from public,anon;
revoke all on function public.marketplace_open_retail_dispute(uuid,text,text) from public,anon;
revoke all on function public.marketplace_retail_order_history(uuid) from public,anon;
grant execute on function public.marketplace_public_listing_controls(uuid,text) to anon,authenticated;
grant execute on function public.marketplace_report_listing(uuid,text,text,text,text,text) to authenticated;
grant execute on function public.marketplace_moderate_listing(uuid,text,text,text,text,text) to authenticated;
grant execute on function public.marketplace_accept_merchant_agreement(text) to authenticated;
grant execute on function public.marketplace_open_retail_dispute(uuid,text,text) to authenticated;
grant execute on function public.marketplace_retail_order_history(uuid) to authenticated;

-- Public personal shop pages never return paused listings.
create or replace function public.personal_shop_public_snapshot(p_market text, p_slug text)
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'shop', (select to_jsonb(s) from public.personal_shops s where s.market_code=lower(trim(p_market)) and s.slug=lower(trim(p_slug)) and s.status='active'),
    'products', coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc) from public.personal_shop_products p join public.personal_shops s on s.user_id=p.shop_user_id where s.market_code=lower(trim(p_market)) and s.slug=lower(trim(p_slug)) and s.status='active' and p.status='active' and not exists(select 1 from public.marketplace_listing_controls c where c.owner_user_id=p.shop_user_id and c.source_type='personal_shop_product' and c.source_id=p.id::text and c.status in ('frozen','removed'))),'[]'::jsonb)
  );
$$;
