-- 乐生活 v5.153：公测反馈截图附件
-- 私有桶：仅反馈提交者本人及 deal_admins 管理员可读取。

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'beta-feedback',
  'beta-feedback',
  false,
  4194304,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = 4194304,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

create table if not exists public.user_feedback_attachments (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references public.user_feedback(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  slot smallint not null check (slot between 1 and 3),
  storage_path text not null unique check (char_length(storage_path) between 8 and 500),
  file_name text not null check (char_length(file_name) between 1 and 180),
  content_type text not null check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  byte_size integer not null check (byte_size > 0 and byte_size <= 4194304),
  created_at timestamp with time zone not null default now(),
  unique (feedback_id, slot)
);

create index if not exists user_feedback_attachments_feedback_created_idx
  on public.user_feedback_attachments (feedback_id, created_at);

create index if not exists user_feedback_attachments_user_created_idx
  on public.user_feedback_attachments (user_id, created_at desc);

alter table public.user_feedback_attachments enable row level security;
grant select, insert on public.user_feedback_attachments to authenticated;
grant usage, select on sequence public.user_feedback_attachments_id_seq to authenticated;

drop policy if exists "feedback attachment select own" on public.user_feedback_attachments;
create policy "feedback attachment select own"
on public.user_feedback_attachments
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "feedback attachment select admins" on public.user_feedback_attachments;
create policy "feedback attachment select admins"
on public.user_feedback_attachments
for select to authenticated
using (
  exists (
    select 1
    from public.deal_admins a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "feedback attachment insert own" on public.user_feedback_attachments;
create policy "feedback attachment insert own"
on public.user_feedback_attachments
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.user_feedback f
    where f.id = feedback_id
      and f.user_id = (select auth.uid())
  )
);

drop policy if exists "feedback screenshot upload own" on storage.objects;
create policy "feedback screenshot upload own"
on storage.objects
for insert to authenticated
with check (
  bucket_id = 'beta-feedback'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
);

drop policy if exists "feedback screenshot read owner or admin" on storage.objects;
create policy "feedback screenshot read owner or admin"
on storage.objects
for select to authenticated
using (
  bucket_id = 'beta-feedback'
  and (
    (storage.foldername(name))[1] = (select auth.uid()::text)
    or exists (
      select 1
      from public.deal_admins a
      where a.user_id = (select auth.uid())
    )
  )
);

drop policy if exists "feedback screenshot delete own" on storage.objects;
create policy "feedback screenshot delete own"
on storage.objects
for delete to authenticated
using (
  bucket_id = 'beta-feedback'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);
