-- 乐生活 5.200：商家矩阵账号
-- 个人账号可被授权进入认证商家的会员核销工作台。

create table if not exists public.merchant_team_members (
  id bigint generated by default as identity primary key,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  member_user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'clerk' check (role in ('operator', 'clerk')),
  status text not null default 'pending' check (status in ('pending', 'active', 'declined', 'revoked')),
  invited_by uuid not null references auth.users(id) on delete cascade,
  invited_at timestamptz not null default now(),
  responded_at timestamptz,
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (merchant_user_id, member_user_id)
);

create index if not exists merchant_team_members_merchant_idx on public.merchant_team_members (merchant_user_id, status, updated_at desc);
create index if not exists merchant_team_members_member_idx on public.merchant_team_members (member_user_id, status, updated_at desc);
alter table public.merchant_team_members enable row level security;
grant select on public.merchant_team_members to authenticated;
grant usage, select on sequence public.merchant_team_members_id_seq to authenticated;

create or replace function public.merchant_matrix_has_role(p_merchant_user_id uuid, p_allowed_roles text[] default array['operator', 'clerk']::text[])
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select auth.uid() = p_merchant_user_id
  or exists (select 1 from public.merchant_team_members t where t.merchant_user_id = p_merchant_user_id and t.member_user_id = auth.uid() and t.status = 'active' and t.role = any (p_allowed_roles));
$$;
revoke all on function public.merchant_matrix_has_role(uuid, text[]) from public;
grant execute on function public.merchant_matrix_has_role(uuid, text[]) to authenticated;

drop policy if exists "merchant team owner or member reads 5.200" on public.merchant_team_members;
create policy "merchant team owner or member reads 5.200" on public.merchant_team_members for select to authenticated
using ((select auth.uid()) = merchant_user_id or (select auth.uid()) = member_user_id);

create or replace function public.merchant_matrix_my_access()
returns table (team_member_id bigint, merchant_user_id uuid, role text, merchant jsonb)
language sql stable security definer set search_path = public, pg_temp as $$
  select t.id, t.merchant_user_id, t.role,
    jsonb_build_object('user_id',m.user_id,'business_name',m.business_name,'logo',m.logo,'cover_image',m.cover_image,'address',m.address,'verified',m.verified,'loyalty_target',m.loyalty_target,'loyalty_reward',m.loyalty_reward,'points_per_visit',m.points_per_visit,'membership_tiers',m.membership_tiers,'birthday_reward',m.birthday_reward)
  from public.merchant_team_members t join public.merchants m on m.user_id = t.merchant_user_id
  where t.member_user_id = auth.uid() and t.status = 'active' and coalesce(m.verified,false) = true order by t.updated_at desc;
$$;

create or replace function public.merchant_matrix_search_people(p_query text)
returns table (user_id uuid, name text, avatar text)
language sql stable security definer set search_path = public, pg_temp as $$
  select p.user_id, coalesce(nullif(p.name,''),'乐生活用户'), p.avatar from public.profiles p
  where auth.uid() is not null and length(trim(coalesce(p_query,''))) >= 1 and p.user_id <> auth.uid() and p.name ilike '%' || trim(p_query) || '%'
  order by p.updated_at desc nulls last limit 8;
$$;

create or replace function public.merchant_matrix_invite_member(p_member_user_id uuid, p_role text default 'clerk')
returns public.merchant_team_members language plpgsql security definer set search_path = public, pg_temp as $$
declare v_row public.merchant_team_members;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if p_member_user_id is null or p_member_user_id = auth.uid() then raise exception 'invalid_member'; end if;
  if p_role not in ('operator','clerk') then raise exception 'invalid_role'; end if;
  if not exists (select 1 from public.merchants where user_id = auth.uid() and verified = true) then raise exception 'merchant_not_verified'; end if;
  if not exists (select 1 from public.profiles where user_id = p_member_user_id) then raise exception 'member_not_found'; end if;
  insert into public.merchant_team_members (merchant_user_id,member_user_id,role,status,invited_by,invited_at,responded_at,revoked_at,updated_at)
  values (auth.uid(),p_member_user_id,p_role,'pending',auth.uid(),now(),null,null,now())
  on conflict (merchant_user_id,member_user_id) do update set role=excluded.role,status='pending',invited_by=auth.uid(),invited_at=now(),responded_at=null,revoked_at=null,updated_at=now() returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.merchant_matrix_respond_invite(p_team_member_id bigint, p_accept boolean)
returns public.merchant_team_members language plpgsql security definer set search_path = public, pg_temp as $$
declare v_row public.merchant_team_members;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  update public.merchant_team_members set status=case when p_accept then 'active' else 'declined' end,responded_at=now(),updated_at=now() where id=p_team_member_id and member_user_id=auth.uid() and status='pending' returning * into v_row;
  if not found then raise exception 'invite_not_found'; end if; return v_row;
end;
$$;

create or replace function public.merchant_matrix_revoke_member(p_team_member_id bigint)
returns public.merchant_team_members language plpgsql security definer set search_path = public, pg_temp as $$
declare v_row public.merchant_team_members;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  update public.merchant_team_members set status='revoked',revoked_at=now(),updated_at=now() where id=p_team_member_id and merchant_user_id=auth.uid() returning * into v_row;
  if not found then raise exception 'team_member_not_found'; end if; return v_row;
end;
$$;

revoke all on function public.merchant_matrix_my_access() from public;
revoke all on function public.merchant_matrix_search_people(text) from public;
revoke all on function public.merchant_matrix_invite_member(uuid,text) from public;
revoke all on function public.merchant_matrix_respond_invite(bigint,boolean) from public;
revoke all on function public.merchant_matrix_revoke_member(bigint) from public;
grant execute on function public.merchant_matrix_my_access() to authenticated;
grant execute on function public.merchant_matrix_search_people(text) to authenticated;
grant execute on function public.merchant_matrix_invite_member(uuid,text) to authenticated;
grant execute on function public.merchant_matrix_respond_invite(bigint,boolean) to authenticated;
grant execute on function public.merchant_matrix_revoke_member(bigint) to authenticated;

drop policy if exists "matrix staff read memberships 5.200" on public.merchant_memberships;
create policy "matrix staff read memberships 5.200" on public.merchant_memberships for select to authenticated using (public.merchant_matrix_has_role(merchant_user_id, array['operator','clerk']));
drop policy if exists "matrix staff update memberships 5.200" on public.merchant_memberships;
create policy "matrix staff update memberships 5.200" on public.merchant_memberships for update to authenticated using (public.merchant_matrix_has_role(merchant_user_id, array['operator','clerk'])) with check (public.merchant_matrix_has_role(merchant_user_id, array['operator','clerk']));

alter table public.merchant_member_transactions add column if not exists operator_user_id uuid references auth.users(id);
create index if not exists merchant_member_transactions_operator_created_idx on public.merchant_member_transactions (operator_user_id, created_at desc);
drop policy if exists "matrix staff read member transactions 5.200" on public.merchant_member_transactions;
create policy "matrix staff read member transactions 5.200" on public.merchant_member_transactions for select to authenticated using (public.merchant_matrix_has_role(merchant_user_id, array['operator','clerk']));
drop policy if exists "matrix staff insert member transactions 5.200" on public.merchant_member_transactions;
create policy "matrix staff insert member transactions 5.200" on public.merchant_member_transactions for insert to authenticated with check (public.merchant_matrix_has_role(merchant_user_id, array['operator','clerk']) and operator_user_id = auth.uid());
drop policy if exists "matrix staff insert activity notifications 5.200" on public.member_activity_notifications;
create policy "matrix staff insert activity notifications 5.200" on public.member_activity_notifications for insert to authenticated with check (public.merchant_matrix_has_role(merchant_user_id, array['operator','clerk']));

create or replace function public.redeem_merchant_reward(p_membership_id bigint,p_quantity integer)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_actor uuid:=auth.uid(); v_membership public.merchant_memberships%rowtype; v_target integer; v_reward text; v_before integer; v_deduct integer; v_after integer; v_transaction_id bigint;
begin
  if v_actor is null then raise exception 'not authenticated'; end if; if coalesce(p_quantity,0)<1 then raise exception 'quantity must be at least 1'; end if;
  select * into v_membership from public.merchant_memberships where id=p_membership_id for update;
  if not found or not public.merchant_matrix_has_role(v_membership.merchant_user_id,array['operator','clerk']) then raise exception 'not allowed'; end if;
  select greatest(1,coalesce(loyalty_target,8)),coalesce(nullif(trim(loyalty_reward),''),'会员奖励') into v_target,v_reward from public.merchants where user_id=v_membership.merchant_user_id limit 1;
  v_target:=coalesce(v_target,8); v_reward:=coalesce(v_reward,'会员奖励'); v_before:=greatest(0,coalesce(v_membership.stamp_count,0)); v_deduct:=v_target*p_quantity; if v_before<v_deduct then raise exception 'insufficient stamps'; end if; v_after:=v_before-v_deduct;
  update public.merchant_memberships set stamp_count=v_after,updated_at=now() where id=v_membership.id;
  insert into public.merchant_member_transactions (membership_id,merchant_user_id,operator_user_id,user_id,action,delta,before_value,after_value,source,note,transaction_kind)
  values (v_membership.id,v_membership.merchant_user_id,v_actor,v_membership.user_id,'stamp',-v_deduct,v_before,v_after,'manual',format('奖励兑换：%s 份「%s」，每份扣 %s 次',p_quantity,v_reward,v_target),'reward_redeem') returning id into v_transaction_id;
  return jsonb_build_object('membership_id',v_membership.id,'transaction_id',v_transaction_id,'before_value',v_before,'after_value',v_after,'quantity',p_quantity,'reward',v_reward);
end;
$$;

create or replace function public.revert_merchant_reward_redemption(p_transaction_id bigint)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_actor uuid:=auth.uid(); v_redemption public.merchant_member_transactions%rowtype; v_membership public.merchant_memberships%rowtype; v_before integer; v_restore integer; v_after integer; v_reversal_id bigint;
begin
  if v_actor is null then raise exception 'not authenticated'; end if; select * into v_redemption from public.merchant_member_transactions where id=p_transaction_id for update;
  if not found or not public.merchant_matrix_has_role(v_redemption.merchant_user_id,array['operator','clerk']) then raise exception 'not allowed'; end if;
  if v_redemption.transaction_kind<>'reward_redeem' or v_redemption.revoked_at is not null then raise exception 'redemption_not_reversible'; end if; v_restore:=abs(coalesce(v_redemption.delta,0)); if v_restore<1 then raise exception 'invalid redemption amount'; end if;
  select * into v_membership from public.merchant_memberships where id=v_redemption.membership_id for update; if not found then raise exception 'membership not found'; end if; v_before:=greatest(0,coalesce(v_membership.stamp_count,0)); v_after:=v_before+v_restore;
  update public.merchant_memberships set stamp_count=v_after,updated_at=now() where id=v_membership.id; update public.merchant_member_transactions set revoked_at=now(),revoked_by=v_actor where id=v_redemption.id;
  insert into public.merchant_member_transactions (membership_id,merchant_user_id,operator_user_id,user_id,action,delta,before_value,after_value,source,note,transaction_kind,reversal_of_id)
  values (v_membership.id,v_membership.merchant_user_id,v_actor,v_membership.user_id,'stamp',v_restore,v_before,v_after,'manual',format('撤销奖励兑换：恢复 %s 次消费记录',v_restore),'reward_reversal',v_redemption.id) returning id into v_reversal_id;
  return jsonb_build_object('membership_id',v_membership.id,'redemption_id',v_redemption.id,'reversal_id',v_reversal_id,'before_value',v_before,'after_value',v_after);
end;
$$;

create or replace function public.redeem_merchant_coupon_claim(p_claim_id bigint)
returns public.merchant_coupon_claims language plpgsql security definer set search_path = public, pg_temp as $$
declare claim_row public.merchant_coupon_claims; merchant_coupons jsonb;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if; select * into claim_row from public.merchant_coupon_claims where id=p_claim_id for update; if not found then raise exception 'coupon_claim_not_found'; end if;
  if not public.merchant_matrix_has_role(claim_row.merchant_user_id,array['operator','clerk']) then raise exception 'not_coupon_merchant'; end if; if claim_row.status<>'claimed' then raise exception 'coupon_already_redeemed'; end if;
  select coupons into merchant_coupons from public.merchants where user_id=claim_row.merchant_user_id and verified=true; if merchant_coupons is null then raise exception 'merchant_not_verified'; end if;
  if not exists (select 1 from jsonb_array_elements(merchant_coupons) with ordinality as item(value,ord) where coalesce(item.value->>'id','legacy-'||(item.ord-1)::text)=claim_row.coupon_id and coalesce(item.value->>'active','true')<>'false') then raise exception 'coupon_not_available'; end if;
  update public.merchant_coupon_claims set status='redeemed',redeemed_at=now(),redeemed_by=auth.uid() where id=claim_row.id returning * into claim_row; return claim_row;
end;
$$;
revoke all on function public.redeem_merchant_reward(bigint,integer) from public;
revoke all on function public.revert_merchant_reward_redemption(bigint) from public;
revoke all on function public.redeem_merchant_coupon_claim(bigint) from public;
grant execute on function public.redeem_merchant_reward(bigint,integer) to authenticated;
grant execute on function public.revert_merchant_reward_redemption(bigint) to authenticated;
grant execute on function public.redeem_merchant_coupon_claim(bigint) to authenticated;
analyze public.merchant_team_members;
analyze public.merchant_member_transactions;
