-- 乐生活 v5.617：餐饮外卖 Stripe 在线支付、账单与优惠券核销闭环。

alter table public.merchant_orders
  add column if not exists delivery_fee numeric(10,2) not null default 0,
  add column if not exists payment_provider text,
  add column if not exists payment_provider_reference text;

alter table public.merchant_orders
  drop constraint if exists merchant_orders_delivery_fee_check,
  add constraint merchant_orders_delivery_fee_check check (delivery_fee >= 0),
  drop constraint if exists merchant_orders_payment_status_check,
  add constraint merchant_orders_payment_status_check
    check (payment_status in ('unpaid','processing','paid','failed','refund_pending','refunded'));

alter table public.merchant_order_bills
  add column if not exists delivery_fee numeric(10,2) not null default 0,
  add column if not exists payment_provider text,
  add column if not exists payment_provider_reference text;

create table if not exists public.merchant_order_payment_attempts (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.merchant_orders(id) on delete cascade,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'stripe',
  provider_payment_id text not null unique,
  status text not null default 'requires_action'
    check (status in ('requires_action','processing','succeeded','failed','cancelled')),
  amount numeric(10,2) not null check (amount >= 0),
  currency text not null default 'usd',
  failure_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists merchant_order_payment_attempts_order_idx
  on public.merchant_order_payment_attempts (order_id, created_at desc);

alter table public.merchant_order_payment_attempts enable row level security;
grant select on public.merchant_order_payment_attempts to authenticated;

drop policy if exists "Customers can read own restaurant payment attempts"
  on public.merchant_order_payment_attempts;
drop policy if exists "Merchants can read restaurant payment attempts"
  on public.merchant_order_payment_attempts;
drop policy if exists "Restaurant payment attempts are visible to participants"
  on public.merchant_order_payment_attempts;
create policy "Restaurant payment attempts are visible to participants"
  on public.merchant_order_payment_attempts
  for select to authenticated
  using (
    user_id = auth.uid()
    or public.merchant_matrix_has_permission(merchant_user_id, 'order_manage')
    or public.merchant_matrix_has_permission(merchant_user_id, 'order_complete')
  );

drop function if exists public.merchant_takeout_order_submit(
  uuid,jsonb,text,text,text,text,timestamptz,text,timestamptz,text,numeric,numeric,jsonb
);

create function public.merchant_takeout_order_submit(
  p_merchant_user_id uuid,
  p_items jsonb,
  p_customer_name text,
  p_customer_phone text,
  p_fulfillment text,
  p_delivery_address text default '',
  p_delivery_at timestamptz default null,
  p_customer_note text default '',
  p_estimated_at timestamptz default null,
  p_requested_payment_method text default 'online',
  p_tip_amount numeric default 0,
  p_quoted_discount_amount numeric default 0,
  p_coupon_claim_ids jsonb default '[]'::jsonb,
  p_delivery_fee numeric default 0
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_order public.merchant_orders%rowtype;
  v_products jsonb;
  v_item jsonb;
  v_product jsonb;
  v_product_id text;
  v_quantity integer;
  v_unit_price numeric(10,2);
  v_price_label text;
  v_subtotal numeric(10,2) := 0;
  v_count integer := 0;
  v_claim_id bigint;
begin
  if v_user_id is null then raise exception 'merchant_order_login_required'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'merchant_order_empty'; end if;
  if coalesce(trim(p_customer_name),'') = '' or coalesce(trim(p_customer_phone),'') = '' then raise exception 'merchant_order_contact_required'; end if;
  if p_fulfillment not in ('pickup','delivery') then raise exception 'merchant_order_invalid_fulfillment'; end if;
  if p_fulfillment = 'delivery' and coalesce(trim(p_delivery_address),'') = '' then raise exception 'merchant_order_delivery_address_required'; end if;
  if coalesce(p_requested_payment_method,'') not in ('apple_pay','google_pay','card','gift_card','online') then raise exception 'merchant_order_invalid_payment_method'; end if;
  if coalesce(p_tip_amount,0) < 0 or coalesce(p_tip_amount,0) > 10000 then raise exception 'merchant_order_invalid_tip'; end if;
  if coalesce(p_delivery_fee,0) < 0 or coalesce(p_delivery_fee,0) > 1000 then raise exception 'merchant_order_invalid_delivery_fee'; end if;
  if jsonb_typeof(coalesce(p_coupon_claim_ids,'[]'::jsonb)) <> 'array' then raise exception 'merchant_order_invalid_coupon'; end if;

  select products into v_products
  from public.merchants
  where user_id = p_merchant_user_id and verified = true;
  if not found then raise exception 'merchant_order_merchant_not_found'; end if;

  for v_claim_id in
    select value::bigint
    from jsonb_array_elements_text(coalesce(p_coupon_claim_ids,'[]'::jsonb)) value
  loop
    if not exists (
      select 1 from public.merchant_coupon_claims
      where id = v_claim_id
        and merchant_user_id = p_merchant_user_id
        and user_id = v_user_id
        and status = 'claimed'
    ) then
      raise exception 'merchant_order_coupon_invalid';
    end if;
  end loop;

  insert into public.merchant_orders (
    merchant_user_id, table_id, table_name, user_id, user_name, order_type, fulfillment,
    customer_name, customer_phone, delivery_address, delivery_at, customer_note, estimated_at,
    requested_payment_method, tip_amount, delivery_fee, quoted_discount_amount,
    coupon_claim_ids, note, payment_status
  ) values (
    p_merchant_user_id, null,
    case when p_fulfillment = 'delivery' then '送餐上门' else '到店自取' end,
    v_user_id, left(trim(p_customer_name),40), 'takeout', p_fulfillment,
    left(trim(p_customer_name),40), left(trim(p_customer_phone),32),
    case when p_fulfillment = 'delivery' then left(trim(p_delivery_address),240) else null end,
    p_delivery_at, left(coalesce(trim(p_customer_note),''),240), p_estimated_at,
    p_requested_payment_method, round(greatest(coalesce(p_tip_amount,0),0),2),
    round(greatest(coalesce(p_delivery_fee,0),0),2), 0,
    coalesce(p_coupon_claim_ids,'[]'::jsonb), '', 'unpaid'
  ) returning * into v_order;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_product_id := coalesce(v_item->>'product_id',v_item->>'id','');
    v_quantity := greatest(1,least(99,coalesce(nullif(v_item->>'quantity','')::integer,1)));
    select value into v_product
    from jsonb_array_elements(coalesce(v_products,'[]'::jsonb))
    where value->>'id' = v_product_id
      and coalesce((value->>'active')::boolean,true) = true
      and coalesce((value->>'orderable')::boolean,true) = true
    limit 1;
    if v_product is null then raise exception 'merchant_order_product_unavailable:%', v_product_id; end if;
    v_price_label := coalesce(v_product->>'price','');
    v_unit_price := coalesce(nullif(substring(v_price_label from '([0-9]+([.][0-9]{1,2})?)'),'')::numeric,0);
    insert into public.merchant_order_items (
      order_id,batch_no,product_id,product_name,product_image,product_categories,
      unit_price,price_label,quantity
    ) values (
      v_order.id,1,v_product_id,coalesce(v_product->>'name','未命名商品'),
      nullif(v_product->>'image',''),
      coalesce(v_product->'categories',jsonb_build_array(coalesce(v_product->>'category','其他'))),
      v_unit_price,v_price_label,v_quantity
    );
    v_subtotal := v_subtotal + v_unit_price * v_quantity;
    v_count := v_count + v_quantity;
  end loop;

  update public.merchant_orders
  set subtotal = round(v_subtotal,2),
      item_count = v_count,
      quoted_discount_amount = round(least(greatest(coalesce(p_quoted_discount_amount,0),0), v_subtotal),2),
      updated_at = now()
  where id = v_order.id;
  return v_order.id;
end;
$$;

revoke all on function public.merchant_takeout_order_submit(
  uuid,jsonb,text,text,text,text,timestamptz,text,timestamptz,text,numeric,numeric,jsonb,numeric
) from public;
grant execute on function public.merchant_takeout_order_submit(
  uuid,jsonb,text,text,text,text,timestamptz,text,timestamptz,text,numeric,numeric,jsonb,numeric
) to authenticated;

create or replace function public.merchant_takeout_order_finalize_stripe_payment(
  p_order_id uuid,
  p_provider_payment_id text,
  p_payment_method text,
  p_amount numeric,
  p_payment_environment text default 'test'
)
returns public.merchant_order_bills
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.merchant_orders%rowtype;
  v_bill public.merchant_order_bills%rowtype;
  v_expected numeric(12,2);
  v_paid_method text;
  v_remaining integer;
begin
  select * into v_order
  from public.merchant_orders
  where id = p_order_id
  for update;
  if not found then raise exception 'restaurant_order_not_found'; end if;
  if v_order.order_type <> 'takeout' then raise exception 'restaurant_order_not_takeout'; end if;
  if v_order.status = 'cancelled' then raise exception 'restaurant_order_cancelled'; end if;

  select * into v_bill
  from public.merchant_order_bills
  where order_id = p_order_id;
  if found then return v_bill; end if;

  v_expected := round(greatest(
    coalesce(v_order.subtotal,0)
    + coalesce(v_order.delivery_fee,0)
    + coalesce(v_order.tip_amount,0)
    - coalesce(v_order.quoted_discount_amount,0),
    0
  ),2);
  if abs(v_expected - round(greatest(coalesce(p_amount,0),0),2)) > 0.009 then
    raise exception 'restaurant_payment_amount_mismatch';
  end if;
  if coalesce(trim(p_provider_payment_id),'') = '' then
    raise exception 'restaurant_payment_reference_required';
  end if;

  v_paid_method := format(
    '%s_%s',
    case when p_payment_environment = 'live' then 'stripe' else 'stripe_test' end,
    coalesce(nullif(trim(p_payment_method),''),'card')
  );

  update public.merchant_coupon_claims
  set status = 'redeemed',
      redeemed_at = now(),
      redeemed_by = v_order.user_id
  where id in (
    select value::bigint
    from jsonb_array_elements_text(coalesce(v_order.coupon_claim_ids,'[]'::jsonb)) value
  )
    and merchant_user_id = v_order.merchant_user_id
    and user_id = v_order.user_id
    and status = 'claimed';

  select count(*) into v_remaining
  from public.merchant_order_items
  where order_id = p_order_id and not coalesce(is_served,false);

  update public.merchant_orders
  set payment_status = 'paid',
      paid_at = now(),
      paid_method = v_paid_method,
      payment_provider = 'stripe',
      payment_provider_reference = p_provider_payment_id,
      status = case when v_remaining = 0 then 'completed' else status end,
      completed_at = case when v_remaining = 0 then now() else completed_at end,
      updated_at = now()
  where id = p_order_id;

  insert into public.merchant_order_bills (
    order_id, merchant_user_id, user_id, payment_method, subtotal, delivery_fee,
    discount_amount, tip_amount, total_amount, coupon_claim_ids,
    payment_provider, payment_provider_reference
  ) values (
    p_order_id, v_order.merchant_user_id, v_order.user_id, v_paid_method,
    coalesce(v_order.subtotal,0), coalesce(v_order.delivery_fee,0),
    coalesce(v_order.quoted_discount_amount,0), coalesce(v_order.tip_amount,0),
    v_expected, coalesce(v_order.coupon_claim_ids,'[]'::jsonb),
    'stripe', p_provider_payment_id
  )
  on conflict (order_id) do update
  set payment_method = excluded.payment_method,
      subtotal = excluded.subtotal,
      delivery_fee = excluded.delivery_fee,
      discount_amount = excluded.discount_amount,
      tip_amount = excluded.tip_amount,
      total_amount = excluded.total_amount,
      coupon_claim_ids = excluded.coupon_claim_ids,
      payment_provider = excluded.payment_provider,
      payment_provider_reference = excluded.payment_provider_reference
  returning * into v_bill;

  return v_bill;
end;
$$;

revoke all on function public.merchant_takeout_order_finalize_stripe_payment(
  uuid,text,text,numeric,text
) from public, anon, authenticated;
grant execute on function public.merchant_takeout_order_finalize_stripe_payment(
  uuid,text,text,numeric,text
) to service_role;
