create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text,
  type text not null default 'bug' check (type in ('bug','suggestion','experience')),
  title text not null check (char_length(title) between 1 and 80),
  body text not null check (char_length(body) between 1 and 1200),
  app_version text,
  page_path text,
  device_info text,
  status text not null default 'pending' check (status in ('pending','reviewing','resolved')),
  handled_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.user_feedback enable row level security;

drop policy if exists "feedback_insert_own" on public.user_feedback;
create policy "feedback_insert_own" on public.user_feedback for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "feedback_select_own" on public.user_feedback;
create policy "feedback_select_own" on public.user_feedback for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "feedback_admin_select" on public.user_feedback;
create policy "feedback_admin_select" on public.user_feedback for select to authenticated using (exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid())));
drop policy if exists "feedback_admin_update" on public.user_feedback;
create policy "feedback_admin_update" on public.user_feedback for update to authenticated using (exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid()))) with check (exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid())));

create index if not exists user_feedback_created_at_idx on public.user_feedback (created_at desc);
create index if not exists user_feedback_status_created_at_idx on public.user_feedback (status, created_at desc);
