insert into public.deal_tracked_products (
  retailer_key,
  retailer_name,
  product_key,
  product_name,
  product_name_cn,
  category,
  unit,
  location,
  source_url,
  source_type,
  source_config,
  is_food_low_price,
  is_hot,
  ai_summary_cn,
  notes
) values
  (
    'walmart',
    'Walmart',
    'replace-with-walmart-item-id',
    'Replace with exact Walmart product name',
    '替换为中文商品名',
    'food',
    '替换单位',
    '网购 / 门店',
    'https://www.walmart.com/ip/replace-with-product-url',
    'public_page',
    '{}'::jsonb,
    true,
    false,
    '价格来自 Walmart 公开商品页每日缓存，最终以官网显示为准。',
    '4.50 外部公开页面抓取模板'
  ),
  (
    'target',
    'Target',
    'replace-with-target-tcin',
    'Replace with exact Target product name',
    '替换为中文商品名',
    'food',
    '替换单位',
    '网购 / 门店',
    'https://www.target.com/p/-/A-replace-with-tcin',
    'public_page',
    '{}'::jsonb,
    true,
    false,
    '价格来自 Target 公开商品页每日缓存，最终以官网显示为准。',
    '4.50 外部公开页面抓取模板'
  ),
  (
    'costco',
    'Costco',
    'replace-with-costco-item-id',
    'Replace with exact Costco product name',
    '替换为中文商品名',
    'food',
    '替换单位',
    '会员仓储 / 门店',
    'https://www.costco.com/replace-with-product-url.product.replace.html',
    'experimental_scraper',
    '{}'::jsonb,
    true,
    false,
    '价格来自 Costco 公开商品页每日缓存；会员、邮编和门店会影响最终价格。',
    '4.50 实验抓取模板；如抓取失败或价格异常，请人工修正'
  ),
  (
    'samsclub',
    'Sam''s Club',
    'replace-with-sams-item-id',
    'Replace with exact Sam''s Club product name',
    '替换为中文商品名',
    'food',
    '替换单位',
    '会员仓储 / 门店',
    'https://www.samsclub.com/p/replace-with-product-url/prodreplace',
    'experimental_scraper',
    '{}'::jsonb,
    true,
    false,
    '价格来自 Sam''s Club 公开商品页每日缓存；会员、邮编和门店会影响最终价格。',
    '4.50 实验抓取模板；如抓取失败或价格异常，请人工修正'
  ),
  (
    'aldi',
    'ALDI',
    'replace-with-aldi-product-id',
    'Replace with exact ALDI weekly item name',
    '替换为中文商品名',
    'food',
    '替换单位',
    '门店 / 周广告',
    'https://www.aldi.us/weekly-specials/our-weekly-ads/',
    'public_page',
    '{}'::jsonb,
    true,
    false,
    '价格来自 ALDI 周广告或公开页面每日缓存，最终以门店和官网显示为准。',
    '4.50 外部公开页面抓取模板；ALDI 周广告若无结构化价格，需人工补正'
  ),
  (
    'macys',
    'Macy''s',
    'replace-with-macys-product-id',
    'Replace with exact Macy''s product name',
    '替换为中文商品名',
    'home',
    '件',
    '网购 / 门店',
    'https://www.macys.com/shop/product/replace-with-product-url',
    'public_page',
    '{}'::jsonb,
    false,
    false,
    '价格来自 Macy''s 公开商品页每日缓存，最终以官网显示为准。',
    '4.50 外部公开页面抓取模板'
  )
on conflict (retailer_key, product_name, (coalesce(product_key, ''))) do update set
  source_url = excluded.source_url,
  source_type = excluded.source_type,
  source_config = excluded.source_config,
  ai_summary_cn = excluded.ai_summary_cn,
  notes = excluded.notes,
  updated_at = now();
