(() => {
  const SUPABASE_URL='https://ptxdxepmggmjcndgukjk.supabase.co';
  const SUPABASE_KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app=document.getElementById('queueManageApp');
  const query=new URLSearchParams(location.search);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const session=()=>{try{return JSON.parse(localStorage.getItem('wanba_session')||'null');}catch(error){return null;}};
  const api=(path,options={})=>{const current=session();return fetch(SUPABASE_URL+path,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${current?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});};
  let merchant=null,rows=[],tables=[],timer=null;
  const close=()=>history.length>1?history.back():location.assign(`/restaurant/manage/?merchant=${encodeURIComponent(query.get('merchant')||'')}`);
  const top=()=>`<header class="top"><button onclick="QueueManager.close()">‹</button><b>排队管理</b><button onclick="QueueManager.reload()">↻</button></header>`;
  const toast=message=>{document.querySelector('.toast')?.remove();const node=document.createElement('div');node.className='toast';node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),2500);};
  const time=value=>{try{return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit'}).format(new Date(value));}catch(error){return '';}};
  const tableOptions=()=>`<option value="">选择餐桌后入座</option>${tables.map(table=>`<option value="${Number(table.id)}">${esc(table.table_name)}</option>`).join('')}`;
  const ticket=(row,history=false)=>{const preorder=Array.isArray(row.preorder_items)?row.preorder_items:[];const status={seated:'已入座',cancelled:'已取消',expired:'已过期'}[row.status]||'排队中';return `<article class="ticket"><div class="ticket-head"><div><h2>${Number(row.party_size||0)} 人 · ${esc(row.queue_code||'')}</h2><small>${esc(row.customer_name||'顾客')} · ${esc(row.customer_phone||'')} · ${time(row.created_at)}</small></div><span class="number">${history?status:`排队 #${Number(row.queue_number||0)}`}</span></div><div class="info"><span>预计 ${Number(row.estimated_wait_minutes||0)} 分钟</span>${preorder.length?`<span>预点 ${preorder.length} 种菜</span>`:''}</div>${preorder.length?`<p class="preorder">预点菜：${preorder.map(item=>`${esc(item.product_name||item.name||'菜品')} × ${Number(item.quantity||1)}`).join('、')}</p>`:''}${!history?`<div class="actions"><select id="queue-table-${esc(row.id)}">${tableOptions()}</select><button onclick="QueueManager.seat('${esc(row.id)}')">安排入座</button><button class="cancel" onclick="QueueManager.cancel('${esc(row.id)}')">取消</button></div>`:''}</article>`;};
  function render(){const queued=rows.filter(row=>row.status==='queued'),finished=rows.filter(row=>row.status!=='queued');app.innerHTML=`${top()}<section class="hero"><h1>${esc(merchant?.business_name||'餐饮排队')}</h1><p>当天排队、预点菜和入座安排会在这里统一处理。</p></section><section class="summary"><div><span>排队中</span><b>${queued.length}</b></div><div><span>预点菜</span><b>${queued.filter(row=>Array.isArray(row.preorder_items)&&row.preorder_items.length).length}</b></div><div><span>已处理</span><b>${finished.length}</b></div></section><p class="notice">安排入座会保留顾客的预点菜，顾客随后可扫描餐桌二维码确认下单。此页面每 3 分钟自动刷新。</p><section class="queue-list">${queued.length?queued.map(row=>ticket(row)).join(''):'<div class="empty">当前没有排队中的顾客。</div>'}</section>${finished.length?`<section class="history"><h2>今日已处理</h2><div class="queue-list">${finished.map(row=>ticket(row,true)).join('')}</div></section>`:''}`;}
  async function load(){const slug=query.get('merchant');if(!slug){app.innerHTML=`${top()}<div class="empty">缺少商家信息。</div>`;return;}if(!session()?.access_token){app.innerHTML=`${top()}<div class="empty">请使用店长或具有管理权限的员工账号登录。</div>`;return;}try{const merchantRes=await api(`/rest/v1/merchants?slug=eq.${encodeURIComponent(slug)}&select=user_id,business_name&limit=1`);const merchants=merchantRes.ok?await merchantRes.json():[];merchant=merchants[0];if(!merchant?.user_id)throw new Error('merchant_not_found');const [queueRes,tableRes]=await Promise.all([api('/rest/v1/rpc/merchant_waitlist_manager_list',{method:'POST',body:JSON.stringify({p_merchant_user_id:merchant.user_id})}),api(`/rest/v1/merchant_order_tables?merchant_user_id=eq.${encodeURIComponent(merchant.user_id)}&is_active=eq.true&select=id,table_name&order=table_name.asc`)]);if(!queueRes.ok)throw new Error(await queueRes.text());rows=await queueRes.json();tables=tableRes.ok?await tableRes.json():[];render();}catch(error){app.innerHTML=`${top()}<div class="empty">暂时无法读取排队管理。请确认当前账号有餐饮管理权限，并已运行排队数据库脚本。</div>`;}}
  async function seat(id){const select=document.getElementById(`queue-table-${id}`),tableId=Number(select?.value||0);if(!tableId){toast('请先选择顾客入座的餐桌。');return;}try{const response=await api('/rest/v1/rpc/merchant_waitlist_set_status',{method:'POST',body:JSON.stringify({p_waitlist_id:id,p_status:'seated',p_table_id:tableId})});if(!response.ok)throw new Error(await response.text());toast('已安排顾客入座。');await load();}catch(error){toast('安排入座失败，请稍后重试。');}}
  async function cancel(id){if(!confirm('确定取消这位顾客的排队吗？'))return;try{const response=await api('/rest/v1/rpc/merchant_waitlist_set_status',{method:'POST',body:JSON.stringify({p_waitlist_id:id,p_status:'cancelled',p_table_id:null})});if(!response.ok)throw new Error(await response.text());toast('已取消排队。');await load();}catch(error){toast('取消排队失败，请稍后重试。');}}
  window.QueueManager={close,reload:load,seat,cancel};load();timer=setInterval(load,180000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
})();
