(()=>{
  const URL='https://ptxdxepmggmjcndgukjk.supabase.co',KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-',app=document.getElementById('ticketsManageApp'),q=new URLSearchParams(location.search);
  const state={merchant:null,data:{events:[],types:[],sections:[],seats:[],orders:[],tickets:[]},tab:'events'};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const session=()=>JSON.parse(localStorage.getItem('wanba_session')||'null');
  const api=(path,opt={})=>{const s=session();return fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${s?.access_token||KEY}`,'Content-Type':'application/json',...(opt.headers||{})}})};
  const back=()=>{if(window.LeshenghuoModuleBridge?.back?.('/'))return;if(history.length>1)history.back();else location.assign('/')};
  const top=t=>`<header class="top"><button onclick="TicketManage.back()">‹</button><b>${esc(t)}</b><button class="close" onclick="TicketManage.back()">×</button></header>`;
  const date=v=>new Intl.DateTimeFormat('zh-CN',{timeZone:'America/Los_Angeles',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));
  const money=v=>Number(v||0)===0?'免费':`$${Number(v).toFixed(2)}`;
  async function getMerchant(){const r=await api('/rest/v1/rpc/merchant_ticket_public_catalog',{method:'POST',body:JSON.stringify({p_slug:q.get('merchant')})}),data=await r.json();return r.ok?data?.merchant||null:null}
  async function load(){try{state.merchant=await getMerchant();if(!state.merchant)throw 0;const r=await api('/rest/v1/rpc/merchant_ticket_manager_snapshot',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id})}),data=await r.json();if(!r.ok)throw 0;state.data={events:data.events||[],types:data.types||[],sections:data.sections||[],seats:data.seats||[],orders:data.orders||[],tickets:data.tickets||[]};render()}catch(e){app.innerHTML=`${top('票务管理')}<div class="empty">暂时无法读取票务管理。请使用商家主号或具备订单管理权限的员工账号。</div>`}}
  function render(){const d=state.data;app.innerHTML=`${top('票务管理')}<section class="hero"><h1>${esc(state.merchant.business_name)}</h1><p>创建活动、普通票种或精确选座分区，查看订单并现场核销。</p></section><div class="tabs"><button class="${state.tab==='events'?'on':''}" onclick="TicketManage.tab('events')">活动 ${d.events.length}</button><button class="${state.tab==='orders'?'on':''}" onclick="TicketManage.tab('orders')">订单 ${d.orders.length}</button><button class="${state.tab==='redeem'?'on':''}" onclick="TicketManage.tab('redeem')">核销</button></div>${state.tab==='events'?events():state.tab==='orders'?orders():redeem()}`}
  function events(){return `<section class="section">${state.data.events.length?state.data.events.map(e=>`<article class="event-card"><h2>${esc(e.title)}</h2><p class="muted">${date(e.starts_at)} 至 ${date(e.ends_at)}<br>${esc(e.location_text||'未填写地点')}</p><div class="event-meta"><span class="pill">${e.status==='published'?'公开售票':e.status==='draft'?'草稿':'已停止'}</span><span class="pill">${e.seating_mode==='assigned'?'精确选座':e.seating_mode==='zone'?'分区票':'普通票'}</span></div><div class="manager-actions"><button onclick="TicketManage.editEvent('${e.id}')">编辑活动</button>${e.seating_mode==='assigned'?`<button onclick="TicketManage.seating('${e.id}')">编辑座位图</button>`:''}</div>${e.seating_mode==='assigned'?sectionSummary(e.id):types(e.id)}</article>`).join(''):'<div class="empty">还没有票务活动。</div>'}<button class="primary" onclick="TicketManage.editEvent()">创建票务活动</button></section>`}
  function types(eventId){const rows=state.data.types.filter(t=>t.event_id===eventId);return `<div class="subpanel">${rows.map(t=>`<div class="ticket-type"><div><b>${esc(t.name)}</b><div class="small">${money(t.price)} · 库存 ${t.stock} · 每单限 ${t.max_per_order}</div></div><button onclick="TicketManage.editType('${eventId}','${t.id}')">编辑</button></div>`).join('')}<button class="secondary" onclick="TicketManage.editType('${eventId}')">添加票种</button></div>`}
  function sectionSummary(eventId){const rows=state.data.sections.filter(s=>s.event_id===eventId);return `<div class="subpanel">${rows.length?rows.map(s=>{const seats=state.data.seats.filter(x=>x.section_id===s.id),sold=seats.filter(x=>x.status==='sold').length;return `<div class="ticket-type"><div><b><i class="section-dot" style="background:${esc(s.color)}"></i>${esc(s.name)}</b><div class="small">${s.rows_count} 排 × ${s.seats_per_row} 座 · ${money(s.price)} · 已售 ${sold}/${seats.length}</div></div><button onclick="TicketManage.seating('${eventId}','${s.id}')">编辑</button></div>`}).join(''):'<div class="small">还没有创建选座分区。</div>'}<button class="secondary" onclick="TicketManage.addSection('${eventId}')">添加座位分区</button></div>`}
  function orders(){return `<section class="section">${state.data.orders.length?state.data.orders.map(o=>{const e=state.data.events.find(x=>x.id===o.event_id),t=state.data.types.find(x=>x.id===o.ticket_type_id),seats=(o.selected_seat_ids||[]).map(id=>state.data.seats.find(x=>x.id===id)?.label).filter(Boolean);return `<article class="order-card"><b>${esc(o.order_code)} · ${esc(t?.name||seats.join('、')||'选座票')}</b><p class="muted">${esc(o.customer_name)} · ${esc(o.customer_phone)}<br>${o.quantity} 张 · ${money(o.total_amount)} · ${date(o.created_at)}</p><div class="event-meta"><span class="pill">${esc(o.payment_status)}</span><span class="pill">${esc(e?.title||'活动')}</span></div></article>`}).join(''):'<div class="empty">还没有售票订单。</div>'}</section>`}
  function redeem(){return `<section class="section"><article class="form"><h2>票码核销</h2><p class="muted">可使用设备扫码器或直接输入 TKT 开头的票码。</p><label class="field">票务二维码 / 票码<input id="ticketCode" placeholder="例如：TKT-ABCDEFGH"></label><button class="primary" onclick="TicketManage.redeem()">核销入场</button><div id="redeemResult"></div></article></section>`}
  function toLocal(v){const d=v?new Date(v):new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
  function editEvent(id){const e=state.data.events.find(x=>x.id===id)||{starts_at:new Date(Date.now()+86400000),ends_at:new Date(Date.now()+90000000),status:'published',seating_mode:'general'};app.innerHTML=`${top(id?'编辑票务活动':'创建票务活动')}<section class="form"><label class="field">活动名称<input id="teTitle" maxlength="100" value="${esc(e.title||'')}"></label><label class="field">活动说明<textarea id="teDesc" maxlength="2000">${esc(e.description||'')}</textarea></label><div class="row"><label class="field">开始时间<input id="teStart" type="datetime-local" value="${toLocal(e.starts_at)}"></label><label class="field">结束时间<input id="teEnd" type="datetime-local" value="${toLocal(e.ends_at)}"></label></div><label class="field">活动地点<input id="teLocation" maxlength="300" value="${esc(e.location_text||'')}"></label><label class="field">售票方式<select id="teSeating"><option value="general" ${e.seating_mode==='general'?'selected':''}>普通票种（不选座）</option><option value="zone" ${e.seating_mode==='zone'?'selected':''}>分区票种（不同区域不同价格）</option><option value="assigned" ${e.seating_mode==='assigned'?'selected':''}>精确选座（行列座位图）</option></select></label><label class="field">座位图背景链接（选填）<input id="teSeatMap" maxlength="3000" value="${esc(e.seat_map_image||'')}" placeholder="上传场地图后粘贴图片链接；不填则使用系统座位图"></label><label class="field">发布状态<select id="teStatus"><option value="published" ${e.status==='published'?'selected':''}>公开售票</option><option value="draft" ${e.status==='draft'?'selected':''}>保存为草稿</option><option value="cancelled" ${e.status==='cancelled'?'selected':''}>停止售票</option></select></label><button class="primary" onclick="TicketManage.saveEvent('${e.id||''}')">保存活动</button></section>`}
  function seating(eventId,sectionId=''){const e=state.data.events.find(x=>x.id===eventId),s=state.data.sections.find(x=>x.id===sectionId),seats=s?state.data.seats.filter(x=>x.section_id===s.id):[];app.innerHTML=`${top('选座编辑器')}<button class="backline" onclick="TicketManage.tab('events')">‹ 返回活动</button><section class="form"><h2>${esc(e?.title||'')}</h2><p class="muted">创建分区后系统会自动生成行列座位。已售或付款锁定的座位不能调整；可点击可用座位将其封锁或恢复销售。</p>${s?sectionForm(s):'<button class="primary" onclick="TicketManage.addSection(\''+eventId+'\')">添加第一个座位分区</button>'}</section>${s?`<section class="seat-page manager-seat-page"><div class="stage">舞台 / 主活动区</div>${seatRows(s,seats)}<div class="notice">绿色为可售，灰色为封锁，深色为已售或付款锁定。</div></section><button class="secondary" onclick="TicketManage.addSection('${eventId}')">新增座位分区</button>`:''}`}
  function sectionForm(s){return `<label class="field">分区名称<input id="tsName" maxlength="80" value="${esc(s.name||'')}"></label><div class="row"><label class="field">区域颜色<input id="tsColor" type="color" value="${esc(s.color||'#568566')}"></label><label class="field">区域票价（美元）<input id="tsPrice" type="number" min="0" step="0.01" value="${s.price||0}"></label></div><div class="row"><label class="field">排数（新建后不可改）<input id="tsRows" type="number" min="1" max="26" value="${s.rows_count||1}" ${s.id?'disabled':''}></label><label class="field">每排座位数（新建后不可改）<input id="tsCols" type="number" min="1" max="60" value="${s.seats_per_row||1}" ${s.id?'disabled':''}></label></div><button class="primary" onclick="TicketManage.saveSection('${s.event_id}','${s.id||''}')">保存分区</button>`}
  function seatRows(s,seats){const grouped={};seats.forEach(x=>(grouped[x.row_label]||(grouped[x.row_label]=[])).push(x));return Object.entries(grouped).map(([row,list])=>`<div class="seat-row"><em>${esc(row)}</em><div class="seat-grid">${list.map(x=>`<button class="seat ${x.status==='available'?'':'is-unavailable'}" ${['sold','held'].includes(x.status)?'disabled':''} onclick="TicketManage.toggleSeat('${s.event_id}','${s.id}','${x.id}',${x.status==='blocked'?'false':'true'})" title="${esc(x.label)}">${x.seat_number}</button>`).join('')}</div></div>`).join('')}
  function addSection(eventId){const s={event_id:eventId,name:'',color:'#568566',price:0,rows_count:8,seats_per_row:12};app.innerHTML=`${top('添加座位分区')}<button class="backline" onclick="TicketManage.seating('${eventId}')">‹ 返回座位图</button><section class="form"><h2>新建分区</h2><p class="muted">例如：VIP 区、A 区、看台。保存后会自动生成行列座位。</p>${sectionForm(s)}</section>`}
  function editType(eventId,id){const t=state.data.types.find(x=>x.id===id)||{event_id:eventId,price:0,stock:100,max_per_order:6,is_active:true,sort_order:0};app.innerHTML=`${top(id?'编辑票种':'添加票种')}<section class="form"><label class="field">票种名称<input id="ttName" maxlength="80" value="${esc(t.name||'')}" placeholder="例如：早鸟票、成人票、儿童票"></label><label class="field">票种说明<textarea id="ttDesc" maxlength="500">${esc(t.description||'')}</textarea></label><div class="row"><label class="field">票价（美元）<input id="ttPrice" type="number" min="0" step="0.01" value="${t.price}"></label><label class="field">库存张数<input id="ttStock" type="number" min="1" max="100000" value="${t.stock}"></label></div><div class="row"><label class="field">每单限购<input id="ttLimit" type="number" min="1" max="20" value="${t.max_per_order}"></label><label class="field">显示排序<input id="ttSort" type="number" value="${t.sort_order||0}"></label></div><label class="field"><input id="ttActive" type="checkbox" ${t.is_active?'checked':''}> 公开销售此票种</label><button class="primary" onclick="TicketManage.saveType('${t.id||''}','${eventId}')">保存票种</button></section>`}
  async function saveEvent(id){const p_event={id:id||null,title:document.getElementById('teTitle').value.trim(),description:document.getElementById('teDesc').value.trim(),starts_at:new Date(document.getElementById('teStart').value).toISOString(),ends_at:new Date(document.getElementById('teEnd').value).toISOString(),location_text:document.getElementById('teLocation').value.trim(),status:document.getElementById('teStatus').value,seating_mode:document.getElementById('teSeating').value,seat_map_image:document.getElementById('teSeatMap').value.trim()};if(!p_event.title)return alert('请填写活动名称。');if(new Date(p_event.ends_at)<=new Date(p_event.starts_at))return alert('结束时间需要晚于开始时间。');const r=await api('/rest/v1/rpc/merchant_ticket_save_event',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_event})});if(!r.ok)return alert('保存失败，请检查活动信息。');state.tab='events';load()}
  async function saveSection(eventId,id){const p_section={id:id||null,event_id:eventId,name:document.getElementById('tsName').value.trim(),color:document.getElementById('tsColor').value,price:Number(document.getElementById('tsPrice').value),rows_count:Number(document.getElementById('tsRows').value),seats_per_row:Number(document.getElementById('tsCols').value),is_active:true};if(!p_section.name)return alert('请填写分区名称。');const r=await api('/rest/v1/rpc/merchant_ticket_save_section',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_section})});if(!r.ok){const x=await r.json().catch(()=>({}));return alert(String(x.message||'保存失败。已售或已锁座的分区不能改变结构。'))}await load();seating(eventId,p_section.id||state.data.sections.find(x=>x.event_id===eventId)?.id||'')}
  async function toggleSeat(eventId,sectionId,seatId,blocked){const r=await api('/rest/v1/rpc/merchant_ticket_toggle_seat',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_seat_id:seatId,p_blocked:blocked})});if(!r.ok)return alert('该座位已售出或正在被其他用户付款锁定。');await load();seating(eventId,sectionId)}
  async function saveType(id,eventId){const p_type={id:id||null,event_id:eventId,name:document.getElementById('ttName').value.trim(),description:document.getElementById('ttDesc').value.trim(),price:Number(document.getElementById('ttPrice').value),stock:Number(document.getElementById('ttStock').value),max_per_order:Number(document.getElementById('ttLimit').value),sort_order:Number(document.getElementById('ttSort').value),is_active:document.getElementById('ttActive').checked};if(!p_type.name)return alert('请填写票种名称。');const r=await api('/rest/v1/rpc/merchant_ticket_save_type',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_type})});if(!r.ok)return alert('保存失败，请检查票种信息。');state.tab='events';load()}
  async function redeem(){const el=document.getElementById('ticketCode'),code=el.value.trim(),out=document.getElementById('redeemResult');if(!code)return;const r=await api('/rest/v1/rpc/merchant_ticket_redeem',{method:'POST',body:JSON.stringify({p_ticket_code:code})}),data=await r.json();out.innerHTML=!r.ok?'<div class="notice" style="margin-top:12px;">未找到可核销的票。请确认票码、付款状态和活动商家。</div>':`<div class="success" style="margin-top:12px;"><strong>${data.ok?'核销成功':'此票已核销'}</strong><p>${esc(data.event_title)} · ${esc(data.ticket_type)}<br>${esc(data.holder_name)} · ${esc(data.ticket_code)}</p></div>`;if(r.ok)el.value=''}
  window.TicketManage={back,tab:t=>{state.tab=t;render()},editEvent,editType,saveEvent,saveType,seating,addSection,saveSection,toggleSeat,redeem};load();
})();
