(()=>{
  const URL='https://ptxdxepmggmjcndgukjk.supabase.co',KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app=document.getElementById('servicesApp'),q=new URLSearchParams(location.search);
  const state={tab:q.get('tab')==='homecare'?'homecare':'gigs',catalog:{requests:[],providers:[]},dashboard:null};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const session=()=>JSON.parse(localStorage.getItem('wanba_session')||'null');
  const profile=()=>JSON.parse(localStorage.getItem('wanba_profile')||'{}');
  const isAuthed=()=>!!session()?.access_token;
  const api=(path,opt={})=>{const s=session();return fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${s?.access_token||KEY}`,'Content-Type':'application/json',...(opt.headers||{})}})};
  const rpc=async(name,payload={})=>{const r=await api(`/rest/v1/rpc/${name}`,{method:'POST',body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d?.message||d?.hint||'请求失败');return d};
  const back=()=>{if(window.LeshenghuoModuleBridge?.back?.('/'))return;if(history.length>1)history.back();else location.assign('/')};
  const top=t=>`<header class="top"><button aria-label="返回" onclick="Services.back()">‹</button><b>${esc(t)}</b><button class="close" aria-label="关闭" onclick="Services.back()">×</button></header>`;
  const money=v=>Number(v||0)>0?`$${Number(v).toFixed(2)}`:'面议';
  const fmt=v=>v?new Intl.DateTimeFormat('zh-CN',{timeZone:'America/Los_Angeles',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'';
  const loginHint=()=>`<div class="notice important">请先在乐生活首页登录后继续。零工和家政当前只提供信息撮合，不接入付款、担保或平台兜底。</div>`;
  async function load(){try{state.catalog=await rpc('service_public_catalog',{p_kind:'all'});render()}catch(e){app.innerHTML=`${top('零工与家政')}<div class="empty">暂时无法读取服务信息，请稍后再试。</div>`}}
  function render(){app.innerHTML=`${top('零工与家政')}<section class="hero"><h1>找人帮忙，也让技能被看见</h1><p>发布零工需求、获取报价；或寻找已完成人工审核的家政服务人员。</p></section><nav class="tabs"><button class="${state.tab==='gigs'?'active':''}" onclick="Services.tab('gigs')">零工需求</button><button class="${state.tab==='homecare'?'active':''}" onclick="Services.tab('homecare')">家政人员</button><button class="${state.tab==='mine'?'active':''}" onclick="Services.tab('mine')">我的</button></nav><div id="serviceContent"></div>`;renderContent()}
  function renderContent(){const target=document.getElementById('serviceContent');if(!target)return;if(state.tab==='gigs'){target.innerHTML=`<div class="section-head"><h2>附近与最新需求</h2><button class="primary" onclick="Services.requestForm()">发布需求</button></div>${(state.catalog.requests||[]).length?state.catalog.requests.map(requestCard).join(''):'<div class="empty">还没有公开需求，成为第一个发布的人吧。</div>'}`;return}if(state.tab==='homecare'){target.innerHTML=`<div class="section-head"><h2>已审核家政人员</h2><button class="primary" onclick="Services.providerForm()">申请成为家政人员</button></div><div class="notice">家政人员须提交证件进行人工审核，审核通过后才会公开展示。请自行沟通服务内容、价格、税务、保险与用工安排。</div>${(state.catalog.providers||[]).length?state.catalog.providers.map(providerCard).join(''):'<div class="empty">暂时没有已审核的家政人员。</div>'}`;return}renderMine(target)}
  function requestCard(x){return `<article class="request-card"><div class="split"><span class="pill">${esc(x.service_type||'零工')}</span><span class="small">${fmt(x.requested_at)||'时间可协商'}</span></div><h3>${esc(x.title)}</h3><p class="muted">${esc(x.description||'')}</p><p class="small">地点：${esc(x.location_text||'待协商')} · ${Number(x.offer_count||0)} 人报价</p><div class="card-foot"><span class="money">${money(x.budget_min)}${Number(x.budget_max||0)>0?` - ${money(x.budget_max)}`:''}</span><button class="secondary" onclick="Services.offerForm('${x.id}')">我要报价</button></div></article>`}
  function providerCard(x){return `<article class="provider-card"><div class="split"><h3>${esc(x.display_name)}</h3><span class="status good">已审核</span></div><p>${(x.service_types||[]).map(v=>`<span class="pill">${esc(v)}</span>`).join('')}</p><p class="muted">${esc(x.bio||'')||'该服务人员尚未填写介绍。'}</p><p class="small">服务区域：${esc((x.areas||[]).join('、')||'可协商')} · ${Number(x.experience_years||0)} 年经验</p><div class="card-foot"><span class="small">${esc(x.availability_note||'时间请沟通确认')}</span><button class="secondary" onclick="Services.bookForm('${x.user_id}')">预约咨询</button></div></article>`}
  function requestForm(){if(!isAuthed()){app.innerHTML=`${top('发布零工需求')}${loginHint()}`;return}const p=profile();app.innerHTML=`${top('发布零工需求')}<section class="form"><h2>发布需求</h2><div class="notice">请勿发布违法、歧视、危险或需要法定执照但无法提供资质的需求。内容可能进入人工审核。</div><label class="field">需求标题<input id="srTitle" maxlength="80" placeholder="例如：周末协助搬运 10 个纸箱"></label><label class="field">服务类型<input id="srType" maxlength="40" placeholder="搬运、清洁、安装、宠物照护等"></label><label class="field">具体说明<textarea id="srDesc" maxlength="1500" placeholder="写清楚工作内容、工具、时长和注意事项"></textarea></label><label class="field">地点<input id="srLocation" maxlength="160" placeholder="城市或大致区域"></label><div class="grid2"><label class="field">最低预算（美元）<input id="srMin" inputmode="decimal" placeholder="可留空"></label><label class="field">最高预算（美元）<input id="srMax" inputmode="decimal" placeholder="可留空"></label></div><label class="field">期望时间（选填）<input id="srTime" type="datetime-local"></label><label class="field">联系人姓名<input id="srName" maxlength="80" value="${esc(p.display_name||p.name||'')}" placeholder="可修改"></label><label class="field">联系电话<input id="srPhone" inputmode="tel" maxlength="40" placeholder="必填，仅在确认合作后提供给对方"></label><button class="primary wide" onclick="Services.submitRequest()">发布需求</button></section>`}
  async function submitRequest(){const payload={p_kind:'gig',p_title:val('srTitle'),p_description:val('srDesc'),p_service_type:val('srType'),p_location_text:val('srLocation'),p_requested_at:val('srTime')||null,p_budget_min:num('srMin'),p_budget_max:num('srMax'),p_contact_name:val('srName'),p_contact_phone:val('srPhone')};if(!payload.p_title||!payload.p_description||!payload.p_service_type||!payload.p_location_text||!payload.p_contact_name||payload.p_contact_phone.length<5)return alert('请完整填写需求、地点、姓名和联系电话。');try{const d=await rpc('service_create_request',payload);alert(d.status==='review'?'需求已提交，正在进行内容审核。':'需求发布成功。');await load()}catch(e){alert(String(e.message||'发布失败').includes('listing_restricted')?'该内容不符合平台发布规则，请调整后再试。':'发布失败，请稍后重试。')}}
  function offerForm(id){if(!isAuthed()){app.innerHTML=`${top('提交报价')}${loginHint()}`;return}const x=(state.catalog.requests||[]).find(v=>v.id===id);if(!x)return;app.innerHTML=`${top('提交报价')}<section class="form"><h2>${esc(x.title)}</h2><p class="muted">${esc(x.description)}</p><label class="field">报价金额（美元）<input id="soPrice" inputmode="decimal" placeholder="例如 80"></label><label class="field">补充说明<textarea id="soMessage" maxlength="800" placeholder="说明可提供的服务、时间和经验"></textarea></label><div class="notice">提交报价不构成雇佣关系或支付承诺。被选择后，请通过乐生活主页私信继续沟通。</div><button class="primary wide" onclick="Services.submitOffer('${x.id}')">提交报价</button></section>`}
  async function submitOffer(id){const amount=num('soPrice'),message=val('soMessage');if(!amount||!message)return alert('请填写报价和说明。');try{await rpc('service_submit_offer',{p_request_id:id,p_quoted_amount:amount,p_message:message});alert('报价已提交。');await load()}catch(e){alert('提交失败，请稍后重试。')}}
  function providerForm(){if(!isAuthed()){app.innerHTML=`${top('申请成为家政人员')}${loginHint()}`;return}const p=profile();app.innerHTML=`${top('家政人员申请')}<section class="form"><h2>提交人工审核</h2><div class="notice important">证件只上传至乐生活私有审核空间，不会向客户公开。乐生活仅提供信息撮合，不参与交易，不承担服务质量、合法用工、税务、保险、薪酬、雇佣关系或纠纷责任。</div><label class="field">展示姓名<input id="hpName" maxlength="80" value="${esc(p.display_name||p.name||'')}" placeholder="可使用乐生活昵称或修改"></label><label class="field">服务项目<input id="hpTypes" maxlength="160" placeholder="例如：保洁、育儿、老人陪护，用逗号分隔"></label><label class="field">服务区域<input id="hpAreas" maxlength="160" placeholder="例如：Arcadia, Temple City，用逗号分隔"></label><label class="field">个人介绍<textarea id="hpBio" maxlength="800" placeholder="经验、可服务内容和注意事项"></textarea></label><label class="field">相关经验年数<input id="hpYears" inputmode="numeric" placeholder="例如 3"></label><label class="field">可服务时间<input id="hpAvailability" maxlength="200" placeholder="例如：周一至周五 9:00-17:00"></label><label class="field">身份审核资料（JPG、PNG 或 PDF，5MB 内）<input id="hpId" type="file" accept="image/jpeg,image/png,application/pdf"></label><button class="primary wide" onclick="Services.submitProvider()">提交审核</button></section>`}
  async function uploadIdDocument(file){const s=session();if(!s?.access_token)throw new Error('login_required');if(!file||file.size>5*1024*1024)throw new Error('file_invalid');const clean=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${s.user.id}/${Date.now()}-${clean}`;const r=await fetch(`${URL}/storage/v1/object/homecare-verification/${path}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'true'},body:file});if(!r.ok)throw new Error('upload_failed');return path}
  async function submitProvider(){const f=document.getElementById('hpId').files?.[0];if(!f)return alert('请上传身份审核资料。');try{const path=await uploadIdDocument(f);await rpc('service_upsert_homecare_profile',{p_display_name:val('hpName'),p_service_types:csv('hpTypes'),p_areas:csv('hpAreas'),p_bio:val('hpBio'),p_experience_years:num('hpYears')||0,p_availability_note:val('hpAvailability'),p_id_document_url:path});alert('资料已提交人工审核，审核通过后才会公开展示。');await load()}catch(e){alert(String(e.message||'').includes('file_invalid')?'资料格式或大小不符合要求。':'提交失败，请稍后重试。')}}
  function bookForm(id){if(!isAuthed()){app.innerHTML=`${top('预约家政服务')}${loginHint()}`;return}const x=(state.catalog.providers||[]).find(v=>v.user_id===id),p=profile();if(!x)return;app.innerHTML=`${top('预约咨询')}<section class="form"><h2>${esc(x.display_name)}</h2><p>${(x.service_types||[]).map(v=>`<span class="pill">${esc(v)}</span>`).join('')}</p><label class="field">姓名<input id="hbName" maxlength="80" value="${esc(p.display_name||p.name||'')}" placeholder="可修改"></label><label class="field">联系电话<input id="hbPhone" inputmode="tel" maxlength="40" placeholder="必填"></label><label class="field">期望服务时间<input id="hbTime" type="datetime-local"></label><label class="field">需求说明<textarea id="hbNote" maxlength="1000" placeholder="写明服务地点、人数、时长和需求"></textarea></label><div class="notice">提交后由双方自行联系、协商和确认。平台暂不提供付款、担保或保险。</div><button class="primary wide" onclick="Services.submitBooking('${x.user_id}')">提交预约咨询</button></section>`}
  async function submitBooking(id){const p={p_provider_user_id:id,p_customer_name:val('hbName'),p_customer_phone:val('hbPhone'),p_requested_at:val('hbTime')||null,p_service_type:'家政服务',p_note:val('hbNote')};if(!p.p_customer_name||p.p_customer_phone.length<5||!p.p_note)return alert('请填写姓名、电话和需求说明。');try{await rpc('service_book_homecare',p);alert('预约咨询已提交，请等待对方联系。');await load()}catch(e){alert('提交失败，请稍后重试。')}}
  async function renderMine(target){if(!isAuthed()){target.innerHTML=loginHint();return}target.innerHTML='<div class="loading">正在读取我的服务记录...</div>';try{state.dashboard=await rpc('service_my_dashboard');const d=state.dashboard,bookings=d.bookings||[];target.innerHTML=`<div class="section-head"><h2>我的服务记录</h2><button class="secondary" onclick="Services.adminReview()">审核申请</button></div><section class="panel"><h3>我发布的需求</h3>${(d.requests||[]).length?(d.requests||[]).map(x=>`<div class="list-row"><div><b>${esc(x.title)}</b><div class="small">${esc(x.status)} · ${Number(x.offer_count||0)} 个报价</div></div><button class="secondary" onclick="Services.viewOffers('${x.id}')">查看报价</button></div>`).join(''):'<p class="muted">暂无已发布需求。</p>'}</section><section class="panel"><h3>我的报价</h3>${(d.offers||[]).length?(d.offers||[]).map(x=>`<div class="list-row"><div><b>${esc(x.title||'零工需求')}</b><div class="small">报价 ${money(x.quoted_amount)} · ${esc(x.status)}</div></div></div>`).join(''):'<p class="muted">暂无报价记录。</p>'}</section><section class="panel"><h3>家政资料与预约</h3>${d.provider_profile?`<p>审核状态：<span class="status ${d.provider_profile.public_status==='active'?'good':'wait'}">${esc(d.provider_profile.public_status)}</span></p>`:'<p class="muted">尚未提交家政人员资料。</p>'}<p class="small">相关预约 ${bookings.length} 条</p></section>`}catch(e){target.innerHTML='<div class="empty">暂时无法读取服务记录。</div>'}}
  async function viewOffers(id){app.innerHTML=`${top('需求报价')}<div class="loading">正在读取报价...</div>`;try{const rows=await rpc('service_request_offers',{p_request_id:id});app.innerHTML=`${top('需求报价')}<section class="panel"><h2>收到的报价</h2>${rows.length?rows.map(x=>`<div class="offer"><div class="split"><b>${money(x.quoted_amount)}</b><span class="status ${x.status==='accepted'?'good':''}">${esc(x.status)}</span></div><p>${esc(x.message||'')}</p>${x.status==='pending'?`<button class="primary" onclick="Services.acceptOffer('${x.id}')">选择此报价</button>`:''}</div>`).join(''):'<p class="muted">暂时还没有报价。</p>'}</section>`}catch(e){app.innerHTML=`${top('需求报价')}<div class="empty">暂时无法读取报价。</div>`}}
  async function acceptOffer(id){if(!confirm('选择后将关闭其他报价。请通过对方主页私信继续沟通。'))return;try{await rpc('service_accept_offer',{p_offer_id:id});alert('已选择该报价。');state.tab='mine';render()}catch(e){alert('操作失败，请稍后再试。')}}
  async function adminReview(){try{const rows=await rpc('service_admin_homecare_profiles');if(!rows.length)return alert('没有待审核的家政人员资料。');app.innerHTML=`${top('家政审核')}<section class="panel"><div class="notice important">证件文件请在 Supabase 私有 Storage 的 homecare-verification 桶中核验后再操作。文件不会对公众开放。</div>${rows.map(x=>`<div class="offer"><b>${esc(x.display_name)}</b><p class="small">${esc((x.service_types||[]).join('、'))} · 证件：${esc(x.id_document_status)} · 公开状态：${esc(x.public_status)}</p><button class="primary" onclick="Services.review('${x.user_id}','active')">审核通过</button> <button class="danger" onclick="Services.review('${x.user_id}','rejected')">驳回</button></div>`).join('')}</section>`}catch(e){alert('仅管理员可查看家政审核。')}}
  async function review(id,status){const note=prompt(status==='active'?'审核备注（选填）':'驳回原因（将展示给申请人）','')??'';try{await rpc('service_review_homecare_provider',{p_user_id:id,p_status:status,p_note:note});alert('审核状态已更新。');await load()}catch(e){alert('操作失败。')}}
  const val=id=>(document.getElementById(id)?.value||'').trim(),num=id=>{const n=Number(val(id));return Number.isFinite(n)&&n>0?n:null},csv=id=>val(id).split(/[,，]/).map(v=>v.trim()).filter(Boolean);
  window.Services={back,tab:t=>{state.tab=t;renderContent()},requestForm,submitRequest,offerForm,submitOffer,providerForm,submitProvider,bookForm,submitBooking,viewOffers,acceptOffer,adminReview,review};load();
})();
