-- 乐生活 v5.250：点餐订单状态、餐桌删除与消费账单

alter table public.merchant_orders
  drop constraint if exists merchant_orders_status_check;

alter table public.merchant_orders
  add constraint merchant_orders_status_check
  check (status = any (array['pending','confirmed','preparing','reminded','served','completed','cancelled']));

alter table public.merchant_order_tables
  add column if not exists deleted_at timestamptz;

create table if not exists public.merchant_order_bills (
  id bigint generated by default as identity primary key,
  order_id uuid not null unique references public.merchant_orders(id) on delete cascade,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete restrict,
  payment_method text not null check (payment_method in ('cash','card','online')),
  subtotal numeric(12,2) not null default 0,
  discount_amount numeric(12,2) not null default 0,
  tip_amount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  coupon_claim_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists merchant_order_bills_user_created_idx
  on public.merchant_order_bills(user_id, created_at desc);

alter table public.merchant_order_bills enable row level security;

drop policy if exists "Users can view own order bills" on public.merchant_order_bills;
create policy "Users can view own order bills"
  on public.merchant_order_bills for select to authenticated
  using (user_id = auth.uid() or public.merchant_order_can_manage(merchant_user_id));

create or replace function public.merchant_order_delete_table(p_table_id bigint)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  table_row public.merchant_order_tables;
  has_orders boolean;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select * into table_row from public.merchant_order_tables where id = p_table_id for update;
  if not found then raise exception 'table_not_found'; end if;
  if not public.merchant_order_can_manage(table_row.merchant_user_id) then raise exception 'not_order_merchant'; end if;
  select exists(select 1 from public.merchant_orders where table_id = p_table_id) into has_orders;
  if has_orders then
    update public.merchant_order_tables set is_active = false, deleted_at = now(), updated_at = now() where id = p_table_id;
    return 'archived';
  end if;
  delete from public.merchant_order_tables where id = p_table_id;
  return 'deleted';
end;
$$;

create or replace function public.merchant_order_complete_with_bill(
  p_order_id uuid,
  p_payment_method text,
  p_tip_amount numeric default 0,
  p_discount_amount numeric default 0,
  p_coupon_claim_ids jsonb default '[]'::jsonb
)
returns public.merchant_order_bills
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  order_row public.merchant_orders;
  bill_row public.merchant_order_bills;
  subtotal_value numeric(12,2);
  discount_value numeric(12,2);
  tip_value numeric(12,2);
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if p_payment_method not in ('cash','card','online') then raise exception 'invalid_payment_method'; end if;
  select * into order_row from public.merchant_orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if not public.merchant_order_can_manage(order_row.merchant_user_id) then raise exception 'not_order_merchant'; end if;
  select * into bill_row from public.merchant_order_bills where order_id = p_order_id;
  if found then return bill_row; end if;
  subtotal_value := greatest(coalesce(order_row.subtotal, 0), 0);
  discount_value := least(greatest(coalesce(p_discount_amount, 0), 0), subtotal_value);
  tip_value := greatest(coalesce(p_tip_amount, 0), 0);
  update public.merchant_orders set status = 'completed', updated_at = now() where id = p_order_id;
  insert into public.merchant_order_bills(order_id, merchant_user_id, user_id, payment_method, subtotal, discount_amount, tip_amount, total_amount, coupon_claim_ids)
  values (p_order_id, order_row.merchant_user_id, order_row.user_id, p_payment_method, subtotal_value, discount_value, tip_value, subtotal_value - discount_value + tip_value, coalesce(p_coupon_claim_ids, '[]'::jsonb))
  returning * into bill_row;
  return bill_row;
end;
$$;

revoke all on function public.merchant_order_delete_table(bigint) from public;
grant execute on function public.merchant_order_delete_table(bigint) to authenticated;
revoke all on function public.merchant_order_complete_with_bill(uuid,text,numeric,numeric,jsonb) from public;
grant execute on function public.merchant_order_complete_with_bill(uuid,text,numeric,numeric,jsonb) to authenticated;

create or replace function public.merchant_order_remind(p_order_id uuid)
returns public.merchant_orders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  order_row public.merchant_orders;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select * into order_row from public.merchant_orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if order_row.user_id <> auth.uid() then raise exception 'not_order_customer'; end if;
  if order_row.status in ('completed','cancelled','served') then raise exception 'order_not_remindable'; end if;
  update public.merchant_orders set status = 'reminded', updated_at = now() where id = p_order_id returning * into order_row;
  return order_row;
end;
$$;

revoke all on function public.merchant_order_remind(uuid) from public;
grant execute on function public.merchant_order_remind(uuid) to authenticated;
