create table if not exists public.merchant_memberships (
  id bigint generated by default as identity primary key,
  merchant_user_id uuid not null,
  user_id uuid not null,
  user_name text,
  user_avatar text,
  status text not null default 'active',
  points integer not null default 0,
  stamp_count integer not null default 0,
  joined_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint merchant_memberships_status_check check (status in ('active', 'paused', 'blocked')),
  constraint merchant_memberships_unique_user unique (merchant_user_id, user_id)
);

alter table public.merchant_memberships enable row level security;

create index if not exists merchant_memberships_merchant_idx
  on public.merchant_memberships (merchant_user_id, status, joined_at desc);

create index if not exists merchant_memberships_user_idx
  on public.merchant_memberships (user_id, status, joined_at desc);

grant select on public.merchant_memberships to anon;
grant select, insert, update, delete on public.merchant_memberships to authenticated;
grant usage, select on sequence public.merchant_memberships_id_seq to authenticated;

drop policy if exists "merchant memberships active rows are readable" on public.merchant_memberships;
create policy "merchant memberships active rows are readable"
on public.merchant_memberships
for select
to anon, authenticated
using (status = 'active');

drop policy if exists "users can join merchant memberships" on public.merchant_memberships;
create policy "users can join merchant memberships"
on public.merchant_memberships
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "users and merchants can update memberships" on public.merchant_memberships;
create policy "users and merchants can update memberships"
on public.merchant_memberships
for update
to authenticated
using ((select auth.uid()) = user_id or (select auth.uid()) = merchant_user_id)
with check ((select auth.uid()) = user_id or (select auth.uid()) = merchant_user_id);

drop policy if exists "users and merchants can delete memberships" on public.merchant_memberships;
create policy "users and merchants can delete memberships"
on public.merchant_memberships
for delete
to authenticated
using ((select auth.uid()) = user_id or (select auth.uid()) = merchant_user_id);
