(() => {
  const SUPABASE_URL='https://ptxdxepmggmjcndgukjk.supabase.co';
  const SUPABASE_KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app=document.getElementById('autoApp');
  const query=new URLSearchParams(location.search);
  const state={merchant:null,listings:[],tab:'buy',screen:'list',selected:null,sellPhotos:[],savedIds:new Set(),compareIds:new Set(),filters:{type:'',fuel:'',price:''}};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>`$${Number(v||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0})}`;
  const tr=key=>window.LeshenghuoI18n?.t?.(key)||key;
  const session=()=>{try{return JSON.parse(localStorage.getItem('wanba_session')||'null')}catch(e){return null}};
  let refreshInFlight=null;
  async function refreshSession(){const current=session();if(!current?.refresh_token)return false;if(!refreshInFlight)refreshInFlight=fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:current.refresh_token})}).then(async response=>{if(!response.ok)return false;const next=await response.json();if(!next?.access_token)return false;localStorage.setItem('wanba_session',JSON.stringify({...current,...next,user:next.user||current.user}));return true}).catch(()=>false).finally(()=>{refreshInFlight=null});return refreshInFlight}
  async function api(path,options={}){const request=()=>fetch(SUPABASE_URL+path,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session()?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});let response=await request();if(response.status===401&&await refreshSession())response=await request();return response}
  const top=title=>`<header class="top"><button onclick="Auto.back()" aria-label="返回">‹</button><b>${esc(title)}</b><span><button onclick="Auto.close()" aria-label="关闭">×</button></span></header>`;
  const exit=()=>{if(window.parent!==window){window.parent.postMessage({type:'leshenghuo-close-auto'},'*');return}location.assign('/');};
  const photo=car=>Array.isArray(car?.photos)&&car.photos[0]?`<img src="${esc(car.photos[0])}" alt="">`:'<div class="placeholder">🚘</div>';
  const filtered=()=>state.listings.filter(car=>(!state.filters.type||car.vehicle_type===state.filters.type)&&(!state.filters.fuel||car.fuel_type===state.filters.fuel)&&(!state.filters.price||Number(car.price||0)<=Number(state.filters.price)));
  function renderList(){const cars=filtered();app.innerHTML=`${top('二手车买卖')}<section class="hero"><h1>${esc(state.merchant?.business_name||'乐生活二手车')}</h1><p>透明展示车辆信息；可预约试驾，也可以提交自己的车获得报价。</p></section><div class="tabs"><button class="${state.tab==='buy'?'on':''}" onclick="Auto.buy()">买车</button><button class="${state.tab==='sell'?'on':''}" onclick="Auto.sell()">卖车估价</button></div>${state.tab==='sell'?sellHtml():buyHtml(cars)}`;}
  function buyHtml(cars){return `<section class="filters"><select onchange="Auto.filter('type',this.value)"><option value="">全部车型</option>${['轿车','SUV','VAN','皮卡','跑车','其他'].map(v=>`<option ${state.filters.type===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('fuel',this.value)"><option value="">全部能源</option>${['汽油','柴油','混动','纯电'].map(v=>`<option ${state.filters.fuel===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('price',this.value)"><option value="">全部价格</option><option value="10000">$10,000 以下</option><option value="20000">$20,000 以下</option><option value="30000">$30,000 以下</option><option value="50000">$50,000 以下</option></select></section><div class="count">找到 <b>${cars.length}</b> 辆可售车辆</div><section class="cards">${cars.length?cars.map(car=>`<button class="car-card" onclick="Auto.open('${esc(car.id)}')">${photo(car)}<div><span class="chip">${esc(car.vehicle_type||'车辆')}</span>${car.is_certified?'<span class="chip">认证车况</span>':''}<h2>${esc(car.title)}</h2><p>${esc([car.year,car.mileage?`${Number(car.mileage).toLocaleString()} mi`:'里程待补充',car.fuel_type,car.transmission].filter(Boolean).join(' · '))}</p><strong class="price">${money(car.price)}</strong></div></button>`).join(''):'<div class="empty">暂无符合条件的车辆。</div>'}</section>`;}
  function sellHtml(){return `<section class="section"><h2>出售你的车</h2><p>留下准确资料和清晰照片，商家会更快联系你确认车况并提供报价。提交不会构成买卖合同。</p></section><section class="form"><label class="field">姓名<input id="leadName" maxlength="80" value="${esc(session()?.user?.user_metadata?.display_name||'')}" placeholder="姓名（必填）"></label><label class="field">联系电话<input id="leadPhone" maxlength="40" inputmode="tel" placeholder="电话（必填）"></label><div class="lead-actions"><label class="field">品牌<input id="sellMake" maxlength="50" placeholder="例如 Toyota"></label><label class="field">车型<input id="sellModel" maxlength="50" placeholder="例如 Camry"></label><label class="field">年份<input id="sellYear" inputmode="numeric" type="number" min="1900" max="2100" placeholder="例如 2021"></label><label class="field">里程<input id="sellMileage" inputmode="numeric" type="number" min="0" placeholder="英里（必填）"></label><label class="field">车型<select id="sellType"><option>轿车</option><option>SUV</option><option>VAN</option><option>皮卡</option><option>跑车</option><option>其他</option></select></label><label class="field">能源<select id="sellFuel"><option>汽油</option><option>柴油</option><option>混动</option><option>纯电</option></select></label><label class="field">变速箱<select id="sellTransmission"><option>自动挡</option><option>手动挡</option><option>其他</option></select></label><label class="field">期望售价（可选）<input id="sellExpectedPrice" type="number" min="0" inputmode="decimal" placeholder="美元"></label></div><label class="field">VIN 后六位（可选）<input id="sellVinLast6" maxlength="6" placeholder="仅用于商家初步核对"></label><label class="field">车辆情况<textarea id="sellMessage" maxlength="1500" placeholder="可补充事故记录、保养情况、改装或其他需要说明的情况"></textarea></label><label class="field">车辆照片（最多 8 张）<input id="sellPhotos" type="file" accept="image/*" multiple onchange="Auto.uploadSellPhotos(this.files)"></label><div class="sell-photo-list">${state.sellPhotos.map((url,index)=>`<div><img src="${esc(url)}" alt="车辆照片"><button type="button" onclick="Auto.removeSellPhoto(${index})">×</button></div>`).join('')}</div><div class="notice">图片会压缩后上传。建议提供车头、车尾、两侧、内饰、仪表盘和车况细节。</div><button class="primary" onclick="Auto.submitSell()">提交车辆，获取报价</button></section>`;}
  function sellHtml(){return `<section class="section"><h2>出售你的车</h2><p>请填写完整 17 位 VIN。商家可据此提取车辆历史报告，VIN 不会在公开页面展示。</p></section><section class="form"><label class="field">姓名<input id="leadName" maxlength="80" value="${esc(session()?.user?.user_metadata?.display_name||'')}" placeholder="姓名（必填）"></label><label class="field">联系电话<input id="leadPhone" maxlength="40" inputmode="tel" placeholder="电话（必填）"></label><div class="lead-actions"><label class="field">品牌<input id="sellMake" maxlength="50" placeholder="例如 Toyota"></label><label class="field">车型<input id="sellModel" maxlength="50" placeholder="例如 Camry"></label><label class="field">年份<input id="sellYear" inputmode="numeric" type="number" min="1900" max="2100" placeholder="例如 2021"></label><label class="field">里程<input id="sellMileage" inputmode="numeric" type="number" min="0" placeholder="英里（必填）"></label><label class="field">车型<select id="sellType"><option>轿车</option><option>SUV</option><option>VAN</option><option>皮卡</option><option>跑车</option><option>其他</option></select></label><label class="field">能源<select id="sellFuel"><option>汽油</option><option>柴油</option><option>混动</option><option>纯电</option></select></label><label class="field">变速箱<select id="sellTransmission"><option>自动挡</option><option>手动挡</option><option>其他</option></select></label><label class="field">期望售价（可选）<input id="sellExpectedPrice" type="number" min="0" inputmode="decimal" placeholder="美元"></label></div><label class="field">车辆识别码 VIN<input id="sellVin" maxlength="17" autocapitalize="characters" spellcheck="false" placeholder="17 位 VIN（必填）"></label><label class="field">车辆情况<textarea id="sellMessage" maxlength="1500" placeholder="可补充事故记录、保养情况、改装或其他需要说明的情况"></textarea></label><label class="field">车辆照片（最多 8 张）<input type="file" accept="image/*" multiple onchange="Auto.uploadSellPhotos(this.files)"></label><div class="sell-photo-list">${state.sellPhotos.map((url,index)=>`<div><img src="${esc(url)}" alt="车辆照片"><button type="button" onclick="Auto.removeSellPhoto(${index})">×</button></div>`).join('')}</div><div class="notice">图片会压缩后上传。建议提供车头、车尾、两侧、内饰、仪表盘和车况细节。</div><button class="primary" onclick="Auto.submitSell()">提交车辆，获取报价</button></section>`;}
  async function loadQuotes(){if(!session()?.user){alert('请先登录后查看报价记录。');return}try{const response=await api('/rest/v1/rpc/merchant_auto_customer_leads',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id})}),rows=await response.json();if(!response.ok)throw new Error('load_failed');state.quotes=Array.isArray(rows)?rows:[];state.tab='quotes';renderList()}catch(error){alert('暂时无法读取报价记录，请确认已运行 v5.387 数据库更新。')}}
  function quotesHtml(){const rows=Array.isArray(state.quotes)?state.quotes:[];const statusText={new:'已提交',contacted:'商家已联系',scheduled:'已安排',quoted:'已报价',closed:'已完成',archived:'已归档'};return `<section class="section"><h2>我的估价与试驾</h2><p>这里显示你在这家商家提交过的卖车估价、车辆咨询和试驾申请。</p></section><section class="cards">${rows.length?rows.map(row=>`<div class="car-card" style="grid-template-columns:1fr"><div><span class="chip">${esc(row.lead_type==='sell_quote'?'卖车估价':row.lead_type==='test_drive'?'预约试驾':'车辆咨询')}</span><span class="chip">${esc(statusText[row.status]||row.status)}</span><h2>${esc(row.lead_type==='sell_quote'?[row.vehicle_data?.year,row.vehicle_data?.make,row.vehicle_data?.model].filter(Boolean).join(' ')||'车辆估价':row.listing_title||'车辆咨询')}</h2><p>${row.quoted_amount!==null&&row.quoted_amount!==undefined?`商家报价：${money(row.quoted_amount)}`:'商家尚未填写正式报价'}</p>${row.quote_expires_at?`<p>报价有效至：${esc(new Date(row.quote_expires_at).toLocaleString('zh-CN'))}</p>`:''}${row.merchant_note?`<p>${esc(row.merchant_note)}</p>`:''}</div></div>`).join(''):'<div class="empty">还没有提交记录。</div>'}</section>`;}
  function renderList(){const cars=filtered();app.innerHTML=`${top('二手车买卖')}<section class="hero"><h1>${esc(state.merchant?.business_name||'乐生活二手车')}</h1><p>透明展示车辆信息；可预约试驾，也可以提交自己的车获得报价。</p></section><div class="tabs"><button class="${state.tab==='buy'?'on':''}" onclick="Auto.buy()">买车</button><button class="${state.tab==='sell'?'on':''}" onclick="Auto.sell()">卖车估价</button></div>${session()?.user?`<button class="outline" style="width:100%;margin-top:-7px" onclick="Auto.quotes()">查看我的估价与试驾记录</button>`:''}${state.tab==='quotes'?quotesHtml():state.tab==='sell'?sellHtml():buyHtml(cars)}`;}
  function renderDetail(){const car=state.selected;if(!car)return renderList();app.innerHTML=`${top('车辆详情')}<section>${photo(car).replace('<img ','<img class="detail-image" ').replace('<div class="placeholder">','<div class="detail-image placeholder">')}</section><div class="detail-title"><div><h1>${esc(car.title)}</h1><p>${esc([car.year,car.make,car.model].filter(Boolean).join(' · '))}</p></div><strong>${money(car.price)}</strong></div><div class="specs"><div><b>${esc(car.mileage?`${Number(car.mileage).toLocaleString()} mi`:'—')}</b><span>里程</span></div><div><b>${esc(car.fuel_type||'—')}</b><span>能源</span></div><div><b>${esc(car.transmission||'—')}</b><span>变速箱</span></div><div><b>${esc(car.drivetrain||'—')}</b><span>驱动</span></div><div><b>${esc(car.exterior_color||'—')}</b><span>外观颜色</span></div><div><b>${esc(car.vin_last6?`…${car.vin_last6}`:'—')}</b><span>VIN</span></div></div><section class="section"><h2>车辆说明</h2><p>${esc(car.description||car.condition_note||'商家尚未补充说明。')}</p></section>${Array.isArray(car.features)&&car.features.length?`<section class="section"><h2>配置</h2><div class="feature-list">${car.features.map(v=>`<span>${esc(v)}</span>`).join('')}</div></section>`:''}<button class="primary sticky" onclick="Auto.testDrive()">预约试驾</button>`;}
  function renderLead(type){const car=state.selected;app.innerHTML=`${top(type==='test_drive'?'预约试驾':'咨询车辆')}<section class="section"><h2>${esc(car?.title||'车辆咨询')}</h2><p>${type==='test_drive'?'请选择希望试驾的时间，商家会联系确认。':'留下联系方式，商家会尽快回复。'}</p></section><section class="form"><label class="field">姓名<input id="leadName" maxlength="80" value="${esc(session()?.user?.user_metadata?.display_name||'')}" placeholder="姓名（必填）"></label><label class="field">联系电话<input id="leadPhone" maxlength="40" inputmode="tel" placeholder="电话（必填）"></label><label class="field">希望时间（可选）<input id="leadTime" type="datetime-local"></label><label class="field">留言（可选）<textarea id="leadMessage" maxlength="1500" placeholder="例如：想确认车况、贷款或置换方案"></textarea></label><button class="primary" onclick="Auto.submitLead('${type}')">提交${type==='test_drive'?'试驾申请':'咨询'}</button></section>`;}
  async function submitLead(type){if(!session()?.user){alert('请先登录后提交咨询。');return}const name=document.getElementById('leadName')?.value.trim(),phone=document.getElementById('leadPhone')?.value.trim();if(!name||!phone){alert('请填写姓名和电话。');return}const response=await api('/rest/v1/rpc/merchant_auto_create_lead',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_listing_id:state.selected?.id||null,p_lead_type:type,p_customer_name:name,p_customer_phone:phone,p_customer_email:session().user.email||null,p_message:document.getElementById('leadMessage')?.value.trim()||null,p_vehicle_data:{},p_photos:[],p_preferred_at:document.getElementById('leadTime')?.value?new Date(document.getElementById('leadTime').value).toISOString():null})});if(!response.ok){alert('提交失败，请稍后重试。');return}app.innerHTML=`${top('已提交')}<section class="success"><i>✓</i><h1>商家已收到你的申请</h1><p>商家会通过你填写的电话联系你。你也可以稍后在 Purchase 中查看后续消费与预约记录。</p><button class="primary" onclick="Auto.list()">返回车辆列表</button></section>`;}
  async function resizeImage(file){const source=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(source.width,source.height)),canvas=document.createElement('canvas');canvas.width=Math.round(source.width*scale);canvas.height=Math.round(source.height*scale);canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height);return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));}
  async function uploadSellPhotos(files){if(!session()?.user){alert('请先登录后上传车辆图片。');return}try{for(const file of [...files].slice(0,8-state.sellPhotos.length)){const blob=await resizeImage(file),response=await fetch('https://upload.escoopcity.com/upload',{method:'POST',headers:{Authorization:`Bearer ${session()?.access_token||''}`,'Content-Type':'image/jpeg','x-media-kind':'products'},body:blob}),data=await response.json();if(!response.ok||!data.url)throw new Error('upload_failed');state.sellPhotos.push(data.url)}renderList()}catch(error){alert('图片上传失败，请检查网络后重试。')}}
  async function submitSell(){if(!session()?.user){alert('请先登录后提交卖车报价。');return}const name=document.getElementById('leadName')?.value.trim(),phone=document.getElementById('leadPhone')?.value.trim(),make=document.getElementById('sellMake')?.value.trim(),model=document.getElementById('sellModel')?.value.trim(),year=document.getElementById('sellYear')?.value,mileage=document.getElementById('sellMileage')?.value;if(!name||!phone){alert('请填写姓名和电话。');return}if(!make||!model||!year||!mileage){alert('请填写品牌、车型、年份和里程。');return}const data={make,model,year,mileage,vehicle_type:document.getElementById('sellType')?.value||'',fuel_type:document.getElementById('sellFuel')?.value||'',transmission:document.getElementById('sellTransmission')?.value||'',expected_price:document.getElementById('sellExpectedPrice')?.value||'',vin_last6:document.getElementById('sellVinLast6')?.value.trim()||''};const response=await api('/rest/v1/rpc/merchant_auto_create_lead',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_listing_id:null,p_lead_type:'sell_quote',p_customer_name:name,p_customer_phone:phone,p_customer_email:session().user.email||null,p_message:document.getElementById('sellMessage')?.value.trim()||null,p_vehicle_data:data,p_photos:state.sellPhotos,p_preferred_at:null})});if(!response.ok){alert('提交失败，请稍后重试。');return}state.sellPhotos=[];app.innerHTML=`${top('已提交')}<section class="success"><i>✓</i><h1>估价资料已提交</h1><p>商家会先核对车辆资料和图片，再通过电话联系你确认报价。</p><button class="primary" onclick="Auto.sell()">继续提交另一辆车</button></section>`;}
  async function load(){const slug=query.get('merchant');if(!slug){app.innerHTML=`${top('二手车买卖')}<div class="empty">缺少商家信息。</div>`;return}try{const response=await api('/rest/v1/rpc/merchant_auto_public_catalog',{method:'POST',body:JSON.stringify({p_slug:slug})});const data=await response.json();if(!response.ok||!data?.merchant)throw new Error('not_found');state.merchant=data.merchant;state.listings=Array.isArray(data.listings)?data.listings:[];await loadSaved();renderList()}catch(error){app.innerHTML=`${top('二手车买卖')}<div class="empty">暂时无法读取车辆库存，请稍后再试。</div>`;}}
  async function submitSell(){if(!session()?.user){alert('请先登录后提交卖车报价。');return}const get=id=>document.getElementById(id)?.value.trim()||'',name=get('leadName'),phone=get('leadPhone'),make=get('sellMake'),model=get('sellModel'),year=get('sellYear'),mileage=get('sellMileage'),vin=get('sellVin').toUpperCase();if(!name||!phone){alert('请填写姓名和电话。');return}if(!make||!model||!year||!mileage){alert('请填写品牌、车型、年份和里程。');return}if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin)){alert('请填写完整且有效的 17 位 VIN。VIN 不包含 I、O、Q。');return}const vehicle={make,model,year,mileage,vin,vehicle_type:get('sellType'),fuel_type:get('sellFuel'),transmission:get('sellTransmission'),expected_price:get('sellExpectedPrice')};const response=await api('/rest/v1/rpc/merchant_auto_create_sell_quote',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_customer_name:name,p_customer_phone:phone,p_customer_email:session().user.email||null,p_message:get('sellMessage')||null,p_vehicle_data:vehicle,p_photos:state.sellPhotos})});if(!response.ok){let detail='';try{detail=(await response.json()).message||''}catch(error){}alert(detail==='full_vin_required'?'VIN 格式不正确，请核对后重试。':'提交失败，请确认已运行 v5.388 数据库更新后重试。');return}state.sellPhotos=[];app.innerHTML=`${top('已提交')}<section class="success"><i>✓</i><h1>估价资料已提交</h1><p>商家会先通过 VIN 核对车辆资料和历史信息，再联系你确认报价。</p><button class="primary" onclick="Auto.sell()">继续提交另一辆车</button></section>`;}
  function quotesHtml(){const rows=Array.isArray(state.quotes)?state.quotes:[],statusText={new:'已提交',contacted:'商家已联系',scheduled:'已安排',quoted:'已报价',closed:'已完成',archived:'已归档'};return `<section class="section"><h2>我的估价与试驾</h2><p>这里显示你在这家商家提交过的卖车估价、车辆咨询和试驾申请。</p></section><section class="cards">${rows.length?rows.map(row=>{const testDrive=row.lead_type==='test_drive',title=testDrive?(row.listing_title||'预约试驾'):(row.lead_type==='sell_quote'?[row.vehicle_data?.year,row.vehicle_data?.make,row.vehicle_data?.model].filter(Boolean).join(' ')||'车辆估价':row.listing_title||'车辆咨询'),appointment=testDrive?(row.confirmed_at?`<p><b>确认试驾：</b>${esc(new Date(row.confirmed_at).toLocaleString('zh-CN'))}</p>${row.appointment_location?`<p><b>地点：</b>${esc(row.appointment_location)}</p>`:''}`:row.preferred_at?`<p>希望试驾时间：${esc(new Date(row.preferred_at).toLocaleString('zh-CN'))}</p>`:'<p>等待商家安排试驾时间。</p>'):'';return `<div class="car-card" style="grid-template-columns:1fr"><div><span class="chip">${esc(testDrive?'预约试驾':row.lead_type==='sell_quote'?'卖车估价':'车辆咨询')}</span><span class="chip">${esc(statusText[row.status]||row.status)}</span><h2>${esc(title)}</h2>${appointment}${!testDrive?`<p>${row.quoted_amount!==null&&row.quoted_amount!==undefined?`商家报价：${money(row.quoted_amount)}`:'商家尚未填写正式报价'}</p>${row.quote_expires_at?`<p>报价有效至：${esc(new Date(row.quote_expires_at).toLocaleString('zh-CN'))}</p>`:''}`:''}${row.merchant_note?`<p>${esc(row.merchant_note)}</p>`:''}</div></div>`}).join(''):'<div class="empty">还没有提交记录。</div>'}</section>`;}
  function quotesHtml(){const rows=Array.isArray(state.quotes)?state.quotes:[],statusText={new:'已提交',contacted:'商家已联系',scheduled:'已安排',reschedule_requested:'已申请改期',cancelled:'已取消',quoted:'已报价',closed:'已完成',archived:'已归档'};return `<section class="section"><h2>我的估价与试驾</h2><p>这里显示你在这家商家提交过的卖车估价、车辆咨询和试驾申请。</p></section><section class="cards">${rows.length?rows.map(row=>{const testDrive=row.lead_type==='test_drive',title=testDrive?(row.listing_title||'预约试驾'):(row.lead_type==='sell_quote'?[row.vehicle_data?.year,row.vehicle_data?.make,row.vehicle_data?.model].filter(Boolean).join(' ')||'车辆估价':row.listing_title||'车辆咨询'),appointment=testDrive?(row.confirmed_at?`<p><b>确认试驾：</b>${esc(new Date(row.confirmed_at).toLocaleString('zh-CN'))}</p>${row.appointment_location?`<p><b>地点：</b>${esc(row.appointment_location)}</p>`:''}`:row.preferred_at?`<p>希望试驾时间：${esc(new Date(row.preferred_at).toLocaleString('zh-CN'))}</p>`:'<p>等待商家安排试驾时间。</p>'):'';const action=testDrive&&row.status==='scheduled'?`<div class="lead-actions" style="margin-top:12px"><button class="outline" onclick="Auto.testDriveAction('${esc(row.id)}','reschedule')">申请改期</button><button class="outline" onclick="Auto.testDriveAction('${esc(row.id)}','cancel')">取消试驾</button></div>`:testDrive&&row.customer_action?`<p><b>${row.customer_action==='cancel'?'已提交取消申请':'已提交改期申请'}</b>${row.customer_action_note?`：${esc(row.customer_action_note)}`:''}</p>`:'';return `<div class="car-card" style="grid-template-columns:1fr"><div><span class="chip">${esc(testDrive?'预约试驾':row.lead_type==='sell_quote'?'卖车估价':'车辆咨询')}</span><span class="chip">${esc(statusText[row.status]||row.status)}</span><h2>${esc(title)}</h2>${appointment}${!testDrive?`<p>${row.quoted_amount!==null&&row.quoted_amount!==undefined?`商家报价：${money(row.quoted_amount)}`:'商家尚未填写正式报价'}</p>${row.quote_expires_at?`<p>报价有效至：${esc(new Date(row.quote_expires_at).toLocaleString('zh-CN'))}</p>`:''}`:''}${row.merchant_note?`<p>${esc(row.merchant_note)}</p>`:''}${action}</div></div>`}).join(''):'<div class="empty">还没有提交记录。</div>'}</section>`;}
async function testDriveAction(id,action){if(action==='cancel'&&!confirm(tr('确定要取消这次试驾吗？商家会收到通知。')))return;const note=prompt(tr(action==='cancel'?'可填写取消原因（可选）':'请填写希望改期的时间或说明（可选）'),'');if(note===null)return;const response=await api('/rest/v1/rpc/merchant_auto_customer_update_test_drive',{method:'POST',body:JSON.stringify({p_lead_id:id,p_action:action,p_note:note.trim()||null})});if(!response.ok){alert(tr('操作失败。请确认该试驾仍为已安排状态，并已运行 v5.391 数据库更新。'));return}await loadQuotes();}
  quotesHtml=function(){const rows=Array.isArray(state.quotes)?state.quotes:[],statusText={new:'已提交',contacted:'商家已联系',scheduled:'已安排',reschedule_requested:'已申请改期',cancelled:'已取消',quoted:'等待你确认',quote_accepted:'已接受报价',quote_declined:'已拒绝报价',closed:'已完成',archived:'已归档'};return `<section class="section"><h2>我的估价与试驾</h2><p>这里显示你在这家商家提交过的卖车估价、车辆咨询和试驾申请。</p></section><section class="cards">${rows.length?rows.map(row=>{const testDrive=row.lead_type==='test_drive',sellQuote=row.lead_type==='sell_quote',title=testDrive?(row.listing_title||'预约试驾'):(sellQuote?[row.vehicle_data?.year,row.vehicle_data?.make,row.vehicle_data?.model].filter(Boolean).join(' ')||'车辆估价':row.listing_title||'车辆咨询'),expired=!!(row.quote_expires_at&&new Date(row.quote_expires_at)<new Date()),appointment=testDrive?(row.confirmed_at?`<p><b>确认试驾：</b>${esc(new Date(row.confirmed_at).toLocaleString('zh-CN'))}</p>${row.appointment_location?`<p><b>地点：</b>${esc(row.appointment_location)}</p>`:''}`:row.preferred_at?`<p>希望试驾时间：${esc(new Date(row.preferred_at).toLocaleString('zh-CN'))}</p>`:'<p>等待商家安排试驾时间。</p>'):'';const testActions=testDrive&&row.status==='scheduled'?`<div class="lead-actions" style="margin-top:12px"><button class="outline" onclick="Auto.testDriveAction('${esc(row.id)}','reschedule')">申请改期</button><button class="outline" onclick="Auto.testDriveAction('${esc(row.id)}','cancel')">取消试驾</button></div>`:testDrive&&row.customer_action?`<p><b>${row.customer_action==='cancel'?'已提交取消申请':'已提交改期申请'}</b>${row.customer_action_note?`：${esc(row.customer_action_note)}`:''}</p>`:'';const quoteActions=sellQuote&&row.status==='quoted'&&!row.quote_response?(expired?'<p style="color:#b33"><b>该报价已过期</b></p>':`<div class="lead-actions" style="margin-top:12px"><button class="primary" onclick="Auto.quoteResponse('${esc(row.id)}','accepted')">接受报价</button><button class="outline" onclick="Auto.quoteResponse('${esc(row.id)}','declined')">暂不接受</button></div>`):sellQuote&&row.quote_response?`<p><b>${row.quote_response==='accepted'?'你已接受该报价':'你暂不接受该报价'}</b>${row.quote_responded_at?` · ${esc(new Date(row.quote_responded_at).toLocaleString('zh-CN'))}`:''}</p>`:'';return `<div class="car-card" style="grid-template-columns:1fr"><div><span class="chip">${esc(testDrive?'预约试驾':sellQuote?'卖车估价':'车辆咨询')}</span><span class="chip">${esc(statusText[row.status]||row.status)}</span><h2>${esc(title)}</h2>${appointment}${sellQuote?`<p>${row.quoted_amount!==null&&row.quoted_amount!==undefined?`商家报价：<b>${money(row.quoted_amount)}</b>`:'商家尚未填写正式报价'}</p>${row.quote_expires_at?`<p>报价有效至：${esc(new Date(row.quote_expires_at).toLocaleString('zh-CN'))}</p>`:''}`:''}${row.merchant_note?`<p>${esc(row.merchant_note)}</p>`:''}${testActions}${quoteActions}</div></div>`}).join(''):'<div class="empty">还没有提交记录。</div>'}</section>`;};
  async function quoteResponse(id,response){const accept=response==='accepted';if(!confirm(accept?'确认接受这份报价吗？商家会联系你安排下一步。':'确认暂不接受这份报价吗？'))return;const result=await api('/rest/v1/rpc/merchant_auto_customer_respond_quote',{method:'POST',body:JSON.stringify({p_lead_id:id,p_response:response})});if(!result.ok){let message='操作失败，请稍后重试。';try{const detail=await result.json();if(detail.message==='quote_expired')message='该报价已过期，请联系商家重新报价。';}catch(error){}alert(message);return}await loadQuotes();}
  async function loadSaved(){if(!session()?.user||!state.merchant?.user_id){state.savedIds=new Set();return}const response=await api(`/rest/v1/merchant_auto_saved_listings?select=listing_id&merchant_user_id=eq.${encodeURIComponent(state.merchant.user_id)}`,{method:'GET'});if(response.ok){const rows=await response.json();state.savedIds=new Set((Array.isArray(rows)?rows:[]).map(row=>String(row.listing_id)))}}
  async function toggleSaved(id){const current=session();if(!current?.user){alert('请先登录后收藏车辆。');return}const listingId=String(id),saved=state.savedIds.has(listingId),path=saved?`/rest/v1/merchant_auto_saved_listings?user_id=eq.${encodeURIComponent(current.user.id)}&listing_id=eq.${encodeURIComponent(id)}`:'/rest/v1/merchant_auto_saved_listings',response=await api(path,{method:saved?'DELETE':'POST',headers:saved?{}:{Prefer:'return=minimal'},body:saved?undefined:JSON.stringify({user_id:current.user.id,listing_id:id,merchant_user_id:state.merchant.user_id})});if(!response.ok){alert('收藏操作失败，请稍后重试。');return}if(saved)state.savedIds.delete(listingId);else state.savedIds.add(listingId);state.savedIds=new Set(state.savedIds);if(state.screen==='detail')renderDetail();else renderList()}
  buyHtml=function(cars){return `<section class="filters"><select onchange="Auto.filter('type',this.value)"><option value="">全部车型</option>${['轿车','SUV','VAN','皮卡','跑车','其他'].map(v=>`<option ${state.filters.type===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('fuel',this.value)"><option value="">全部能源</option>${['汽油','柴油','混动','纯电'].map(v=>`<option ${state.filters.fuel===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('price',this.value)"><option value="">全部价格</option><option value="10000">$10,000 以下</option><option value="20000">$20,000 以下</option><option value="30000">$30,000 以下</option><option value="50000">$50,000 以下</option></select></section><div class="count">找到 <b>${cars.length}</b> 辆可售车辆</div><section class="cards">${cars.length?cars.map(car=>{const saved=state.savedIds.has(String(car.id));return `<article class="car-card saved-card"><button class="car-main" onclick="Auto.open('${esc(car.id)}')">${photo(car)}<div><span class="chip">${esc(car.vehicle_type||'车辆')}</span>${car.is_certified?'<span class="chip">认证车况</span>':''}<h2>${esc(car.title)}</h2><p>${esc([car.year,car.mileage?`${Number(car.mileage).toLocaleString()} mi`:'里程待补充',car.fuel_type,car.transmission].filter(Boolean).join(' · '))}</p><strong class="price">${money(car.price)}</strong></div></button><button class="save-button ${saved?'saved':''}" aria-label="${saved?'取消收藏':'收藏车辆'}" onclick="Auto.toggleSaved('${esc(car.id)}')">${saved?'♥':'♡'}</button></article>`}).join(''):'<div class="empty">暂无符合条件的车辆。</div>'}</section>`;};
  renderList=function(){const cars=state.tab==='saved'?state.listings.filter(car=>state.savedIds.has(String(car.id))):filtered();app.innerHTML=`${top('二手车买卖')}<section class="hero"><h1>${esc(state.merchant?.business_name||'乐生活二手车')}</h1><p>透明展示车辆信息；可预约试驾，也可以提交自己的车获得报价。</p></section><div class="tabs auto-tabs"><button class="${state.tab==='buy'?'on':''}" onclick="Auto.buy()">买车</button><button class="${state.tab==='sell'?'on':''}" onclick="Auto.sell()">卖车估价</button><button class="${state.tab==='saved'?'on':''}" onclick="Auto.saved()">收藏 ${state.savedIds.size}</button></div>${session()?.user?`<button class="outline" style="width:100%;margin-top:-7px" onclick="Auto.quotes()">查看我的估价与试驾记录</button>`:''}${state.tab==='quotes'?quotesHtml():state.tab==='sell'?sellHtml():buyHtml(cars)}`;};
  const renderAutoDetailBase=renderDetail;
  renderDetail=function(){renderAutoDetailBase();const title=app.querySelector('.detail-title');if(!title)return;const saved=state.savedIds.has(String(state.selected?.id));title.insertAdjacentHTML('beforeend',`<button class="outline detail-save ${saved?'saved':''}" onclick="Auto.toggleSaved('${esc(state.selected?.id||'')}')">${saved?'♥ 已收藏':'♡ 收藏车辆'}</button>`);};
  const renderAutoListWithSaved = renderList;
  renderList=function(){renderAutoListWithSaved();if(!session()?.user)return;const tabs=app.querySelector('.auto-tabs');if(tabs&&!app.querySelector('#autoMineEntry'))tabs.insertAdjacentHTML('afterend','<button id="autoMineEntry" class="outline" style="width:100%;margin-top:-7px" onclick="Auto.myVehicles()">我的车辆：收藏、估价与试驾</button>');};
  const quotesHtmlWithArrivalBase=quotesHtml;
  quotesHtml=function(){const rows=Array.isArray(state.quotes)?state.quotes:[],statusText={new:'已提交',contacted:'商家已联系',scheduled:'已安排',arrived:'已确认到店',reschedule_requested:'已申请改期',cancelled:'已取消',quoted:'等待你确认',quote_accepted:'已接受报价',quote_declined:'已拒绝报价',closed:'已完成',archived:'已归档'};return `<section class="section"><h2>我的估价与试驾</h2><p>这里显示你的估价、试驾和咨询进度。</p></section><section class="cards">${rows.length?rows.map(row=>{const testDrive=row.lead_type==='test_drive',title=testDrive?(row.listing_title||'预约试驾'):(row.lead_type==='sell_quote'?[row.vehicle_data?.year,row.vehicle_data?.make,row.vehicle_data?.model].filter(Boolean).join(' ')||'车辆估价':row.listing_title||'车辆咨询'),schedule=testDrive?(row.confirmed_at?`<p><b>确认试驾：</b>${esc(new Date(row.confirmed_at).toLocaleString('zh-CN'))}</p>${row.appointment_location?`<p><b>地点：</b>${esc(row.appointment_location)}</p>`:''}`:row.preferred_at?`<p>希望时间：${esc(new Date(row.preferred_at).toLocaleString('zh-CN'))}</p>`:'等待商家安排时间。'):'';const arrival=testDrive&&row.status==='scheduled'?`<div class="lead-actions"><button class="primary" onclick="Auto.confirmArrival('${esc(row.id)}')">确认已到店</button><button class="outline" onclick="Auto.testDriveAction('${esc(row.id)}','cancel')">取消预约</button></div>`:testDrive&&row.status==='arrived'?'<p><b style="color:#315a40">已通知商家你已到店。</b></p>':'';return `<article class="car-card" style="grid-template-columns:1fr"><div><span class="chip">${esc(testDrive?'预约试驾':row.lead_type==='sell_quote'?'卖车估价':'车辆咨询')}</span><span class="chip">${esc(statusText[row.status]||row.status)}</span><h2>${esc(title)}</h2>${schedule}${row.merchant_note?`<p>${esc(row.merchant_note)}</p>`:''}${arrival}</div></article>`}).join(''):'<div class="empty">还没有提交记录。</div>'}</section>`;};
  async function confirmArrival(id){if(!confirm('确认你已经到达试驾地点吗？商家会立即看到此状态。'))return;const response=await api('/rest/v1/rpc/merchant_auto_customer_confirm_test_drive',{method:'POST',body:JSON.stringify({p_lead_id:id})});if(!response.ok){alert('暂时无法确认到店，请检查预约状态后重试。');return;}await loadQuotes();}
  const buyHtmlWithVehicleDetails=buyHtml;
  buyHtml=function(cars){
    const content=buyHtmlWithVehicleDetails(cars);
    const compareBar=state.compareIds.size?`<section class="auto-compare-bar"><span>已选 ${state.compareIds.size}/3 辆</span>${state.compareIds.size>=2?'<button class="primary" onclick="Auto.compare()">对比车辆</button>':'<span>再选一辆即可对比</span>'}<button class="outline" onclick="Auto.clearCompare()">清空</button></section>`:'';
    const wrapped=content.replace(/<\/article>/g,(closing,offset,source)=>{
      const prior=source.slice(0,offset);
      const matches=[...prior.matchAll(/Auto\.open\('([^']+)'\)/g)];
      const id=matches[matches.length-1]?.[1]||'';
      if(!id)return closing;
      const checked=state.compareIds.has(String(id));
      const disabled=!checked&&state.compareIds.size>=3;
      return `<button class="compare-toggle ${checked?'on':''}" ${disabled?'disabled':''} onclick="Auto.toggleCompare('${esc(id)}')">${checked?'✓ 已选对比':'＋ 对比'}</button>${closing}`;
    });
    return compareBar+wrapped;
  };
  const renderAutoDetailWithDetails=renderDetail;
  renderDetail=function(){
    renderAutoDetailWithDetails();
    const car=state.selected;
    if(!car||document.getElementById('autoVehicleDetails'))return;
    const detail=document.querySelector('.detail-title');
    if(!detail)return;
    const cell=(name,value)=>`<div><span>${esc(name)}</span><b>${esc(value||'商家未提供')}</b></div>`;
    const report=car.vehicle_report_url?`<a class="outline report-link" href="${esc(car.vehicle_report_url)}" target="_blank" rel="noopener">查看车况报告 / PDF</a>`:'<p class="auto-muted">商家暂未提供第三方车况报告。</p>';
    detail.insertAdjacentHTML('afterend',`<section id="autoVehicleDetails" class="section auto-vehicle-details"><h2>车辆资料</h2><div class="vehicle-facts">${cell('事故记录',car.accident_history)}${cell('保养记录',car.service_history)}${cell('过户次数',car.owner_count===null||car.owner_count===undefined?'':`${car.owner_count} 次`)}${cell('产权状态',car.title_status)}${cell('保修状态',car.warranty_status)}</div>${report}</section><section class="section loan-tool"><h2>贷款月供估算</h2><p>仅供预算参考，实际年利率、税费与贷款审批以金融机构为准。</p><div class="loan-fields"><label>首付<input id="autoLoanDown" inputmode="decimal" type="number" min="0" value="${Math.round(Number(car.price||0)*.2)}" oninput="Auto.updateLoan()"></label><label>年利率<input id="autoLoanApr" inputmode="decimal" type="number" min="0" max="99" step="0.1" value="7.2" oninput="Auto.updateLoan()"></label><label>期限<select id="autoLoanMonths" onchange="Auto.updateLoan()"><option value="36">36 个月</option><option value="48">48 个月</option><option value="60" selected>60 个月</option><option value="72">72 个月</option></select></label></div><div class="loan-result">预计月供 <b id="autoLoanPayment">—</b><span id="autoLoanPrincipal"></span></div></section>`);
    updateLoan();
  };
  function updateLoan(){
    const price=Number(state.selected?.price||0),down=Math.max(0,Number(document.getElementById('autoLoanDown')?.value||0)),apr=Math.max(0,Number(document.getElementById('autoLoanApr')?.value||0)),months=Math.max(1,Number(document.getElementById('autoLoanMonths')?.value||60)),principal=Math.max(0,price-down),rate=apr/1200,payment=rate===0?principal/months:principal*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1),target=document.getElementById('autoLoanPayment'),meta=document.getElementById('autoLoanPrincipal');
    if(target)target.textContent=money(payment);
    if(meta)meta.textContent=`贷款本金约 ${money(principal)} · ${months} 期`;
  }
  function toggleCompare(id){
    const key=String(id);
    if(state.compareIds.has(key))state.compareIds.delete(key);
    else if(state.compareIds.size<3)state.compareIds.add(key);
    else {alert('最多可同时对比 3 辆车。');return;}
    state.compareIds=new Set(state.compareIds);renderList();
  }
  function clearCompare(){state.compareIds=new Set();renderList();}
  function compareView(){
    const cars=state.listings.filter(car=>state.compareIds.has(String(car.id)));
    if(cars.length<2){alert('至少选择两辆车后再对比。');state.screen='list';return renderList();}
    const row=(label,key,format=value=>value||'—')=>`<div class="compare-row"><b>${esc(label)}</b>${cars.map(car=>`<span>${esc(format(car[key]))}</span>`).join('')}</div>`;
    app.innerHTML=`${top('车辆对比')}<section class="compare-grid"><div class="compare-row compare-head"><b>项目</b>${cars.map(car=>`<span><strong>${esc(car.title)}</strong><button class="outline" onclick="Auto.open('${esc(car.id)}')">查看详情</button></span>`).join('')}</div>${row('售价','price',money)}${row('年份','year')}${row('里程','mileage',value=>value?`${Number(value).toLocaleString()} mi`:'—')}${row('车型','vehicle_type')}${row('能源','fuel_type')}${row('变速箱','transmission')}${row('驱动','drivetrain')}${row('事故记录','accident_history')}${row('过户次数','owner_count',value=>value===null||value===undefined?'—':`${value} 次`)}${row('产权状态','title_status')}${row('保修状态','warranty_status')}</section><button class="outline" style="width:100%;margin-top:15px" onclick="Auto.clearCompare()">清空对比</button>`;
  }
  // Keep the public controls in one place. Earlier versions layered card renderers
  // but left several inline handlers pointing at functions that no longer existed.
  function openVehicle(event,id){
    event?.preventDefault();
    event?.stopPropagation();
    const car=state.listings.find(item=>String(item.id)===String(id));
    if(!car){alert('暂时找不到这辆车，请刷新后重试。');return;}
    state.selected=car;
    state.screen='detail';
    renderDetail();
    window.scrollTo({top:0,behavior:'instant'});
  }
  async function toggleFavorite(event,id){
    event?.preventDefault();
    event?.stopPropagation();
    await toggleSaved(id);
  }
  function toggleCompareCard(event,id){
    event?.preventDefault();
    event?.stopPropagation();
    toggleCompare(id);
  }
  function myVehicles(){location.assign(`/autos/mine/?v=5.405&refresh_t=${Date.now()}`);}
  function renderCompareView(){
    const cars=state.listings.filter(car=>state.compareIds.has(String(car.id)));
    if(cars.length<2){alert('至少选择两辆车后再对比。');state.screen='list';return renderList();}
    const row=(label,key,format=value=>value||'—')=>`<div class="compare-row"><b>${esc(label)}</b>${cars.map(car=>`<span>${esc(format(car[key]))}</span>`).join('')}</div>`;
    app.innerHTML=`${top('车辆对比')}<p class="compare-hint">左右滑动即可查看全部车辆和参数。</p><section class="compare-scroll"><section class="compare-grid" style="--compare-count:${cars.length}"><div class="compare-row compare-head"><b>项目</b>${cars.map(car=>`<span><strong>${esc(car.title)}</strong><button class="outline" type="button" onclick="Auto.openVehicle(event,'${esc(car.id)}')">查看详情</button></span>`).join('')}</div>${row('售价','price',money)}${row('年份','year')}${row('里程','mileage',value=>value?`${Number(value).toLocaleString()} mi`:'—')}${row('车型','vehicle_type')}${row('能源','fuel_type')}${row('变速箱','transmission')}${row('驱动','drivetrain')}${row('事故记录','accident_history')}${row('过户次数','owner_count',value=>value===null||value===undefined?'—':`${value} 次`)}${row('产权状态','title_status')}${row('保修状态','warranty_status')}</section></section><button class="outline" type="button" style="width:100%;margin-top:15px" onclick="Auto.clearCompare()">清空对比</button>`;
  }
  const legacyRenderList=renderList;
  renderList=function(){
    legacyRenderList();
    if(session()?.user){
      const oldMine=document.getElementById('autoMineEntry');
      const oldQuotes=[...app.querySelectorAll('button')].find(button=>button.textContent.includes('查看我的估价与试驾记录'));
      const existing=document.getElementById('autoAccountActions');
      if(!existing&&(oldMine||oldQuotes)){
        const actions=document.createElement('section');
        actions.id='autoAccountActions';
        actions.className='auto-account-actions';
        actions.innerHTML='<button class="outline" type="button" onclick="Auto.myVehicles()">我的车辆</button><button class="outline" type="button" onclick="Auto.quotes()">估价与试驾</button>';
        (oldMine||oldQuotes).replaceWith(actions);
        if(oldMine&&oldMine!==actions)oldMine.remove();
        if(oldQuotes&&oldQuotes!==actions)oldQuotes.remove();
      }
    }
    document.getElementById('autoCompareFab')?.remove();
    if(state.screen==='list'&&state.compareIds.size>=2){
      const fab=document.createElement('div');
      fab.id='autoCompareFab';
      fab.className='auto-compare-fab';
      fab.innerHTML=`<button class="primary" type="button" onclick="Auto.compare()">对比 ${state.compareIds.size} 辆车</button>`;
      document.body.appendChild(fab);
    }
  };
  buyHtml=function(cars){
    const compareBar=state.compareIds.size?`<section class="auto-compare-bar"><span>已选 ${state.compareIds.size}/3 辆</span><span>${state.compareIds.size>=2?'可直接点击底部对比':'再选一辆即可对比'}</span><button class="outline" type="button" onclick="Auto.clearCompare()">清空</button></section>`:'';
    const filters=`<section class="filters"><select onchange="Auto.filter('type',this.value)"><option value="">全部车型</option>${['轿车','SUV','VAN','皮卡','跑车','其他'].map(v=>`<option ${state.filters.type===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('fuel',this.value)"><option value="">全部能源</option>${['汽油','柴油','混动','纯电'].map(v=>`<option ${state.filters.fuel===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('price',this.value)"><option value="">全部价格</option><option value="10000">$10,000 以下</option><option value="20000">$20,000 以下</option><option value="30000">$30,000 以下</option><option value="50000">$50,000 以下</option></select></section>`;
    const cards=cars.length?cars.map(car=>{
      const id=esc(car.id),saved=state.savedIds.has(String(car.id)),checked=state.compareIds.has(String(car.id)),disabled=!checked&&state.compareIds.size>=3;
      return `<article class="car-card saved-card"><button type="button" class="car-main" onclick="Auto.openVehicle(event,'${id}')">${photo(car)}<div><span class="chip">${esc(car.vehicle_type||'车辆')}</span>${car.is_certified?'<span class="chip">认证车况</span>':''}<h2>${esc(car.title)}</h2><p>${esc([car.year,car.mileage?`${Number(car.mileage).toLocaleString()} mi`:'里程待补充',car.fuel_type,car.transmission].filter(Boolean).join(' · '))}</p><strong class="price">${money(car.price)}</strong></div></button><div class="auto-card-actions"><button class="compare-toggle ${checked?'on':''}" type="button" ${disabled?'disabled':''} onclick="Auto.toggleCompareCard(event,'${id}')">${checked?'✓ 已选对比':'＋ 对比'}</button><button class="save-button ${saved?'saved':''}" type="button" aria-label="${saved?'取消收藏':'收藏车辆'}" onclick="Auto.toggleFavorite(event,'${id}')">${saved?'♥ 已收藏':'♡ 收藏'}</button></div></article>`;
    }).join(''):'<div class="empty">暂无符合条件的车辆。</div>';
    return `${compareBar}${filters}<div class="count">找到 <b>${cars.length}</b> 辆可售车辆</div><section class="cards">${cards}</section>`;
  };
  window.Auto={...window.Auto,
    close:exit,
    list(){state.tab='buy';state.screen='list';renderList();},
    buy(){state.tab='buy';state.screen='list';renderList();},
    sell(){state.tab='sell';state.screen='list';renderList();},
    saved(){state.tab='saved';state.screen='list';renderList();},
    filter(key,value){state.filters[key]=value;state.screen='list';renderList();},
    open(id){openVehicle(null,id);},openVehicle,toggleFavorite,toggleCompareCard,
    toggleSaved,uploadSellPhotos,removeSellPhoto(index){state.sellPhotos.splice(index,1);renderList();},
    submitSell,testDrive(){state.screen='lead';renderLead('test_drive');},submitLead,
    quotes:loadQuotes,myVehicles,testDriveAction,quoteResponse,confirmArrival,
    updateLoan,toggleCompare,clearCompare,compare(){state.screen='compare';renderCompareView();},
    back(){document.getElementById('autoCompareFab')?.remove();if(state.screen==='detail'||state.screen==='lead'||state.screen==='compare'){state.screen='list';renderList()}else exit()}
  };
  load();
})();
