(() => {
  const SUPABASE_URL='https://ptxdxepmggmjcndgukjk.supabase.co';
  const SUPABASE_KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app=document.getElementById('autoApp');
  const query=new URLSearchParams(location.search);
  const state={merchant:null,listings:[],tab:'buy',screen:'list',selected:null,filters:{type:'',fuel:'',price:''}};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>`$${Number(v||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0})}`;
  const session=()=>{try{return JSON.parse(localStorage.getItem('wanba_session')||'null')}catch(e){return null}};
  const api=(path,options={})=>fetch(SUPABASE_URL+path,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session()?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});
  const top=title=>`<header class="top"><button onclick="Auto.back()" aria-label="返回">‹</button><b>${esc(title)}</b><span><button onclick="Auto.close()" aria-label="关闭">×</button></span></header>`;
  const exit=()=>{if(window.parent!==window){window.parent.postMessage({type:'leshenghuo-close-auto'},'*');return}location.assign('/');};
  const photo=car=>Array.isArray(car?.photos)&&car.photos[0]?`<img src="${esc(car.photos[0])}" alt="">`:'<div class="placeholder">🚘</div>';
  const filtered=()=>state.listings.filter(car=>(!state.filters.type||car.vehicle_type===state.filters.type)&&(!state.filters.fuel||car.fuel_type===state.filters.fuel)&&(!state.filters.price||Number(car.price||0)<=Number(state.filters.price)));
  function renderList(){const cars=filtered();app.innerHTML=`${top('二手车买卖')}<section class="hero"><h1>${esc(state.merchant?.business_name||'乐生活二手车')}</h1><p>透明展示车辆信息；可预约试驾，也可以提交自己的车获得报价。</p></section><div class="tabs"><button class="${state.tab==='buy'?'on':''}" onclick="Auto.buy()">买车</button><button class="${state.tab==='sell'?'on':''}" onclick="Auto.sell()">卖车估价</button></div>${state.tab==='sell'?sellHtml():buyHtml(cars)}`;}
  function buyHtml(cars){return `<section class="filters"><select onchange="Auto.filter('type',this.value)"><option value="">全部车型</option>${['轿车','SUV','VAN','皮卡','跑车','其他'].map(v=>`<option ${state.filters.type===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('fuel',this.value)"><option value="">全部能源</option>${['汽油','柴油','混动','纯电'].map(v=>`<option ${state.filters.fuel===v?'selected':''}>${v}</option>`).join('')}</select><select onchange="Auto.filter('price',this.value)"><option value="">全部价格</option><option value="10000">$10,000 以下</option><option value="20000">$20,000 以下</option><option value="30000">$30,000 以下</option><option value="50000">$50,000 以下</option></select></section><div class="count">找到 <b>${cars.length}</b> 辆可售车辆</div><section class="cards">${cars.length?cars.map(car=>`<button class="car-card" onclick="Auto.open('${esc(car.id)}')">${photo(car)}<div><span class="chip">${esc(car.vehicle_type||'车辆')}</span>${car.is_certified?'<span class="chip">认证车况</span>':''}<h2>${esc(car.title)}</h2><p>${esc([car.year,car.mileage?`${Number(car.mileage).toLocaleString()} mi`:'里程待补充',car.fuel_type,car.transmission].filter(Boolean).join(' · '))}</p><strong class="price">${money(car.price)}</strong></div></button>`).join(''):'<div class="empty">暂无符合条件的车辆。</div>'}</section>`;}
  function sellHtml(){return `<section class="section"><h2>出售你的车</h2><p>填写基础资料后，商家会联系你确认车况并提供报价。提交不会构成买卖合同。</p></section><section class="form"><label class="field">姓名<input id="leadName" maxlength="80" value="${esc(session()?.user?.user_metadata?.display_name||'')}" placeholder="姓名（必填）"></label><label class="field">联系电话<input id="leadPhone" maxlength="40" inputmode="tel" placeholder="电话（必填）"></label><div class="lead-actions"><label class="field">品牌<input id="sellMake" maxlength="50" placeholder="例如 Toyota"></label><label class="field">车型<input id="sellModel" maxlength="50" placeholder="例如 Camry"></label><label class="field">年份<input id="sellYear" inputmode="numeric" type="number" min="1900" max="2100" placeholder="例如 2021"></label><label class="field">里程<input id="sellMileage" inputmode="numeric" type="number" min="0" placeholder="英里"></label></div><label class="field">车辆情况<textarea id="sellMessage" maxlength="1500" placeholder="可补充事故记录、保养情况、期望售价等"></textarea></label><div class="notice">提交报价需要登录乐生活，方便你查看商家回复与后续进度。</div><button class="primary" onclick="Auto.submitSell()">提交车辆，获取报价</button></section>`;}
  function renderDetail(){const car=state.selected;if(!car)return renderList();app.innerHTML=`${top('车辆详情')}<section>${photo(car).replace('<img ','<img class="detail-image" ').replace('<div class="placeholder">','<div class="detail-image placeholder">')}</section><div class="detail-title"><div><h1>${esc(car.title)}</h1><p>${esc([car.year,car.make,car.model].filter(Boolean).join(' · '))}</p></div><strong>${money(car.price)}</strong></div><div class="specs"><div><b>${esc(car.mileage?`${Number(car.mileage).toLocaleString()} mi`:'—')}</b><span>里程</span></div><div><b>${esc(car.fuel_type||'—')}</b><span>能源</span></div><div><b>${esc(car.transmission||'—')}</b><span>变速箱</span></div><div><b>${esc(car.drivetrain||'—')}</b><span>驱动</span></div><div><b>${esc(car.exterior_color||'—')}</b><span>外观颜色</span></div><div><b>${esc(car.vin_last6?`…${car.vin_last6}`:'—')}</b><span>VIN</span></div></div><section class="section"><h2>车辆说明</h2><p>${esc(car.description||car.condition_note||'商家尚未补充说明。')}</p></section>${Array.isArray(car.features)&&car.features.length?`<section class="section"><h2>配置</h2><div class="feature-list">${car.features.map(v=>`<span>${esc(v)}</span>`).join('')}</div></section>`:''}<button class="primary sticky" onclick="Auto.testDrive()">预约试驾</button>`;}
  function renderLead(type){const car=state.selected;app.innerHTML=`${top(type==='test_drive'?'预约试驾':'咨询车辆')}<section class="section"><h2>${esc(car?.title||'车辆咨询')}</h2><p>${type==='test_drive'?'请选择希望试驾的时间，商家会联系确认。':'留下联系方式，商家会尽快回复。'}</p></section><section class="form"><label class="field">姓名<input id="leadName" maxlength="80" value="${esc(session()?.user?.user_metadata?.display_name||'')}" placeholder="姓名（必填）"></label><label class="field">联系电话<input id="leadPhone" maxlength="40" inputmode="tel" placeholder="电话（必填）"></label><label class="field">希望时间（可选）<input id="leadTime" type="datetime-local"></label><label class="field">留言（可选）<textarea id="leadMessage" maxlength="1500" placeholder="例如：想确认车况、贷款或置换方案"></textarea></label><button class="primary" onclick="Auto.submitLead('${type}')">提交${type==='test_drive'?'试驾申请':'咨询'}</button></section>`;}
  async function submitLead(type){if(!session()?.user){alert('请先登录后提交咨询。');return}const name=document.getElementById('leadName')?.value.trim(),phone=document.getElementById('leadPhone')?.value.trim();if(!name||!phone){alert('请填写姓名和电话。');return}const response=await api('/rest/v1/rpc/merchant_auto_create_lead',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_listing_id:state.selected?.id||null,p_lead_type:type,p_customer_name:name,p_customer_phone:phone,p_customer_email:session().user.email||null,p_message:document.getElementById('leadMessage')?.value.trim()||null,p_vehicle_data:{},p_photos:[],p_preferred_at:document.getElementById('leadTime')?.value?new Date(document.getElementById('leadTime').value).toISOString():null})});if(!response.ok){alert('提交失败，请稍后重试。');return}app.innerHTML=`${top('已提交')}<section class="success"><i>✓</i><h1>商家已收到你的申请</h1><p>商家会通过你填写的电话联系你。你也可以稍后在 Purchase 中查看后续消费与预约记录。</p><button class="primary" onclick="Auto.list()">返回车辆列表</button></section>`;}
  async function submitSell(){if(!session()?.user){alert('请先登录后提交卖车报价。');return}const name=document.getElementById('leadName')?.value.trim(),phone=document.getElementById('leadPhone')?.value.trim();if(!name||!phone){alert('请填写姓名和电话。');return}const data={make:document.getElementById('sellMake')?.value.trim()||'',model:document.getElementById('sellModel')?.value.trim()||'',year:document.getElementById('sellYear')?.value||'',mileage:document.getElementById('sellMileage')?.value||''};const response=await api('/rest/v1/rpc/merchant_auto_create_lead',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_listing_id:null,p_lead_type:'sell_quote',p_customer_name:name,p_customer_phone:phone,p_customer_email:session().user.email||null,p_message:document.getElementById('sellMessage')?.value.trim()||null,p_vehicle_data:data,p_photos:[],p_preferred_at:null})});if(!response.ok){alert('提交失败，请稍后重试。');return}app.innerHTML=`${top('已提交')}<section class="success"><i>✓</i><h1>估价资料已提交</h1><p>商家会先核对车辆资料，再通过电话联系你确认报价。</p><button class="primary" onclick="Auto.sell()">继续提交另一辆车</button></section>`;}
  async function load(){const slug=query.get('merchant');if(!slug){app.innerHTML=`${top('二手车买卖')}<div class="empty">缺少商家信息。</div>`;return}try{const response=await api('/rest/v1/rpc/merchant_auto_public_catalog',{method:'POST',body:JSON.stringify({p_slug:slug})});const data=await response.json();if(!response.ok||!data?.merchant)throw new Error('not_found');state.merchant=data.merchant;state.listings=Array.isArray(data.listings)?data.listings:[];renderList()}catch(error){app.innerHTML=`${top('二手车买卖')}<div class="empty">暂时无法读取车辆库存，请稍后再试。</div>`;}}
  window.Auto={list(){state.tab='buy';state.screen='list';renderList()},buy(){state.tab='buy';state.screen='list';renderList()},sell(){state.tab='sell';state.screen='list';renderList()},filter(k,v){state.filters[k]=v;renderList()},open(id){state.selected=state.listings.find(v=>String(v.id)===String(id))||null;state.screen='detail';renderDetail()},testDrive(){if(!session()?.user){alert('请先登录后预约试驾。');return}state.screen='lead';renderLead('test_drive')},submitLead,submitSell,back(){if(state.screen==='detail'||state.screen==='lead'){state.screen='list';renderList()}else exit()},close:exit};
  load();
})();
