(()=>{
  const URL='https://ptxdxepmggmjcndgukjk.supabase.co',KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app=document.getElementById('ticketsApp'),q=new URLSearchParams(location.search);
  const state={merchant:null,events:[],order:null,stripe:null,elements:null,seatMap:null,selectedSeats:[]};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const session=()=>JSON.parse(localStorage.getItem('wanba_session')||'null');
  const profile=()=>JSON.parse(localStorage.getItem('wanba_profile')||'{}');
  const api=(path,opt={})=>{const s=session();return fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${s?.access_token||KEY}`,'Content-Type':'application/json',...(opt.headers||{})}})};
  const back=()=>{if(window.LeshenghuoModuleBridge?.back?.('/'))return;if(history.length>1)history.back();else location.assign('/')};
  const top=t=>`<header class="top"><button onclick="Tickets.back()">‹</button><b>${esc(t)}</b><button class="close" onclick="Tickets.back()">×</button></header>`;
  const money=v=>Number(v||0)===0?'免费':`$${Number(v).toFixed(2)}`;
  const date=v=>new Intl.DateTimeFormat('zh-CN',{timeZone:'America/Los_Angeles',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));
  const qr=code=>{try{const x=window.qrcode(0,'M');x.addData(String(code));x.make();return x.createSvgTag(5,1,'票务二维码','乐生活票务')}catch(e){return `<b>${esc(code)}</b>`}};

  async function load(){try{const r=await api('/rest/v1/rpc/merchant_ticket_public_catalog',{method:'POST',body:JSON.stringify({p_slug:q.get('merchant')})}),data=await r.json();if(!r.ok||!data?.merchant)throw 0;state.merchant=data.merchant;state.events=data.events||[];render()}catch(e){app.innerHTML=`${top('票务')}<div class="empty">暂时无法读取票务。请确认商家已开启票务与核销。</div>`}}
  function render(){app.innerHTML=`${top('票务')}<section class="hero"><h1>${esc(state.merchant.business_name)}</h1><p>选择票种或座位后购票；付款成功即可获得二维码，到场出示核销。</p></section>${state.events.length?state.events.map(card).join(''):'<div class="empty">暂时没有可购买的票务活动。</div>'}`}
  function card(e){const types=e.ticket_types||[];return `<article class="event-card">${e.cover_image?`<img class="event-cover" src="${esc(e.cover_image)}" alt="">`:''}<h2>${esc(e.title)}</h2><p class="muted">${esc(e.description||'')}</p><div class="event-meta"><span class="pill">${date(e.starts_at)}</span>${e.location_text?`<span class="pill">${esc(e.location_text)}</span>`:''}</div>${types.length?types.map(t=>`<div class="ticket-type"><div><b>${esc(t.name)}</b><div class="small">${esc(t.description||'')||'活动入场票'} · 剩余 ${Number(t.remaining||0)} 张</div></div><div><div class="price">${money(t.price)}</div><button class="secondary" ${Number(t.remaining||0)<1?'disabled':''} onclick="Tickets.open('${t.id}')">${Number(t.remaining||0)<1?'已售罄':'购票'}</button></div></div>`).join(''):''}<button class="${types.length?'secondary':'primary'}" onclick="Tickets.openEvent('${e.id}')">选择座位</button></article>`}
  function findType(id){return state.events.flatMap(e=>(e.ticket_types||[]).map(t=>({event:e,type:t}))).find(x=>x.type.id===id)}
  function open(id){const found=findType(id);if(!found)return;state.order={...found,kind:'type'};purchaseForm()}
  async function openEvent(eventId){const e=state.events.find(x=>x.id===eventId);if(!e)return;app.innerHTML=`${top('选择座位')}<div class="loading">正在读取座位图...</div>`;try{const r=await api('/rest/v1/rpc/merchant_ticket_public_event_seats',{method:'POST',body:JSON.stringify({p_event_id:eventId})}),map=await r.json();if(!r.ok||!map)throw 0;if(map.seating_mode!=='assigned'||!(map.sections||[]).length){if((e.ticket_types||[]).length)return open(e.ticket_types[0].id);app.innerHTML=`${top('选择座位')}<div class="empty">商家尚未完成座位配置。</div>`;return}state.order={event:e,kind:'seat'};state.seatMap=map;state.selectedSeats=[];seatPicker()}catch(err){app.innerHTML=`${top('选择座位')}<div class="empty">座位图暂时不可用，请稍后重试。</div>`}}
  function seatPicker(){const map=state.seatMap,all=(map.sections||[]).flatMap(s=>(s.seats||[]).map(x=>({...x,section:s}))),selected=all.filter(x=>state.selectedSeats.includes(x.id));app.innerHTML=`${top('选择座位')}<button class="backline" onclick="Tickets.render()">‹ 返回票务列表</button><section class="seat-page"><div class="stage">舞台 / 主活动区</div>${map.seat_map_image?`<img class="seat-map-image" src="${esc(map.seat_map_image)}" alt="场地图">`:''}<div class="seat-legend"><span><i class="available"></i>可选</span><span><i class="selected"></i>已选</span><span><i class="unavailable"></i>不可选</span></div>${map.sections.map(section).join('')||'<div class="empty">暂无可选座位</div>'}</section><div class="seat-bottom"><div><b>${selected.length?`已选 ${selected.map(x=>`${x.section.name} ${x.label}`).join('、')}`:'请选择座位'}</b><span>${selected.length?`合计 ${money(selected.reduce((n,x)=>n+Number(x.price||0),0))}`:' '}</span></div><button class="primary" ${selected.length?'':'disabled'} onclick="Tickets.seatForm()">下一步</button></div>`}
  function sectionBlocks(s){const raw=Array.isArray(s.seat_blocks)?s.seat_blocks:[],blocks=raw.map(Number).filter(n=>Number.isInteger(n)&&n>0);return blocks.length&&blocks.reduce((a,b)=>a+b,0)===Number(s.seats_per_row)?blocks:[Number(s.seats_per_row||1)]}
  function seatClusters(s,list){let offset=0;return `<div class="seat-clusters">${sectionBlocks(s).map((count,index)=>{const group=list.filter(x=>Number(x.seat_number)>offset&&Number(x.seat_number)<=offset+count);offset+=count;return `${index?'<span class="seat-aisle" aria-label="过道">过道</span>':''}<div class="seat-group">${group.map(x=>{const selected=state.selectedSeats.includes(x.id),expired=x.status==='held'&&new Date(x.hold_expires_at||0)<=new Date(),usable=x.status==='available'||expired;return `<button class="seat ${selected?'is-selected':''} ${usable?'':'is-unavailable'}" ${usable?'':'disabled'} onclick="Tickets.toggleSeat('${x.id}')" title="${esc(s.name)} ${esc(x.label)} · ${money(x.price)}">${esc(x.seat_number)}</button>`}).join('')}</div>`}).join('')}</div>`}
  function section(s){const seats=s.seats||[];const rows={};seats.forEach(x=>(rows[x.row_label]||(rows[x.row_label]=[])).push(x));const orderedRows=Object.entries(rows).sort(([a],[b])=>a.localeCompare(b)*(s.row_direction==='reverse'?-1:1));return `<article class="seat-section"><div class="seat-section-head"><b><i style="background:${esc(s.color)}"></i>${esc(s.name)}</b><span>${money(s.price)} 起</span></div>${orderedRows.map(([row,list])=>`<div class="seat-row"><em>${esc(row)}</em>${seatClusters(s,list)}</div>`).join('')}</article>`}
  function toggleSeat(id){const item=(state.seatMap.sections||[]).flatMap(s=>(s.seats||[])).find(x=>x.id===id);if(!item)return;if(state.selectedSeats.includes(id))state.selectedSeats=state.selectedSeats.filter(x=>x!==id);else if(state.selectedSeats.length>=20)return alert('每笔订单最多选择 20 个座位。');else state.selectedSeats.push(id);seatPicker()}
  function purchaseForm(){const found=state.order,p=profile(),seat=found.kind==='seat';const unit=seat?state.selectedSeats.reduce((n,id)=>{const x=(state.seatMap.sections||[]).flatMap(s=>(s.seats||[])).find(y=>y.id===id);return n+Number(x?.price||0)},0):Number(found.type.price||0);app.innerHTML=`${top('确认购票')}<button class="backline" onclick="${seat?'Tickets.seatPicker()':'Tickets.render()'}">‹ 返回</button><section class="form"><h2>${esc(found.event.title)}</h2><p class="muted">${seat?`已选 ${state.selectedSeats.length} 个座位 · ${money(unit)}`:`${esc(found.type.name)} · ${money(unit)} / 张`}</p>${seat?'':`<label class="field">购票数量<select id="ticketQty">${Array.from({length:Math.min(Number(found.type.max_per_order||1),Number(found.type.remaining||0))},(_,i)=>`<option value="${i+1}">${i+1} 张</option>`).join('')}</select></label>`}<label class="field">姓名<input id="ticketName" maxlength="80" value="${esc(p.display_name||p.name||'')}" placeholder="默认使用乐生活昵称，可自行修改"></label><label class="field">联系电话<input id="ticketPhone" inputmode="tel" maxlength="40" placeholder="必填，仅提供给活动商家"></label><label class="field">备注（选填）<textarea id="ticketNote" maxlength="500" placeholder="例如：同行人姓名、特殊需求"></textarea></label><div class="notice">付费票需要登录乐生活并通过 Stripe 安全支付。座位将保留 20 分钟，超时未付款会自动释放。</div><button class="primary" onclick="Tickets.submit()">${unit===0?'领取免费票':'前往支付'}</button></section>`}
  async function submit(){const found=state.order,name=document.getElementById('ticketName').value.trim(),phone=document.getElementById('ticketPhone').value.trim(),note=document.getElementById('ticketNote').value.trim(),seat=found.kind==='seat',quantity=seat?state.selectedSeats.length:Number(document.getElementById('ticketQty').value),amount=seat?state.selectedSeats.reduce((n,id)=>{const x=(state.seatMap.sections||[]).flatMap(s=>(s.seats||[])).find(y=>y.id===id);return n+Number(x?.price||0)},0):Number(found.type.price||0)*quantity;if(!name||phone.length<5)return alert('请填写姓名和联系电话。');if(amount>0&&!session()?.access_token)return alert('付费票需要先登录乐生活。');const btn=document.querySelector('.form .primary');if(btn){btn.disabled=true;btn.textContent='正在创建订单…'}try{const payload=seat?{p_event_id:found.event.id,p_seat_ids:state.selectedSeats,p_customer_name:name,p_customer_phone:phone,p_note:note}:{p_ticket_type_id:found.type.id,p_customer_name:name,p_customer_phone:phone,p_quantity:quantity,p_note:note};const r=await api(`/rest/v1/rpc/${seat?'merchant_ticket_create_seat_order':'merchant_ticket_create_order'}`,{method:'POST',body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw new Error(data?.message||'创建订单失败');if(data.payment_status==='free'){success(data);return}state.order={...state.order,...data};pay(data)}catch(err){const m=String(err.message||'');alert(m.includes('seat_unavailable')?'座位刚刚被其他用户选走，请重新选择。':m.includes('sold_out')?'票已售罄。':m.includes('login_required')?'请先登录乐生活后购买付费票。':'创建订单失败，请稍后再试。');if(btn){btn.disabled=false;btn.textContent='前往支付'}}}
  async function pay(order){app.innerHTML=`${top('安全支付')}<section class="form"><h2>${esc(state.order.event.title)}</h2><p class="muted">订单 ${esc(order.order_code)} · 座位将保留至 ${new Date(order.payment_expires_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</p><div class="payment-box"><div id="ticketPaymentElement"></div></div><div class="notice">付款成功后才会签发二维码并确认座位。</div><button class="primary" id="ticketPayBtn" onclick="Tickets.confirmPay()">支付 ${money(order.total_amount)}</button></section>`;try{const r=await api('/functions/v1/ticket-stripe-payment',{method:'POST',body:JSON.stringify({order_id:order.order_id})}),data=await r.json();if(!r.ok)throw new Error(data?.error||'payment_unavailable');state.stripe=window.Stripe(data.publishable_key);state.elements=state.stripe.elements({clientSecret:data.client_secret});state.elements.create('payment').mount('#ticketPaymentElement')}catch(e){document.getElementById('ticketPayBtn').disabled=true;document.querySelector('.payment-box').innerHTML='<div class="empty">支付服务暂时不可用，请稍后再试。</div>'}}
  async function confirmPay(){const btn=document.getElementById('ticketPayBtn');btn.disabled=true;btn.textContent='正在确认付款…';try{const result=await state.stripe.confirmPayment({elements:state.elements,redirect:'if_required'});if(result.error)throw result.error;for(let i=0;i<5;i++){await new Promise(r=>setTimeout(r,900));const r=await api('/rest/v1/rpc/merchant_ticket_order_for_customer',{method:'POST',body:JSON.stringify({p_order_id:state.order.order_id})}),data=await r.json();if(r.ok&&['paid','free'].includes(data.payment_status)){success(data);return}}throw new Error('payment_processing')}catch(e){alert(String(e.message||'').includes('payment_processing')?'付款正在确认，请稍候后重新打开票务查看。':'付款未完成，请检查支付方式后重试。');btn.disabled=false;btn.textContent=`支付 ${money(state.order.total_amount)}`}}
  function success(data){const tickets=data.tickets||[];app.innerHTML=`${top('购票成功')}<section class="success"><strong>${data.payment_status==='free'?'免费票已领取':'付款成功'}</strong><p>${esc(state.order?.event?.title||'票务活动')} · 订单 ${esc(data.order_code||'')}</p>${tickets.map(t=>`<div class="ticket-present"><div class="qr">${qr(t.ticket_code)}</div><b>${esc(t.seat_label?`${t.seat_label} · `:'')}${esc(t.ticket_code)}</b><p class="small">到场向商家出示此二维码核销</p></div>`).join('')}<button class="primary" onclick="Tickets.back()">完成</button></section>`}
  window.Tickets={back,render,open,openEvent,toggleSeat,seatPicker,seatForm:purchaseForm,submit,confirmPay};load();
})();
