(() => {
  const SUPABASE_URL = 'https://ptxdxepmggmjcndgukjk.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app = document.getElementById('rentalApp');
  const query = new URLSearchParams(location.search);
  const state = { merchant:null, vehicles:[], selected:null, quote:null, screen:'list', startsAt:'', endsAt:'', name:'', phone:'', email:'', note:'', selectedAddons:[], paymentMethod:'apple_pay', error:'' };
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const money = value => `$${Number(value || 0).toFixed(2)}`;
  const user = () => JSON.parse(localStorage.getItem('wanba_session') || 'null')?.user || null;
  const api = async (path, options={}) => { const session=JSON.parse(localStorage.getItem('wanba_session') || 'null'); const headers=Object.assign({apikey:SUPABASE_KEY,'Content-Type':'application/json'},options.headers||{}); headers.Authorization=`Bearer ${session?.access_token||SUPABASE_KEY}`; return fetch(`${SUPABASE_URL}${path}`,Object.assign({},options,{headers})); };
  const close = () => { if(window.parent!==window) window.parent.postMessage({type:'leshenghuo-close-rental'},'*'); else if(history.length>1) history.back(); else location.assign('/'); };
  const top = title => `<header class="top"><button onclick="Rental.back()" aria-label="返回">‹</button><b>${esc(title)}</b><button class="close" onclick="Rental.close()" aria-label="关闭">×</button></header>`;
  const toLocalInput = value => { const date=value?new Date(value):new Date(Date.now()+3600000); date.setMinutes(date.getMinutes()-date.getTimezoneOffset()); return date.toISOString().slice(0,16); };
  const displayDate = value => value ? new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Los_Angeles'}).format(new Date(value)) : '';
  const rate = vehicle => vehicle.pricing_mode === 'hour' ? `${money(vehicle.hourly_rate)}/小时` : vehicle.pricing_mode === 'both' ? `${money(vehicle.daily_rate)}/天 · ${money(vehicle.hourly_rate)}/小时` : `${money(vehicle.daily_rate)}/天`;
  const photo = vehicle => Array.isArray(vehicle.photos)&&vehicle.photos[0] ? `<img src="${esc(vehicle.photos[0])}" alt="">` : '<div class="placeholder">🚗</div>';
  const fuel = value => ({'纯电':'电动','电动':'电动','柴油':'柴油','混动':'混动','汽油':'汽油'}[String(value||'')] || '汽油');
  const addons = () => Array.isArray(state.selected?.addons) ? state.selected.addons : [];
  const selectedAddonRows = () => addons().filter(item => state.selectedAddons.includes(String(item.id)));
  const formTimes = () => { const start=document.getElementById('rentalStart')?.value, end=document.getElementById('rentalEnd')?.value; if(start) state.startsAt=new Date(start).toISOString(); if(end) state.endsAt=new Date(end).toISOString(); };
  const address = () => state.selected?.pickup_address || state.merchant?.address || '由商家确认取还车地点';
  const map = () => `<div class="rental-map"><span>取还车地点</span><b>${esc(address())}</b><i>●</i></div>`;
  const specIcon = type => ({
    person:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"></circle><path d="M5.5 20c.7-4 2.8-6 6.5-6s5.8 2 6.5 6"></path></svg>',
    luggage:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="6" width="12" height="14" rx="2"></rect><path d="M9 6V4h6v2M9 10h6M9 20v1M15 20v1"></path></svg>',
    wheel:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"></circle><circle cx="12" cy="12" r="2"></circle><path d="M12 4v6M4.8 14l5.3-1.2M19.2 14l-5.3-1.2"></path></svg>',
    fuel:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 21V5a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v16"></path><path d="M5 12h8M15 7h2l2 2v7a2 2 0 0 1-4 0v-3"></path></svg>',
    battery:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="7" width="15" height="10" rx="2"></rect><path d="M20 10v4M10 5l-2 6h4l-2 8 6-8h-4l2-6"></path></svg>'
  }[type] || '');
  const infoIcon = (icon,label,value) => `<div class="spec"><span>${specIcon(icon)}</span><b>${esc(value)}</b><small>${esc(label)}</small></div>`;
  const summary = () => state.quote ? `<section class="price-card"><div><span>车辆租金</span><b>${money(state.quote.base_amount)}</b></div>${Number(state.quote.addon_amount||0)?`<div><span>附加服务</span><b>${money(state.quote.addon_amount)}</b></div>`:''}<div><span>预估税费</span><b>${money(0)}</b></div><div class="total"><span>预估总额</span><b>${money(state.quote.total_amount)}</b></div></section>` : '';
  function renderList(){
    const start=state.startsAt?toLocalInput(state.startsAt):toLocalInput(); const end=state.endsAt?toLocalInput(state.endsAt):toLocalInput(new Date(Date.now()+25*3600000));
    app.innerHTML=`${top('租车预约')}<section class="rental-hero"><h1>${esc(state.merchant?.business_name||'乐生活租车')}</h1><p>${esc(state.merchant?.address||'请选择取还时间后查看可预约车辆')}</p></section><section class="time-filter"><label>取车时间<input id="rentalStart" type="datetime-local" value="${esc(start)}" min="${toLocalInput()}"></label><label>还车时间<input id="rentalEnd" type="datetime-local" value="${esc(end)}" min="${toLocalInput(new Date(Date.now()+3600000))}"></label><button onclick="Rental.refreshList()">查询车辆</button></section><div class="vehicle-list">${state.vehicles.length?state.vehicles.map(vehicle=>`<article class="vehicle">${photo(vehicle)}<div class="vehicle-main"><div class="vehicle-head"><div><h2>${esc(vehicle.name)}</h2><p>${esc([vehicle.year,vehicle.make,vehicle.model].filter(Boolean).join(' '))}</p></div><b>${rate(vehicle)}</b></div><div class="chips"><span>${esc(vehicle.vehicle_type||'车辆')}</span><span>${vehicle.seats||5} 座</span><span>${esc(vehicle.transmission||'自动挡')}</span><span>${esc(fuel(vehicle.fuel_type))}</span></div><button onclick="Rental.select('${esc(vehicle.id)}')">查看车辆</button></div></article>`).join(''):'<div class="empty">这家商家还没有发布可预约车辆。</div>'}</div>`;
  }
  function renderVehicle(){
    const v=state.selected; if(!v) return renderList();
    const start=state.startsAt?toLocalInput(state.startsAt):toLocalInput(); const end=state.endsAt?toLocalInput(state.endsAt):toLocalInput(new Date(Date.now()+25*3600000));
    const options=addons();
    app.innerHTML=`${top('车辆详细信息')}<section class="vehicle-hero">${photo(v)}<span class="cancel-tag">✓ 免费取消</span></section><div class="vehicle-title"><div><p>${esc([v.year,v.make,v.model].filter(Boolean).join(' ') || v.vehicle_type || '可预约车辆')}</p><h1>${esc(v.name)}</h1></div><b>${rate(v)}<small>含税费以确认页为准</small></b></div><div class="spec-row">${infoIcon('person','座位',`${v.seats||5}`)}${infoIcon('luggage','行李',`${v.luggage_count ?? 2}`)}${infoIcon('wheel','档位',v.transmission||'自动挡')}${infoIcon(fuel(v.fuel_type)==='电动'?'battery':'fuel','燃油',fuel(v.fuel_type))}</div><section class="rental-section"><h2>预约时间</h2><label>取车时间<input id="rentalStart" type="datetime-local" value="${esc(start)}" min="${toLocalInput()}"></label><label>还车时间<input id="rentalEnd" type="datetime-local" value="${esc(end)}" min="${toLocalInput(new Date(Date.now()+3600000))}"></label><button class="outline" onclick="Rental.quote()">更新价格与可用性</button>${state.error?`<p class="warning">${esc(state.error)}</p>`:''}</section>${state.quote?`<section class="rental-section"><h2>租车附加服务</h2>${options.length?options.map(item=>`<label class="addon"><span><b>${esc(item.name)}</b><small>${esc(item.description||'租车附加服务')}</small><em>+${money(item.price)}${item.unit==='day'?'/天':''}</em></span><input type="checkbox" ${state.selectedAddons.includes(String(item.id))?'checked':''} onchange="Rental.toggleAddon('${esc(item.id)}',this.checked)"><i></i></label>`).join(''):`<p class="muted">商家暂未设置附加服务。</p>`}</section>${summary()}<section class="rental-section place-section"><h2>取车和还车</h2>${map()}<p><b>${esc(address())}</b><small>到店取车并原地归还；具体流程以商家确认信息为准。</small></p></section><section class="help-list"><button onclick="Rental.help()">☎ 寻求帮助 <span>›</span></button><button onclick="Rental.faq()">ⓘ 常见问题 <span>›</span></button></section><button class="primary sticky-action" onclick="Rental.contact()">继续查看附加项</button>`:`<button class="primary sticky-action" onclick="Rental.quote()">计算租金与可用性</button>`}`;
  }
  function renderContact(){
    const profile=user(); const v=state.selected;
    app.innerHTML=`${top('查看预约')}<section class="review-head"><div>${photo(v)}</div><p><b>${esc(v.name)}</b><span>${esc([v.year,v.make,v.model].filter(Boolean).join(' '))}</span></p></section><section class="rental-section"><h2>预约开始时间</h2><p class="detail-line">▣ ${displayDate(state.startsAt)}<small>至 ${displayDate(state.endsAt)}</small></p><label>租车人姓名<input id="rentalName" maxlength="80" value="${esc(state.name||profile?.user_metadata?.display_name||profile?.user_metadata?.name||'')}" placeholder="姓名（必填）"></label><label>联系电话<input id="rentalPhone" maxlength="40" inputmode="tel" value="${esc(state.phone)}" placeholder="电话（必填）"></label><label>邮箱（选填）<input id="rentalEmail" maxlength="120" type="email" value="${esc(state.email||profile?.email||'')}" placeholder="用于接收预约信息"></label><label>备注（选填）<textarea id="rentalNote" maxlength="400" placeholder="例如：航班号、取车时间或其他需求">${esc(state.note)}</textarea></label></section>${summary()}<section class="rental-section"><h2>自助取车和还车</h2>${map()}<p class="detail-line">⌖ ${esc(address())}<small>取还车地点与到店流程将由商家确认。</small></p></section><section class="help-list"><button onclick="Rental.help()">☎ 寻求帮助 <span>›</span></button><button onclick="Rental.faq()">ⓘ 常见问题 <span>›</span></button></section><div class="action-grid"><button class="danger" onclick="Rental.cancel()">取消预约</button><button class="secondary" onclick="Rental.modify()">修改预约</button></div><button class="primary confirm-booking" onclick="Rental.review()">确认预约</button>`;
  }
  function renderPayment(){
    const methods=[['apple_pay','Apple Pay','使用 Apple Pay 支付预估总额'],['google_pay','Google Pay','使用 Google Pay 支付预估总额'],['card','信用卡','使用信用卡支付预估总额'],['gift','商家礼品卡','使用商家礼品卡支付预估总额']];
    app.innerHTML=`${top('支付预约')}<section class="payment-banner"><b>确认支付内容</b><span>${esc(state.selected.name)} · ${displayDate(state.startsAt)} 至 ${displayDate(state.endsAt)}</span></section>${summary()}<section class="rental-section"><h2>支付方式</h2>${methods.map(([id,title,detail])=>`<button class="pay-method ${state.paymentMethod===id?'selected':''}" onclick="Rental.pickPayment('${id}')"><span><b>${title}</b><small>${detail}</small></span><i>${state.paymentMethod===id?'✓':''}</i></button>`).join('')}<p class="payment-note">当前为预约支付流程界面。正式扣款、押金预授权和退款将在商家开通支付服务后启用；提交后商家会确认你的预约。</p></section><button class="primary sticky-action" onclick="Rental.submit()">确认并提交 ${money(state.quote?.total_amount)}</button>`;
  }
  function renderSuccess(booking){ app.innerHTML=`${top('预约已提交')}<div class="success"><i>✓</i><h1>预约已提交</h1><b>${esc(booking.booking_code||'')}</b><p>商家将确认你的预约和付款安排。</p><section class="price-card"><div><span>车辆租金</span><b>${money(booking.base_amount)}</b></div>${Number(booking.addon_amount||0)?`<div><span>附加服务</span><b>${money(booking.addon_amount)}</b></div>`:''}<div class="total"><span>预估总额</span><b>${money(booking.total_amount)}</b></div></section><button class="primary" onclick="Rental.list()">返回车辆列表</button></div>`; }
  async function quote(){ formTimes(); state.error=''; try { const response=await api('/rest/v1/rpc/merchant_rental_quote',{method:'POST',body:JSON.stringify({p_vehicle_id:state.selected.id,p_starts_at:state.startsAt,p_ends_at:state.endsAt,p_addon_ids:state.selectedAddons})}); const data=await response.json(); if(!response.ok)throw new Error(String(data?.message||data?.hint||'该时间暂不可预约')); state.quote=data; renderVehicle(); } catch(error){ state.quote=null; state.error=error.message.includes('vehicle')?'该车辆在这段时间不可预约，请换一个时间。':error.message.includes('invalid')?'请确认取车和还车时间。':'暂时无法计算，请稍后重试。'; renderVehicle(); } }
  function toggleAddon(id, checked){ state.selectedAddons=checked?[...new Set(state.selectedAddons.concat(String(id)))]:state.selectedAddons.filter(value=>value!==String(id)); quote(); }
  function contact(){ state.screen='contact'; renderContact(); }
  function review(){ state.name=document.getElementById('rentalName')?.value.trim()||''; state.phone=document.getElementById('rentalPhone')?.value.trim()||''; state.email=document.getElementById('rentalEmail')?.value.trim()||''; state.note=document.getElementById('rentalNote')?.value.trim()||''; if(!state.name||!state.phone){ alert('请填写姓名和电话。'); return; } state.screen='payment'; renderPayment(); }
  async function submit(){ const response=await api('/rest/v1/rpc/merchant_rental_create_booking',{method:'POST',body:JSON.stringify({p_vehicle_id:state.selected.id,p_starts_at:state.startsAt,p_ends_at:state.endsAt,p_customer_name:state.name,p_customer_phone:state.phone,p_customer_email:state.email||null,p_note:state.note||null,p_addon_ids:state.selectedAddons})}); const data=await response.json(); if(!response.ok){ alert(data?.message?.includes('unavailable')?'该时段刚被其他预约占用，请重新选择时间。':'预约提交失败，请稍后重试。'); return; } renderSuccess(data); }
  function refreshList(){ formTimes(); renderList(); }
  function select(id){ state.selected=state.vehicles.find(v=>String(v.id)===String(id))||null; state.quote=null; state.error=''; state.selectedAddons=[]; state.screen='vehicle'; renderVehicle(); }
  function back(){ if(state.screen==='payment'){state.screen='contact';renderContact();} else if(state.screen==='contact'){state.screen='vehicle';renderVehicle();} else if(state.screen==='vehicle'){state.screen='list';renderList();} else close(); }
  function modify(){ state.screen='vehicle'; renderVehicle(); }
  function cancel(){ if(confirm('确定取消本次尚未提交的预约吗？')) { state.screen='list'; state.selected=null; state.quote=null; state.selectedAddons=[]; renderList(); } }
  async function load(){ const slug=query.get('merchant'); if(!slug){ app.innerHTML='<div class="empty">缺少商家信息。</div>'; return; } try { const res=await api('/rest/v1/rpc/merchant_rental_public_catalog',{method:'POST',body:JSON.stringify({p_slug:slug})}); const data=await res.json(); if(!res.ok||!data?.merchant)throw new Error('not_found'); state.merchant=data.merchant; state.vehicles=Array.isArray(data.vehicles)?data.vehicles:[]; renderList(); } catch(e){ app.innerHTML=`${top('车辆预约')}<div class="empty">暂时无法读取租车服务，请稍后再试。</div>`; } }
  window.Rental={close,back,refreshList,select,quote,toggleAddon,contact,review,pickPayment:id=>{state.paymentMethod=id;renderPayment();},submit,modify,cancel,list:()=>{state.screen='list';state.selected=null;state.quote=null;renderList();},help:()=>alert(`请联系 ${state.merchant?.business_name||'商家'}：${state.merchant?.phone||'商家暂未填写电话'}`),faq:()=>alert('常见问题：预约提交后由商家确认；请在取车前携带有效驾照与预约信息。')};
  load();
})();
