(() => {
  const SUPABASE_URL = 'https://ptxdxepmggmjcndgukjk.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app = document.getElementById('rentalApp');
  const query = new URLSearchParams(location.search);
  const state = { merchant:null, vehicles:[], selected:null, quote:null, screen:'list', startsAt:'', endsAt:'', name:'', phone:'', email:'', note:'', error:'' };
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
  const money = value => `$${Number(value || 0).toFixed(2)}`;
  const user = () => JSON.parse(localStorage.getItem('wanba_session') || 'null')?.user || null;
  const api = async (path, options={}) => { const session=JSON.parse(localStorage.getItem('wanba_session') || 'null'); const headers=Object.assign({apikey:SUPABASE_KEY,'Content-Type':'application/json'},options.headers||{}); headers.Authorization=`Bearer ${session?.access_token||SUPABASE_KEY}`; return fetch(`${SUPABASE_URL}${path}`,Object.assign({},options,{headers})); };
  const close = () => { if(window.parent!==window) window.parent.postMessage({type:'leshenghuo-close-rental'},'*'); else if(history.length>1) history.back(); else location.assign('/'); };
  const top = title => `<header class="top"><button onclick="Rental.back()" aria-label="返回">‹</button><b>${esc(title)}</b><button class="close" onclick="Rental.close()" aria-label="关闭">×</button></header>`;
  const toLocalInput = value => { const date=value?new Date(value):new Date(Date.now()+3600000); date.setMinutes(date.getMinutes()-date.getTimezoneOffset()); return date.toISOString().slice(0,16); };
  const displayDate = value => value ? new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Los_Angeles'}).format(new Date(value)) : '';
  const rate = vehicle => vehicle.pricing_mode === 'hour' ? `${money(vehicle.hourly_rate)}/小时` : vehicle.pricing_mode === 'both' ? `${money(vehicle.hourly_rate)}/小时起` : `${money(vehicle.daily_rate)}/天`;
  const photo = vehicle => Array.isArray(vehicle.photos)&&vehicle.photos[0] ? `<img src="${esc(vehicle.photos[0])}" alt="">` : '<div class="placeholder"></div>';
  function formTimes(){ const start=document.getElementById('rentalStart')?.value, end=document.getElementById('rentalEnd')?.value; if(start) state.startsAt=new Date(start).toISOString(); if(end) state.endsAt=new Date(end).toISOString(); }
  function renderList(){
    const defaultStart=state.startsAt?toLocalInput(state.startsAt):toLocalInput(); const defaultEnd=state.endsAt?toLocalInput(state.endsAt):toLocalInput(new Date(Date.now()+25*3600000));
    const vehicles=state.vehicles;
    app.innerHTML=`${top('车辆预约')}<section class="hero"><h1>${esc(state.merchant?.business_name||'乐生活租车')}</h1><p>${esc(state.merchant?.address||'请选择取还时间后查看可预约车辆')}</p></section><section class="filter"><label>取车时间<input id="rentalStart" type="datetime-local" value="${esc(defaultStart)}" min="${toLocalInput()}"></label><label>还车时间<input id="rentalEnd" type="datetime-local" value="${esc(defaultEnd)}" min="${toLocalInput(new Date(Date.now()+3600000))}"></label><button onclick="Rental.refreshQuoteList()">查询可预约车辆</button></section><div class="vehicle-list">${vehicles.length?vehicles.map(vehicle=>`<article class="vehicle">${photo(vehicle)}<div class="vehicle-main"><div class="vehicle-head"><div><h2>${esc(vehicle.name)}</h2><p class="meta">${esc([vehicle.year,vehicle.make,vehicle.model].filter(Boolean).join(' '))}</p></div><span class="rate">${rate(vehicle)}</span></div><div class="chips"><span>${esc(vehicle.vehicle_type||'车辆')}</span><span>${esc(String(vehicle.seats||5))} 座</span><span>${esc(vehicle.transmission||'自动挡')}</span><span>${esc(vehicle.fuel_type||'汽油')}</span></div>${vehicle.description?`<p class="muted">${esc(vehicle.description)}</p>`:''}<button onclick="Rental.select('${esc(vehicle.id)}')">查看并预约</button></div></article>`).join(''):'<div class="empty">这家商家还没有发布可预约车辆。</div>'}</div>`;
  }
  function renderVehicle(){ const vehicle=state.selected; if(!vehicle)return renderList(); const photos=Array.isArray(vehicle.photos)?vehicle.photos:[]; app.innerHTML=`${top('预约车辆')}<section class="hero"><h1>${esc(vehicle.name)}</h1><p>${esc(state.merchant?.business_name||'乐生活商家')} · ${esc(vehicle.pickup_address||state.merchant?.address||'到店取车')}</p></section>${photos[0]?`<img class="details-photo" src="${esc(photos[0])}" alt="">`:''}${photos.length>1?`<div class="photo-strip">${photos.slice(1).map(url=>`<img src="${esc(url)}" alt="">`).join('')}</div>`:''}<section class="section"><h2>车辆信息</h2><p class="muted">${esc([vehicle.year,vehicle.make,vehicle.model,vehicle.vehicle_type,`${vehicle.seats||5} 座`,vehicle.transmission,vehicle.fuel_type].filter(Boolean).join(' · '))}</p>${vehicle.description?`<p class="muted">${esc(vehicle.description)}</p>`:''}</section><section class="section"><h2>选择租期</h2><label>取车时间<input id="rentalStart" type="datetime-local" value="${esc(state.startsAt?toLocalInput(state.startsAt):toLocalInput())}" min="${toLocalInput()}"></label><label>还车时间<input id="rentalEnd" type="datetime-local" value="${esc(state.endsAt?toLocalInput(state.endsAt):toLocalInput(new Date(Date.now()+25*3600000)))}" min="${toLocalInput(new Date(Date.now()+3600000))}"></label><button class="primary" style="margin-top:12px" onclick="Rental.quote()">计算租金与可用性</button>${state.error?`<p class="date-warning">${esc(state.error)}</p>`:''}</section>${state.quote?`<section class="quote"><div><span>租期</span><b>${esc(state.quote.pricing_mode==='hour'?`${state.quote.unit_count} 小时`:`${state.quote.unit_count} 天`)}</b></div><div><span>车辆租金</span><b>${money(state.quote.base_amount)}</b></div><div><span>取车押金</span><b>${money(state.quote.deposit_amount)}</b></div><div class="total"><span>预计租金</span><b>${money(state.quote.total_amount)}</b></div><small>押金与实际付款由商家确认；线上支付与预授权将在后续开通。</small></section><button class="primary" style="margin-top:14px;width:100%" onclick="Rental.contact()">填写预约信息</button>`:''}`; }
  function renderContact(){ const vehicle=state.selected, profile=user(); app.innerHTML=`${top('提交预约')}<section class="hero"><h1>${esc(vehicle?.name||'车辆预约')}</h1><p>${displayDate(state.startsAt)} 至 ${displayDate(state.endsAt)}</p></section><section class="section"><h2>租车人信息</h2><label>姓名<input id="rentalName" maxlength="80" value="${esc(state.name||profile?.user_metadata?.display_name||profile?.user_metadata?.name||'')}" placeholder="姓名（必填）"></label><label>电话<input id="rentalPhone" maxlength="40" inputmode="tel" value="${esc(state.phone)}" placeholder="电话（必填）"></label><label>邮箱（选填）<input id="rentalEmail" maxlength="120" type="email" value="${esc(state.email||profile?.email||'')}" placeholder="用于接收预约确认"></label><label>备注（选填）<textarea id="rentalNote" maxlength="400" placeholder="例如：取车时间、儿童座椅等需求">${esc(state.note)}</textarea></label><div class="notice">提交后由商家人工确认。取车时请携带有效驾照并完成车辆验车；为了保护隐私，本阶段不在公开网页上传驾照照片。</div></section><section class="quote"><div><span>车辆租金</span><b>${money(state.quote?.total_amount)}</b></div><div><span>取车押金</span><b>${money(state.quote?.deposit_amount)}</b></div></section><button class="primary" style="margin-top:14px;width:100%" onclick="Rental.submit()">提交预约</button>`; }
  function renderSuccess(booking){ app.innerHTML=`${top('预约已提交')}<div class="success"><i>✓</i><h1>预约已提交</h1><p class="muted">商家确认前将为你保留该时段。请留意电话或邮箱通知。</p><b>${esc(booking.booking_code||'')}</b><p class="muted">预计租金 ${money(booking.total_amount)} · 押金 ${money(booking.deposit_amount)}</p><button class="primary" style="margin-top:16px" onclick="Rental.list()">返回车辆列表</button></div>`; }
  async function quote(){ formTimes(); state.error=''; try { const response=await api('/rest/v1/rpc/merchant_rental_quote',{method:'POST',body:JSON.stringify({p_vehicle_id:state.selected.id,p_starts_at:state.startsAt,p_ends_at:state.endsAt})}); const data=await response.json(); if(!response.ok)throw new Error(String(data?.message||data?.hint||'该时间暂不可预约')); state.quote=data; renderVehicle(); } catch(error){ state.quote=null; state.error=error.message.includes('vehicle')?'该车辆在这段时间不可预约，请换一个时间。':error.message.includes('invalid')?'请确认取车和还车时间。':'暂时无法计算，请稍后重试。'; renderVehicle(); } }
  async function submit(){ state.name=document.getElementById('rentalName')?.value.trim()||''; state.phone=document.getElementById('rentalPhone')?.value.trim()||''; state.email=document.getElementById('rentalEmail')?.value.trim()||''; state.note=document.getElementById('rentalNote')?.value.trim()||''; if(!state.name||!state.phone){ alert('请填写姓名和电话。'); return; } const response=await api('/rest/v1/rpc/merchant_rental_create_booking',{method:'POST',body:JSON.stringify({p_vehicle_id:state.selected.id,p_starts_at:state.startsAt,p_ends_at:state.endsAt,p_customer_name:state.name,p_customer_phone:state.phone,p_customer_email:state.email||null,p_note:state.note||null})}); const data=await response.json(); if(!response.ok){ alert(data?.message?.includes('unavailable')?'该时段刚被其他预约占用，请重新选择时间。':'预约提交失败，请稍后重试。'); return; } renderSuccess(data); }
  async function load(){ const slug=query.get('merchant'); if(!slug){ app.innerHTML='<div class="empty">缺少商家信息。</div>'; return; } try { const response=await api('/rest/v1/rpc/merchant_rental_public_catalog',{method:'POST',body:JSON.stringify({p_slug:slug})}); const data=await response.json(); if(!response.ok||!data?.merchant)throw new Error('not_found'); state.merchant=data.merchant;state.vehicles=Array.isArray(data.vehicles)?data.vehicles:[]; renderList(); } catch(error){ app.innerHTML=`${top('车辆预约')}<div class="empty">暂时无法读取租车服务，请稍后再试。</div>`; } }
  window.Rental={close,back:()=>{if(state.screen==='contact'){state.screen='vehicle';renderVehicle();}else if(state.screen==='vehicle'){state.screen='list';renderList();}else close();},list:()=>{state.screen='list';state.selected=null;state.quote=null;renderList();},refreshQuoteList:()=>{formTimes();renderList();},select:id=>{state.selected=state.vehicles.find(vehicle=>String(vehicle.id)===String(id))||null;state.quote=null;state.error='';state.screen='vehicle';renderVehicle();},quote,contact:()=>{state.screen='contact';renderContact();},submit};
  load();
})();
