(() => {
  const SUPABASE_URL = 'https://ptxdxepmggmjcndgukjk.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app = document.getElementById('queueApp');
  const query = new URLSearchParams(location.search);
  const state = { merchant:null, products:[], board:[], ticket:null, cart:{}, category:'全部', screen:'join', tables:[] };
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
  const money = value => `$${Number(value || 0).toFixed(2)}`;
  const price = value => Number(String(value || '').match(/\d+(?:\.\d{1,2})?/)?.[0] || 0);
  const session = () => JSON.parse(localStorage.getItem('wanba_session') || 'null');
  const user = () => session()?.user || null;
  const api = async (path, options = {}) => {
    const current = session();
    const headers = Object.assign({apikey:SUPABASE_KEY,'Content-Type':'application/json'}, options.headers || {});
    headers.Authorization = `Bearer ${current?.access_token || SUPABASE_KEY}`;
    return fetch(`${SUPABASE_URL}${path}`, Object.assign({},options,{headers}));
  };
  const ticketKey = () => `leshenghuo_waitlist_${state.merchant?.user_id || ''}`;
  const nav = screen => { state.screen=screen; render(); window.scrollTo(0,0); };
  const close = () => { if(window.parent!==window) window.parent.postMessage({type:'leshenghuo-close-takeout'},'*'); else if(history.length>1) history.back(); else location.assign('/'); };
  const top = title => `<header class="top"><button onclick="Queue.back()" aria-label="返回">‹</button><b>${esc(title)}</b><button onclick="Queue.close()" aria-label="关闭">×</button></header>`;
  const hero = () => `<section class="hero"><h1>${esc(state.merchant?.business_name || '乐生活扫码排队')}</h1><p>${esc(state.merchant?.address || '')}</p></section>`;
  const products = () => state.products.filter(row=>row.active!==false && row.orderable!==false);
  const productCategories = row => Array.isArray(row.categories)?row.categories:(row.category?[row.category]:[]);
  const categories = () => ['全部',...new Set(products().flatMap(productCategories).filter(Boolean))];
  const cartRows = () => state.products.filter(row=>Number(state.cart[row.id]||0)>0).map(row=>Object.assign({},row,{quantity:Number(state.cart[row.id])}));
  const subtotal = () => cartRows().reduce((sum,row)=>sum+price(row.price)*row.quantity,0);
  const refreshBoard = async () => { const res=await api('/rest/v1/rpc/merchant_waitlist_public_board',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id})}); state.board=res.ok?await res.json():[]; return state.board; };
  const restoreTicket = () => { try { const saved=JSON.parse(localStorage.getItem(ticketKey())||'null'); if(saved?.id&&saved?.manage_token) state.ticket=saved; } catch(_){} };
  const boardHtml = () => state.board.length ? `<div class="queue-list">${state.board.map(row=>`<div class="queue-row"><span><b>${Number(row.party_size)} 人桌 · ${esc(row.queue_code)}</b><small>前方排队 ${Math.max(0,Number(row.queue_number)-1)} 组</small></span><em>约 ${Number(row.estimated_wait_minutes)||0} 分钟</em></div>`).join('')}</div>` : '<p class="muted">目前没有排队中的顾客，欢迎第一位入座。</p>';
  function renderJoin(){
    const profileName=user()?.user_metadata?.display_name||user()?.user_metadata?.name||'';
    app.innerHTML=`${top('扫码排队')}${hero()}<section class="section"><h2>排队信息</h2><label>人数</label><select id="waitPartySize">${Array.from({length:20},(_,i)=>`<option value="${i+1}">${i+1} 人</option>`).join('')}</select><label>姓名</label><input id="waitName" maxlength="40" value="${esc(profileName)}" placeholder="姓名（必填）"><label>电话号码</label><input id="waitPhone" inputmode="tel" maxlength="32" placeholder="电话号码（必填）"><button class="primary" style="margin-top:15px" onclick="Queue.join()">提交排队</button><p class="join-note">提交后会显示排队编号和预计等待时间。</p></section><section class="section"><h2>当前排队</h2>${boardHtml()}</section>`;
  }
  function renderQueued(){
    const ticket=state.ticket, items=cartRows();
    app.innerHTML=`${top('排队成功')}${hero()}<div class="success"><i>✓</i><h1>排队成功</h1><p class="muted">你的排队编号</p><div class="code">${esc(ticket.queue_code)}</div><p class="muted">前方约 ${Number(ticket.people_ahead)||0} 组，预计等待 ${Number(ticket.estimated_wait_minutes)||0} 分钟。</p></div><section class="seat-card"><b>入座后可提交预点菜</b><p>可以先提前点菜；入座时扫描餐桌二维码，或在 App 中选择桌号后确认下单。</p><div class="actions"><button class="action" onclick="Queue.menu()">${items.length?'继续修改预点菜':'提前点菜'}</button><button class="action" onclick="Queue.seat()">入座扫码</button></div></section><section class="section"><h2>前方排队</h2>${boardHtml()}</section>`;
  }
  function renderMenu(){
    const rows=products().filter(row=>state.category==='全部'||productCategories(row).includes(state.category)), count=cartRows().reduce((sum,row)=>sum+row.quantity,0);
    app.innerHTML=`${top('提前点菜')}${hero()}<div class="tabs">${categories().map(category=>`<button class="${state.category===category?'on':''}" onclick="Queue.category('${esc(category)}')">${esc(category)}</button>`).join('')}</div><div class="list">${rows.length?rows.map(row=>`<article class="product">${row.image?`<img src="${esc(row.image)}" alt="">`:'<div class="product-placeholder"></div>'}<div class="product-main"><b>${esc(row.name||'未命名菜品')}</b>${row.description?`<p>${esc(row.description)}</p>`:''}<span class="price">${esc(row.price||'到店咨询')}</span></div><div class="qty"><button onclick="Queue.qty('${esc(row.id)}',-1)" ${Number(state.cart[row.id]||0)?'':'disabled'}>−</button><span>${Number(state.cart[row.id]||0)}</span><button onclick="Queue.qty('${esc(row.id)}',1)">+</button></div></article>`).join(''):'<div class="empty">商家暂时没有可预点的菜品。</div>'}</div><div class="bar"><div><b>${money(subtotal())}</b><span>${count?`已选 ${count} 件`:'请选择菜品'}</span></div><button class="primary" ${count?'':'disabled'} onclick="Queue.cart()">查看预点菜</button></div>`;
  }
  function renderCart(){const rows=cartRows();app.innerHTML=`${top('预点菜')}${hero()}<section class="section"><h2>已选内容</h2>${rows.length?rows.map(row=>`<div class="summary-line"><span>${esc(row.name)} × ${row.quantity}</span><b>${money(price(row.price)*row.quantity)}</b></div>`).join(''):'<p class="muted">还没有选择菜品。</p>'}<div class="summary-line total"><span>预点菜小计</span><b>${money(subtotal())}</b></div><div class="notice">这不是结算。菜品会先保存，入座后确认下单，再按商家当前价格和库存复核。</div></section><div class="actions"><button class="action" onclick="Queue.menu()">继续点菜</button><button class="action" ${rows.length?'':'disabled'} onclick="Queue.savePreorder()">保存预点菜</button></div>`;}
  function renderSeat(){const rows=cartRows();app.innerHTML=`${top('入座并下单')}${hero()}<section class="section"><h2>你的预点菜</h2>${rows.length?rows.map(row=>`<div class="summary-line"><span>${esc(row.name)} × ${row.quantity}</span><b>${money(price(row.price)*row.quantity)}</b></div>`).join(''):'<p class="muted">尚未预点菜。可直接扫描桌面二维码进入点餐。</p>'}</section>${user()?.id?`<section class="section"><h2>选择已入座餐桌</h2><p>选择桌号后，会将已保存的预点菜正式发送给商家。</p><div class="table-grid">${state.tables.length?state.tables.map(table=>`<button onclick="Queue.placeOrder('${esc(table.table_code)}')">${esc(table.table_name)}<small>${esc(table.table_code)}</small></button>`).join(''):'<p class="muted">正在读取餐桌；也可以扫描桌面二维码。</p>'}</div></section>`:`<section class="section"><h2>请先登录乐生活</h2><p>未注册用户可直接扫码排队。预点菜已保存在本机；入座后登录乐生活 App 并扫描餐桌二维码，即可确认下单。</p></section>`}`;
  }
  function render(){try{if(!state.merchant)return;if(state.screen==='queued')renderQueued();else if(state.screen==='menu')renderMenu();else if(state.screen==='cart')renderCart();else if(state.screen==='seat')renderSeat();else renderJoin();}catch(error){console.error(error);app.innerHTML='<div class="empty">排队页面暂时无法打开，请稍后再试。</div>';}}
  async function join(){const name=document.getElementById('waitName')?.value.trim()||'',phone=document.getElementById('waitPhone')?.value.trim()||'',party=Number(document.getElementById('waitPartySize')?.value||0);if(!name||!phone){alert('请填写姓名和电话号码。');return;}const res=await api('/rest/v1/rpc/merchant_waitlist_join',{method:'POST',body:JSON.stringify({p_merchant_user_id:state.merchant.user_id,p_customer_name:name,p_customer_phone:phone,p_party_size:party})});if(!res.ok){console.warn(await res.text());alert('提交排队失败，请稍后重试。');return;}state.ticket=await res.json();localStorage.setItem(ticketKey(),JSON.stringify(state.ticket));await refreshBoard();nav('queued');}
  async function savePreorder(){const rows=cartRows();if(!rows.length){alert('请先选择菜品。');return;}if(!state.ticket?.id){alert('请先提交排队。');return;}const res=await api('/rest/v1/rpc/merchant_waitlist_save_preorder',{method:'POST',body:JSON.stringify({p_waitlist_id:state.ticket.id,p_manage_token:state.ticket.manage_token,p_items:rows.map(row=>({product_id:row.id,quantity:row.quantity}))})});if(!res.ok){console.warn(await res.text());alert('预点菜保存失败，请稍后重试。');return;}state.ticket.preorder_items=rows.map(row=>({product_id:row.id,quantity:row.quantity}));localStorage.setItem(ticketKey(),JSON.stringify(state.ticket));alert('预点菜已保存。入座后可选择桌号确认下单。');nav('queued');}
  async function seat(){if(!user()?.id){nav('seat');return;}try{const res=await api(`/rest/v1/merchant_order_tables?merchant_user_id=eq.${encodeURIComponent(state.merchant.user_id)}&is_active=eq.true&select=id,table_code,table_name&order=table_name.asc`);state.tables=res.ok?await res.json():[];}catch(_){state.tables=[];}nav('seat');}
  async function placeOrder(tableCode){const rows=cartRows();if(!rows.length){alert('没有预点菜，请直接扫描餐桌二维码点餐。');return;}if(!confirm(`确认将 ${rows.length} 种预点菜发送到 ${tableCode} 吗？`))return;const res=await api('/rest/v1/rpc/merchant_waitlist_submit_preorder',{method:'POST',body:JSON.stringify({p_waitlist_id:state.ticket.id,p_manage_token:state.ticket.manage_token,p_table_code:tableCode})});if(!res.ok){console.warn(await res.text());alert('下单失败，请确认已登录且餐桌仍可使用。');return;}state.cart={};localStorage.removeItem(ticketKey());alert('预点菜已下单，商家正在处理。');close();}
  window.Queue={back:()=>{if(state.screen==='menu')nav('queued');else if(state.screen==='cart')nav('menu');else if(state.screen==='seat')nav('queued');else close();},close,join,menu:()=>nav('menu'),cart:()=>nav('cart'),seat,savePreorder,placeOrder,category:value=>{state.category=value;render();},qty:(id,delta)=>{state.cart[id]=Math.max(0,Number(state.cart[id]||0)+delta);if(!state.cart[id])delete state.cart[id];render();}};
  (async()=>{const slug=query.get('merchant');if(!slug){app.innerHTML='<div class="empty">缺少商家信息。</div>';return;}const res=await api(`/rest/v1/merchants?slug=eq.${encodeURIComponent(slug)}&verified=eq.true&select=*&limit=1`);const rows=res.ok?await res.json():[];state.merchant=rows[0];if(!state.merchant){app.innerHTML='<div class="empty">未找到可排队商家。</div>';return;}state.products=Array.isArray(state.merchant.products)?state.merchant.products:[];restoreTicket();if(state.ticket?.preorder_items?.length)state.ticket.preorder_items.forEach(row=>state.cart[row.product_id]=Number(row.quantity||0));await refreshBoard();state.screen=state.ticket?'queued':'join';render();})().catch(error=>{console.error(error);app.innerHTML='<div class="empty">排队页面暂时无法打开，请稍后再试。</div>';});
})();
