-- 乐生活 v5.173：管理员用户资料、封禁、禁言与警告。

alter table public.admin_user_statuses
  add column if not exists expires_at timestamptz,
  add column if not exists reason_code text,
  add column if not exists note text,
  add column if not exists updated_by uuid references auth.users(id);

create table if not exists public.admin_user_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null check (action_type in ('ban','mute','warning','unban','unmute')),
  reason_code text,
  note text,
  duration_days integer,
  expires_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists admin_user_actions_user_created_idx
  on public.admin_user_actions (user_id, created_at desc);

create table if not exists public.user_moderation_notices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_id bigint references public.admin_user_actions(id) on delete set null,
  kind text not null,
  title text not null,
  body text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists user_moderation_notices_user_created_idx
  on public.user_moderation_notices (user_id, created_at desc);

alter table public.admin_user_actions enable row level security;
alter table public.user_moderation_notices enable row level security;

drop policy if exists "admin user actions read admins 5.173" on public.admin_user_actions;
create policy "admin user actions read admins 5.173" on public.admin_user_actions
for select to authenticated
using (exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid())));

drop policy if exists "user moderation notices read own 5.173" on public.user_moderation_notices;
create policy "user moderation notices read own 5.173" on public.user_moderation_notices
for select to authenticated
using (user_id = (select auth.uid()) or exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid())));

drop policy if exists "user moderation notices update own 5.173" on public.user_moderation_notices;
create policy "user moderation notices update own 5.173" on public.user_moderation_notices
for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create or replace function public.can_create_community_content()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.admin_user_statuses s
    where s.user_id = (select auth.uid())
      and s.status in ('banned','muted')
      and (s.expires_at is null or s.expires_at > now())
  );
$$;

revoke all on function public.can_create_community_content() from public;
grant execute on function public.can_create_community_content() to authenticated;

alter policy "auth insert own" on public.posts
with check ((select auth.uid()) = user_id and public.can_create_community_content());

alter policy "owner update" on public.posts
using ((select auth.uid()) = user_id and public.can_create_community_content())
with check ((select auth.uid()) = user_id and public.can_create_community_content());

alter policy "auth insert comment" on public.comments
with check ((select auth.uid()) = user_id and public.can_create_community_content());

create or replace function public.admin_moderate_user(
  p_user_id uuid,
  p_action_type text,
  p_reason_code text default null,
  p_note text default null,
  p_duration_days integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_action text := lower(coalesce(p_action_type, ''));
  v_duration integer := nullif(p_duration_days, 0);
  v_expires_at timestamptz;
  v_action_id bigint;
  v_title text;
  v_body text;
begin
  if not exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid())) then
    raise exception 'not_admin' using errcode = '42501';
  end if;
  if p_user_id = (select auth.uid()) then
    raise exception 'cannot_moderate_self' using errcode = '22023';
  end if;
  if v_action not in ('ban','mute','warning','unban','unmute') then
    raise exception 'invalid_action' using errcode = '22023';
  end if;
  if v_duration is not null and (v_duration < 1 or v_duration > 3650) then
    raise exception 'invalid_duration' using errcode = '22023';
  end if;
  v_expires_at := case when v_duration is null then null else now() + make_interval(days => v_duration) end;

  insert into public.admin_user_actions (user_id, action_type, reason_code, note, duration_days, expires_at, created_by)
  values (p_user_id, v_action, nullif(trim(p_reason_code), ''), nullif(trim(p_note), ''), v_duration, v_expires_at, (select auth.uid()))
  returning id into v_action_id;

  if v_action in ('ban','mute') then
    insert into public.admin_user_statuses (user_id, status, reason, reason_code, note, expires_at, created_by, updated_by, created_at, updated_at)
    values (p_user_id, case when v_action = 'ban' then 'banned' else 'muted' end, nullif(trim(p_reason_code), ''), nullif(trim(p_reason_code), ''), nullif(trim(p_note), ''), v_expires_at, (select auth.uid()), (select auth.uid()), now(), now())
    on conflict (user_id) do update set
      status = excluded.status, reason = excluded.reason, reason_code = excluded.reason_code,
      note = excluded.note, expires_at = excluded.expires_at, updated_by = excluded.updated_by, updated_at = now();
  elsif v_action in ('unban','unmute') then
    insert into public.admin_user_statuses (user_id, status, created_by, updated_by, created_at, updated_at)
    values (p_user_id, 'active', (select auth.uid()), (select auth.uid()), now(), now())
    on conflict (user_id) do update set status='active', reason=null, reason_code=null, note=null, expires_at=null, updated_by=(select auth.uid()), updated_at=now();
  end if;

  v_title := case v_action
    when 'ban' then '账号已被限制使用'
    when 'mute' then '账号已被禁言'
    when 'warning' then '社区规则提醒'
    else '账号限制已解除'
  end;
  v_body := concat_ws(E'\n',
    case when nullif(trim(p_reason_code), '') is not null then '处理原因：' || trim(p_reason_code) end,
    case when v_action in ('ban','mute') and v_expires_at is not null then '结束时间：' || to_char(v_expires_at at time zone 'America/Los_Angeles', 'YYYY-MM-DD HH24:MI') || '（洛杉矶时间）' end,
    case when v_action in ('ban','mute') and v_expires_at is null then '处理期限：长期，直至管理员解除' end,
    nullif(trim(p_note), '')
  );
  insert into public.user_moderation_notices (user_id, action_id, kind, title, body)
  values (p_user_id, v_action_id, v_action, v_title, coalesce(v_body, ''));

  return jsonb_build_object('action_id', v_action_id, 'action_type', v_action, 'expires_at', v_expires_at);
end;
$$;

revoke all on function public.admin_moderate_user(uuid,text,text,text,integer) from public;
grant execute on function public.admin_moderate_user(uuid,text,text,text,integer) to authenticated;

create or replace function public.admin_center_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not exists (select 1 from public.deal_admins a where a.user_id = (select auth.uid())) then
    raise exception 'not_admin' using errcode = '42501';
  end if;
  return jsonb_build_object(
    'users', coalesce((select jsonb_agg(to_jsonb(u) order by u.created_at desc) from (
      select au.id::text as user_id, au.email,
        coalesce(nullif(p.name,''), nullif(au.raw_user_meta_data->>'name',''), nullif(split_part(coalesce(au.email,''),'@',1),''),'未命名用户') as name,
        p.avatar, p.bio, p.tags, p.gender, p.birth, p.ip_location, au.created_at, au.last_sign_in_at,
        coalesce(p.updated_at, au.updated_at, au.created_at) as updated_at,
        (select count(*) from public.posts po where po.user_id = au.id) as post_count,
        s.status as moderation_status, s.reason_code, s.note as moderation_note, s.expires_at as moderation_expires_at
      from auth.users au left join public.profiles p on p.user_id=au.id left join public.admin_user_statuses s on s.user_id=au.id
      order by au.created_at desc limit 200
    ) u),'[]'::jsonb),
    'posts', coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc) from (select id,user_id,author,title,content,category,subcategory,community_meta,created_at,likes from public.posts order by created_at desc nulls last limit 120) p),'[]'::jsonb),
    'comments', coalesce((select jsonb_agg(to_jsonb(c) order by c.created_at desc) from (select id,post_id,user_id,name,text,created_at,parent_id,reply_to_name from public.comments order by created_at desc nulls last limit 200) c),'[]'::jsonb),
    'banned', coalesce((select jsonb_agg(to_jsonb(b) order by b.created_at desc) from (select id,user_id,action_type,reason_code,note,duration_days,expires_at,created_by,created_at from public.admin_user_actions order by created_at desc limit 300) b),'[]'::jsonb)
  );
end;
$$;

revoke all on function public.admin_center_snapshot() from public;
grant execute on function public.admin_center_snapshot() to authenticated;
