-- 乐生活 5.104：会员核销、兑换与优惠券核销的用户回执通知

create table if not exists public.member_activity_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  membership_id bigint,
  transaction_id bigint,
  coupon_claim_id bigint,
  kind text not null check (kind in ('stamp','points','reward','coupon')),
  title text not null,
  body text not null default '',
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists member_activity_notifications_user_created_idx
  on public.member_activity_notifications (user_id, created_at desc);

alter table public.member_activity_notifications enable row level security;

drop policy if exists "member activity user read 5.104" on public.member_activity_notifications;
create policy "member activity user read 5.104"
on public.member_activity_notifications for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "member activity merchant insert 5.104" on public.member_activity_notifications;
create policy "member activity merchant insert 5.104"
on public.member_activity_notifications for insert to authenticated
with check ((select auth.uid()) = merchant_user_id);

drop policy if exists "member activity user read mark 5.104" on public.member_activity_notifications;
create policy "member activity user read mark 5.104"
on public.member_activity_notifications for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

grant select, insert on public.member_activity_notifications to authenticated;
grant update (read_at) on public.member_activity_notifications to authenticated;
grant usage, select on sequence public.member_activity_notifications_id_seq to authenticated;
