-- 乐生活 5.101：用户领取优惠券、出示二维码与商家扫码核销

create table if not exists public.merchant_coupon_claims (
  id bigint generated by default as identity primary key,
  merchant_user_id uuid not null references auth.users(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  coupon_id text not null,
  coupon_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'claimed' check (status in ('claimed','redeemed','void')),
  claimed_at timestamptz not null default now(),
  redeemed_at timestamptz,
  redeemed_by uuid references auth.users(id),
  unique (merchant_user_id, user_id, coupon_id)
);

create index if not exists merchant_coupon_claims_user_status_idx
  on public.merchant_coupon_claims (user_id, status, claimed_at desc);
create index if not exists merchant_coupon_claims_merchant_status_idx
  on public.merchant_coupon_claims (merchant_user_id, status, claimed_at desc);

alter table public.merchant_coupon_claims enable row level security;

drop policy if exists "coupon claim owner or merchant read 5.101" on public.merchant_coupon_claims;
create policy "coupon claim owner or merchant read 5.101"
on public.merchant_coupon_claims for select to authenticated
using ((select auth.uid()) = user_id or (select auth.uid()) = merchant_user_id);

drop policy if exists "coupon claim owner insert 5.101" on public.merchant_coupon_claims;
create policy "coupon claim owner insert 5.101"
on public.merchant_coupon_claims for insert to authenticated
with check ((select auth.uid()) = user_id);

grant select, insert on public.merchant_coupon_claims to authenticated;
grant usage, select on sequence public.merchant_coupon_claims_id_seq to authenticated;

create or replace function public.redeem_merchant_coupon_claim(p_claim_id bigint)
returns public.merchant_coupon_claims
language plpgsql
security definer
set search_path = public
as $$
declare
  claim_row public.merchant_coupon_claims;
  merchant_coupons jsonb;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into claim_row
  from public.merchant_coupon_claims
  where id = p_claim_id
  for update;

  if not found then
    raise exception 'coupon_claim_not_found' using errcode = 'P0002';
  end if;
  if claim_row.merchant_user_id <> auth.uid() then
    raise exception 'not_coupon_merchant' using errcode = '42501';
  end if;
  if claim_row.status <> 'claimed' then
    raise exception 'coupon_already_redeemed' using errcode = '23514';
  end if;

  select coupons into merchant_coupons
  from public.merchants
  where user_id = auth.uid() and verified = true;
  if merchant_coupons is null then
    raise exception 'merchant_not_verified' using errcode = '42501';
  end if;
  if not exists (
    select 1 from jsonb_array_elements(merchant_coupons) with ordinality as item(value, ord)
    where coalesce(item.value->>'id', 'legacy-' || (item.ord - 1)::text) = claim_row.coupon_id
      and coalesce(item.value->>'active', 'true') <> 'false'
  ) then
    raise exception 'coupon_not_available' using errcode = '23514';
  end if;

  update public.merchant_coupon_claims
  set status = 'redeemed', redeemed_at = now(), redeemed_by = auth.uid()
  where id = claim_row.id
  returning * into claim_row;

  return claim_row;
end;
$$;

revoke all on function public.redeem_merchant_coupon_claim(bigint) from public;
revoke execute on function public.redeem_merchant_coupon_claim(bigint) from anon;
grant execute on function public.redeem_merchant_coupon_claim(bigint) to authenticated;
