(() => {
  const URL='https://ptxdxepmggmjcndgukjk.supabase.co', KEY='sb_publishable_h3x-jnCW-N8Nx3P6t_D8rA_CS9dgkP-';
  const app=document.querySelector('#merchantApp'), q=new URLSearchParams(location.search), pathParts=location.pathname.split('/').filter(Boolean), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const api=path=>fetch(URL+path,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});
  const back=()=>history.length>1?history.back():location.assign('/');
  const list=v=>Array.isArray(v)?v:(typeof v==='string'?(()=>{try{return JSON.parse(v)}catch(e){return []}})():[]);
  const imgs=p=>list(p.images).length?list(p.images):(p.image?[p.image]:[]);
  const market=String(q.get('market')||((pathParts.length===3&&pathParts[1]==='merchant')?pathParts[0]:'la')).toLowerCase(), slug=String(q.get('merchant')||q.get('m')||((pathParts.length===3&&pathParts[1]==='merchant')?pathParts[2]:'')).toLowerCase(); let merchant=null, tab='posts';
  const social=m=>{const raw=m.external_links; if(raw&&typeof raw==='object'&&!Array.isArray(raw))return Object.entries(raw).filter(([,u])=>u).slice(0,5);return []};
  const openFeature=(kind)=>{const base=encodeURIComponent(merchant.slug);const paths={rental:`/rental/?merchant=${base}`,auto_sales:`/autos/?merchant=${base}`,table_order:`/restaurant/?merchant=${base}`};location.assign(paths[kind]||'/');};
  async function load(){
    if(!slug){app.innerHTML='<div class="empty">缺少商家链接。</div>';return}
    try{const r=await api(`/rest/v1/merchants?market_code=eq.${encodeURIComponent(market)}&slug=eq.${encodeURIComponent(slug)}&verified=eq.true&select=*&limit=1`);merchant=(await r.json())[0];if(!merchant)throw Error('not found');render()}catch(e){app.innerHTML='<div class="empty">没有找到这家认证商家，请确认链接是否正确。</div>'}}
  async function render(){
    const features=new Set(list(merchant.enabled_features)), cover=merchant.cover_image?`style="background-image:url('${esc(merchant.cover_image)}')"`:'';
    const featureCards=[];if(features.has('table_order'))featureCards.push(['table_order','扫码点餐']);if(features.has('rental'))featureCards.push(['rental','租车预约']);if(features.has('auto_sales'))featureCards.push(['auto_sales','二手车买卖']);
    const res=await Promise.all([api(`/rest/v1/posts?user_id=eq.${encodeURIComponent(merchant.user_id)}&visibility=eq.public&select=id,title,excerpt,content,image,created_at&order=created_at.desc&limit=30`),Promise.resolve(merchant)]); const posts=(await res[0].json().catch(()=>[]))||[];
    const products=list(merchant.products||merchant.store_products).filter(p=>p&&p.active!==false); const coupons=list(merchant.coupons).filter(c=>c&&c.active!==false);
    const body=tab==='posts'?(posts.length?posts.map(p=>`<article class="post"><h3>${esc(p.title||'商家动态')}</h3><p>${esc(p.excerpt||p.content||'')}</p></article>`).join(''):'<div class="empty">商家暂时还没有发布动态。</div>'):tab==='store'?(products.length?products.map((p,i)=>`<article class="product" onclick="MerchantSite.product(${i})"><div class="product-image">${imgs(p)[0]?`<img src="${esc(imgs(p)[0])}" alt="">`:''}</div><div><h3>${esc(p.name||p.title||'商品')}</h3><p>${esc(p.description||'')}</p><div class="price">${p.price!==undefined?'$'+Number(p.price).toFixed(2):'咨询商家'}</div></div></article>`).join(''):'<div class="empty">商家正在整理商品与服务。</div>'):(coupons.length?coupons.map(c=>`<article class="coupon"><h3>${esc(c.title||'店铺优惠')} <b>${esc(c.badge||'优惠')}</b></h3><p>${esc(c.description||'到店出示使用，具体以商家说明为准。')}</p></article>`).join(''):'<div class="empty">暂时没有可领取的优惠券。</div>');
    app.innerHTML=`<header class="top"><button onclick="MerchantSite.back()">‹</button><b>商家微网站</b><button onclick="MerchantSite.share()">⌑</button></header><section class="hero ${merchant.cover_image?'cover':''}" ${cover}><div class="identity"><div class="logo">${merchant.logo?`<img src="${esc(merchant.logo)}" alt="">`:esc((merchant.business_name||'商').slice(0,1))}</div><div><h1>${esc(merchant.business_name||'认证商家')}</h1><small>乐生活认证商家</small></div></div><p class="intro">${esc(merchant.intro||merchant.description||'')}</p></section><section class="info"><div class="meta">${merchant.category?`<span>${esc(merchant.category)}${merchant.subcategory?' · '+esc(merchant.subcategory):''}</span>`:''}${merchant.business_hours?`<span>营业时间：${esc(typeof merchant.business_hours==='string'?merchant.business_hours:'详见店铺')}</span>`:''}${merchant.address?`<span>${esc(merchant.address)}</span>`:''}</div><div class="actions"><a class="primary" href="tel:${esc(merchant.phone||'')}">联系商家</a><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(merchant.address||merchant.business_name||'')}" target="_blank">导航</a><button onclick="MerchantSite.copy()">复制链接</button></div>${social(merchant).length?`<div class="social">${social(merchant).map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(n)}</a>`).join('')}</div>`:''}</section>${featureCards.length?`<section class="features">${featureCards.map(([id,name])=>`<button class="feature" onclick="MerchantSite.feature('${id}')">${esc(name)}</button>`).join('')}</section>`:''}<nav class="tabs"><button class="${tab==='posts'?'on':''}" onclick="MerchantSite.tab('posts')">最新动态</button><button class="${tab==='store'?'on':''}" onclick="MerchantSite.tab('store')">店铺</button><button class="${tab==='coupons'?'on':''}" onclick="MerchantSite.tab('coupons')">优惠券</button></nav><section class="content">${body}</section><div class="modal" id="productModal" onclick="if(event.target.id==='productModal')MerchantSite.close()"><div class="sheet" id="productSheet"></div></div>`;
    window._merchantProducts=products;
  }
  const product=i=>{const p=window._merchantProducts[i];if(!p)return;document.querySelector('#productSheet').innerHTML=`<h2>${esc(p.name||p.title||'商品')}</h2>${imgs(p)[0]?`<img src="${esc(imgs(p)[0])}" style="width:100%;border-radius:10px;max-height:270px;object-fit:cover" alt="">`:''}<p style="white-space:pre-line;line-height:1.6;color:#74756c">${esc(p.description||'请联系商家了解详情。')}</p><h3 class="price">${p.price!==undefined?'$'+Number(p.price).toFixed(2):'咨询商家'}</h3><button onclick="location.href='tel:${esc(merchant.phone||'')}'">联系商家</button></div>`;document.querySelector('#productModal').classList.add('open')};
  const copy=()=>navigator.clipboard?.writeText(location.href).then(()=>alert('链接已复制')).catch(()=>prompt('复制链接',location.href));
  window.MerchantSite={back,tab:v=>{tab=v;render()},feature:openFeature,product,close:()=>document.querySelector('#productModal')?.classList.remove('open'),copy,share:()=>navigator.share?navigator.share({title:merchant.business_name,text:merchant.intro,url:location.href}):copy()};load();
})();
